# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/aggregation.pyx

from pylibcudf.libcudf.aggregation import Kind
from pylibcudf.libcudf.aggregation import bitwise_op
from pylibcudf.libcudf.aggregation import bitwise_op as BitwiseOp
from pylibcudf.libcudf.aggregation import correlation_type
from pylibcudf.libcudf.aggregation import correlation_type as CorrelationType
from pylibcudf.libcudf.aggregation import ewm_history
from pylibcudf.libcudf.aggregation import ewm_history as EWMHistory
from pylibcudf.libcudf.aggregation import rank_method
from pylibcudf.libcudf.aggregation import rank_method as RankMethod
from pylibcudf.libcudf.aggregation import rank_percentage
from pylibcudf.libcudf.aggregation import rank_percentage as RankPercentage
from pylibcudf.libcudf.types import (interpolation, nan_equality,
                                     null_equality, null_order, null_policy,
                                     order, size_type)
from pylibcudf.libcudf.types import udf_source_type as UdfSourceType

from .types import DataType

__all__ = ['Aggregation', 'BitwiseOp', 'CorrelationType', 'EWMHistory', 'Kind', 'RankMethod', 'RankPercentage', 'UdfSourceType', 'all', 'any', 'argmax', 'argmin', 'bitwise', 'collect_list', 'collect_set', 'correlation', 'count', 'covariance', 'ewma', 'histogram', 'is_valid_aggregation', 'lag', 'lead', 'm2', 'max', 'mean', 'median', 'merge_histogram', 'merge_lists', 'merge_m2', 'merge_sets', 'merge_tdigest', 'min', 'nth_element', 'nunique', 'product', 'quantile', 'rank', 'row_number', 'std', 'sum', 'sum_of_squares', 'tdigest', 'udf', 'variance']

class Aggregation:
    """A type of aggregation to perform.

    Aggregations are passed to APIs like
    :py:func:`~pylibcudf.groupby.GroupBy.aggregate` to indicate what
    operations to perform. Using a class for aggregations provides a unified
    API for handling parametrizable aggregations. This class should never be
    instantiated directly, only via one of the factory functions.

    For details, see :cpp:class:`cudf::aggregation`.
    """
    def __init__(self): ...
    def __eq__(self, other): ...
    def __hash__(self): ...
    def kind(self):
        """Get the kind of the aggregation."""
    def __repr__(self): ...

def sum() -> Aggregation:
    """Create a sum aggregation.

    For details, see :cpp:func:`make_sum_aggregation`.

    Returns
    -------
    Aggregation
        The sum aggregation.
    """
def product() -> Aggregation:
    """Create a product aggregation.

    For details, see :cpp:func:`make_product_aggregation`.

    Returns
    -------
    Aggregation
        The product aggregation.
    """
def min() -> Aggregation:
    """Create a min aggregation.

    For details, see :cpp:func:`make_min_aggregation`.

    Returns
    -------
    Aggregation
        The min aggregation.
    """
def max() -> Aggregation:
    """Create a max aggregation.

    For details, see :cpp:func:`make_max_aggregation`.

    Returns
    -------
    Aggregation
        The max aggregation.
    """
def ewma(center_of_mass: float, history: ewm_history) -> Aggregation:
    """Create a EWMA aggregation.

    For details, see :cpp:func:`make_ewma_aggregation`.

    Parameters
    ----------
    center_of_mass : float
        The decay in terms of the center of mass
    history : ewm_history
        Whether or not to treat the history as infinite.

    Returns
    -------
    Aggregation
        The EWMA aggregation.
    """
def count(null_handling: null_policy=null_policy.EXCLUDE) -> Aggregation:
    """Create a count aggregation.

    For details, see :cpp:func:`make_count_aggregation`.

    Parameters
    ----------
    null_handling : null_policy, default EXCLUDE
        Whether or not nulls should be included.

    Returns
    -------
    Aggregation
        The count aggregation.
    """
def any() -> Aggregation:
    """Create an any aggregation.

    For details, see :cpp:func:`make_any_aggregation`.

    Returns
    -------
    Aggregation
        The any aggregation.
    """
def all() -> Aggregation:
    """Create an all aggregation.

    For details, see :cpp:func:`make_all_aggregation`.

    Returns
    -------
    Aggregation
        The all aggregation.
    """
def sum_of_squares() -> Aggregation:
    """Create a sum_of_squares aggregation.

    For details, see :cpp:func:`make_sum_of_squares_aggregation`.

    Returns
    -------
    Aggregation
        The sum_of_squares aggregation.
    """
def mean() -> Aggregation:
    """Create a mean aggregation.

    For details, see :cpp:func:`make_mean_aggregation`.

    Returns
    -------
    Aggregation
        The mean aggregation.
    """
def variance(ddof: size_type=1) -> Aggregation:
    """Create a variance aggregation.

    For details, see :cpp:func:`make_variance_aggregation`.

    Parameters
    ----------
    ddof : int, default 1
        Delta degrees of freedom.

    Returns
    -------
    Aggregation
        The variance aggregation.
    """
def std(ddof: size_type=1) -> Aggregation:
    """Create a std aggregation.

    For details, see :cpp:func:`make_std_aggregation`.

    Parameters
    ----------
    ddof : int, default 1
        Delta degrees of freedom. The default value is 1.

    Returns
    -------
    Aggregation
        The std aggregation.
    """
def median() -> Aggregation:
    """Create a median aggregation.

    For details, see :cpp:func:`make_median_aggregation`.

    Returns
    -------
    Aggregation
        The median aggregation.
    """
def quantile(quantiles: list[float], interp: interpolation=interpolation.LINEAR) -> Aggregation:
    """Create a quantile aggregation.

    For details, see :cpp:func:`make_quantile_aggregation`.

    Parameters
    ----------
    quantiles : list
        List of quantiles to compute, should be between 0 and 1.
    interp : interpolation, default LINEAR
        Interpolation technique to use when the desired quantile lies between
        two data points.

    Returns
    -------
    Aggregation
        The quantile aggregation.
    """
def argmax() -> Aggregation:
    """Create an argmax aggregation.

    For details, see :cpp:func:`make_argmax_aggregation`.

    Returns
    -------
    Aggregation
        The argmax aggregation.
    """
def argmin() -> Aggregation:
    """Create an argmin aggregation.

    For details, see :cpp:func:`make_argmin_aggregation`.

    Returns
    -------
    Aggregation
        The argmin aggregation.
    """
def nunique(null_handling: null_policy=null_policy.EXCLUDE) -> Aggregation:
    """Create a nunique aggregation.

    For details, see :cpp:func:`make_nunique_aggregation`.

    Parameters
    ----------
    null_handling : null_policy, default EXCLUDE
        Whether or not nulls should be included.

    Returns
    -------
    Aggregation
        The nunique aggregation.
    """
def nth_element(n: size_type, null_handling: null_policy=null_policy.INCLUDE) -> Aggregation:
    """Create a nth_element aggregation.

    For details, see :cpp:func:`make_nth_element_aggregation`.

    Parameters
    ----------
    null_handling : null_policy, default INCLUDE
        Whether or not nulls should be included.

    Returns
    -------
    Aggregation
        The nth_element aggregation.
    """
def collect_list(null_handling: null_policy=null_policy.INCLUDE) -> Aggregation:
    """Create a collect_list aggregation.

    For details, see :cpp:func:`make_collect_list_aggregation`.

    Parameters
    ----------
    null_handling : null_policy, default INCLUDE
        Whether or not nulls should be included.

    Returns
    -------
    Aggregation
        The collect_list aggregation.
    """
def collect_set(null_handling=null_policy.INCLUDE, nulls_equal=null_equality.EQUAL, nans_equal=nan_equality.ALL_EQUAL) -> Aggregation:
    """Create a collect_set aggregation.

    For details, see :cpp:func:`make_collect_set_aggregation`.

    Parameters
    ----------
    null_handling : null_policy, default INCLUDE
        Whether or not nulls should be included.
    nulls_equal : null_equality, default EQUAL
        Whether or not nulls should be considered equal.
    nans_equal : nan_equality, default ALL_EQUAL
        Whether or not NaNs should be considered equal.

    Returns
    -------
    Aggregation
        The collect_set aggregation.
    """
def udf(operation: str, output_type: DataType) -> Aggregation:
    """Create a udf aggregation.

    For details, see :cpp:func:`make_udf_aggregation`.

    Parameters
    ----------
    operation : str
        The operation to perform as a string of PTX code.
    output_type : DataType
        The output type of the aggregation.

    Returns
    -------
    Aggregation
        The udf aggregation.
    """
def correlation(type: correlation_type, min_periods: size_type) -> Aggregation:
    """Create a correlation aggregation.

    For details, see :cpp:func:`make_correlation_aggregation`.

    Parameters
    ----------
    type : correlation_type
        The type of correlation to compute.
    min_periods : int
        The minimum number of observations to consider for computing the
        correlation.

    Returns
    -------
    Aggregation
        The correlation aggregation.
    """
def covariance(min_periods: size_type, ddof: size_type) -> Aggregation:
    """Create a covariance aggregation.

    For details, see :cpp:func:`make_covariance_aggregation`.

    Parameters
    ----------
    min_periods : int
        The minimum number of observations to consider for computing the
        covariance.
    ddof : int
        Delta degrees of freedom.

    Returns
    -------
    Aggregation
        The covariance aggregation.
    """
def rank(method: rank_method, column_order: order=order.ASCENDING, null_handling: null_policy=null_policy.EXCLUDE, null_precedence: null_order=null_order.AFTER, percentage: rank_percentage=rank_percentage.NONE) -> Aggregation:
    """Create a rank aggregation.

    For details, see :cpp:func:`make_rank_aggregation`.

    Parameters
    ----------
    method : rank_method
        The method to use for ranking.
    column_order : order, default ASCENDING
        The order in which to sort the column.
    null_handling : null_policy, default EXCLUDE
        Whether or not nulls should be included.
    null_precedence : null_order, default AFTER
        Whether nulls should come before or after non-nulls.
    percentage : rank_percentage, default NONE
        Whether or not ranks should be converted to percentages, and if so,
        the type of normalization to use.

    Returns
    -------
    Aggregation
        The rank aggregation.
    """
def histogram() -> Aggregation:
    """Create a histogram aggregation.

    For details, see :cpp:func:`make_histogram_aggregation`.

    Returns
    -------
    Aggregation
        The histogram aggregation.
    """
def m2() -> Aggregation:
    """Create a M2 aggregation.

    For details, see :cpp:func:`make_m2_aggregation`.

    Returns
    -------
    Aggregation
        The M2 aggregation.
    """
def merge_m2() -> Aggregation:
    """Create a merge M2 aggregation.

    For details, see :cpp:func:`make_merge_m2_aggregation`.

    Returns
    -------
    Aggregation
        The merge M2 aggregation.
    """
def merge_histogram() -> Aggregation:
    """Create a merge histogram aggregation.

    For details, see :cpp:func:`make_merge_histogram_aggregation`.

    Returns
    -------
    Aggregation
        The merge histogram aggregation.
    """
def merge_lists() -> Aggregation:
    """Create a merge lists aggregation.

    For details, see :cpp:func:`make_merge_lists_aggregation`.

    Returns
    -------
    Aggregation
        The merge lists aggregation.
    """
def merge_sets(nulls_equal: null_equality=null_equality.EQUAL, nans_equal: nan_equality=nan_equality.ALL_EQUAL) -> Aggregation:
    """Create a merge sets aggregation.

    For details, see :cpp:func:`make_merge_sets_aggregation`.

    Parameters
    ----------
    nulls_equal : null_equality, default EQUAL
        Whether or not nulls should be considered equal.
    nans_equal : nan_equality, default ALL_EQUAL
        Whether or not NaNs should be considered equal.

    Returns
    -------
    Aggregation
        The merge sets aggregation.
    """
def merge_tdigest(max_centroids: int) -> Aggregation:
    """Create a merge TDIGEST aggregation.

    For details, see :cpp:func:`make_merge_tdigest_aggregation`.

    Parameters
    ----------
    max_centroids : int
        Parameter controlling compression level and accuracy
        on subsequent queries on the output tdigest data.

    Returns
    -------
    Aggregation
        The merge TDIGEST aggregation.
    """
def tdigest(max_centroids: int) -> Aggregation:
    """Create a TDIGEST aggregation.

    For details, see :cpp:func:`make_tdigest_aggregation`.

    Parameters
    ----------
    max_centroids : int
        Parameter controlling compression level and accuracy
        on subsequent queries on the output tdigest data.

    Returns
    -------
    Aggregation
        The TDIGEST aggregation.
    """
def bitwise(op: bitwise_op) -> Aggregation:
    """Create a bitwise aggregation.

    For details, see :cpp:func:`make_bitwise_aggregation`.

    Parameters
    ----------
    op : BitwiseOp
        The bitwise operation to perform on the input column

    Returns
    -------
    Aggregation
        The bitwise aggregation.
    """
def lag(offset: size_type) -> Aggregation:
    """Create a lag aggregation.

    For details, see :cpp:func:`make_lag_aggregation`.

    Parameters
    ----------
    offset : int
        The number of rows to lag the input

    Returns
    -------
    Aggregation
        The lag aggregation.
    """
def lead(offset: size_type) -> Aggregation:
    """Create a lead aggregation.

    For details, see :cpp:func:`make_lead_aggregation`.

    Parameters
    ----------
    offset : int
        The number of rows to lead the input

    Returns
    -------
    Aggregation
        The lead aggregation.
    """
def row_number() -> Aggregation:
    """Create a row_number aggregation.

    For details, see :cpp:func:`make_row_number_aggregation`.

    Returns
    -------
    Aggregation
        The row_number aggregation.
    """
def is_valid_aggregation(source: DataType, agg: Aggregation) -> bool:
    """
    Return if an aggregation is supported for a given datatype.

    Parameters
    ----------
    source
        The type of the column the aggregation is being performed on.
    agg
        The aggregation.

    Returns
    -------
    True if the aggregation is supported.
    """
