# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/column.pyx

from collections.abc import Iterable, Sequence

from pylibcudf.libcudf.types import size_type
from pylibcudf.typing import (CudaStreamLike, SupportsArrayInterface,
                              SupportsCudaArrayInterface)
from rmm.pylibrmm.device_buffer import DeviceBuffer
from rmm.pylibrmm.memory_resource import DeviceMemoryResource
from rmm.pylibrmm.stream import Stream

from ._interop_helpers import ArrowLike, ColumnMetadata
from .scalar import Scalar
from .types import DataType

__all__ = ['Column', 'ListsColumnView', 'StructsColumnView', 'is_c_contiguous']

class _ArrowColumnHolder:
    """A holder for an Arrow column for gpumemoryview lifetime management."""

class OwnerWithCAI:
    """An interface for column view's data with gpumemoryview via CAI."""
    @property
    def __cuda_array_interface__(self): ...

class OwnerMaskWithCAI:
    """An interface for column view's null mask with gpumemoryview via CAI."""
    @property
    def __cuda_array_interface__(self): ...

class ArrayInterfaceWrapper:
    def __init__(self, iface): ...

class Column:
    """A container of nullable device data as a column of elements.

    This class is an implementation of `Arrow columnar data specification
    <https://arrow.apache.org/docs/format/Columnar.html>`__ for data stored on
    GPUs. It relies on Python memoryview-like semantics to maintain shared
    ownership of the data it is constructed with, so any input data may also be
    co-owned by other data structures. The Column is designed to be operated on
    using algorithms backed by libcudf.

    Parameters
    ----------
    data_type : DataType
        The type of data in the column.
    size : size_type
        The number of rows in the column.
    data : gpumemoryview
        The data the column will refer to.
    mask : gpumemoryview
        The null mask for the column.
    null_count : int
        The number of null rows in the column.
    offset : int
        The offset into the data buffer where the column's data begins.
    children : Iterable[Column]
        The children of this column if it is a compound column type.
    validate : bool, default True
        Whether to validate that data and mask satisfy Span protocol.
    """
    __hash__ = None

    def __init__(self, data_type: DataType, size: size_type, data: object, mask: object, null_count: size_type, offset: size_type, children: Iterable[Column], validate: bool=True): ...
    def to_arrow(self, metadata: ColumnMetadata | str | None=None, stream: Stream | None=None) -> ArrowLike:
        """Create a pyarrow array from a pylibcudf column.

        Parameters
        ----------
        metadata : ColumnMetadata | str | None
            The metadata to attach to the column.
        stream : Stream | None
            CUDA stream on which to perform the operation.

        Returns
        -------
        pyarrow.Array
        """
    @staticmethod
    def from_arrow(obj: ArrowLike, dtype: DataType | None=None, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> ArrowLike:
        """
        Create a Column from an Arrow-like object using the Arrow C Data Interface.

        This method supports host and device Arrow arrays or streams. It detects
        the type of Arrow object provided and constructs a `pylibcudf.Column`
        accordingly using the appropriate Arrow C pointer-based interface.

        Parameters
        ----------
        obj : Arrow-like
            An object implementing one of the following:
            - `__arrow_c_array__` (host Arrow array)
            - `__arrow_c_device_array__` (device Arrow array)
            - `__arrow_c_stream__` (host Arrow stream)
            - `__arrow_c_device_stream__` (device Arrow stream)
        dtype : DataType | None
            The pylibcudf data type.
        stream : Stream | None
            CUDA stream on which to perform the operation.
        mr : DeviceMemoryResource | None
            Device memory resource for allocations.

        Returns
        -------
        Column
            A `pylibcudf.Column` representing the Arrow data.

        Raises
        ------
        NotImplementedError
            If the Arrow-like object is a device stream (`__arrow_c_device_stream__`).
            If the dtype argument is not None.
        ValueError
            If the object does not implement a known Arrow C interface.

        Notes
        -----
        - This method supports zero-copy construction for device arrays.
        """
    @staticmethod
    def from_rmm_buffer(buff: DeviceBuffer, dtype: DataType, size: size_type, children: Iterable[Column]):
        """
        Create a Column from an RMM DeviceBuffer.

        Parameters
        ----------
        buff : DeviceBuffer
            The data rmm.DeviceBuffer.
        size : size_type
            The number of rows in the column.
        dtype : DataType
            The type of the data in the buffer.
        children : Iterable[Column]
            The child columns.

        Notes
        -----
        To provide a mask and null count, use `Column.with_mask` after
        this method.
        """
    def with_mask(self, mask: object, null_count: size_type, validate: bool=True) -> Column:
        """Augment this column with a new null mask.

        Parameters
        ----------
        mask : Span-like or None
            New mask (or None to unset the mask). Must satisfy Span protocol.
        null_count : int
            New null count. If this is incorrect, bad things happen.
        validate : bool, default True
            Whether to validate that mask satisfies Span protocol.

        Returns
        -------
        New Column object sharing data with self (except for the mask which is new).
        """
    @staticmethod
    def from_scalar(slr: Scalar, size: size_type, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None):
        """Create a Column from a Scalar.

        Parameters
        ----------
        slr : Scalar
            The scalar to create a column from.
        size : size_type
            The number of elements in the column.
        stream : Stream | None
            CUDA stream on which to perform the operation.

        Returns
        -------
        Column
            A Column containing the scalar repeated `size` times.
        """
    def to_scalar(self, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Scalar:
        """
        Return the first value of 1-element column as a Scalar.

        Raises
        ------
        ValueError
            If the column has more than one row.
        stream : Stream | None
            CUDA stream on which to perform the operation.
        mr : DeviceMemoryResource | None
            Device memory resource used to allocate the returned scalar's device memory.

        Returns
        -------
        Scalar
            A Scalar representing the only value in the column, including nulls.
        """
    @staticmethod
    def all_null_like(like: Column, size: size_type, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None):
        """Create an all null column from a template.

        Parameters
        ----------
        like : Column
            Column whose type we should mimic
        size : int
            Number of rows in the resulting column.
        stream : Stream | None
            CUDA stream on which to perform the operation.

        Returns
        -------
        Column
            An all-null column of `size` rows and type matching `like`.
        """
    @classmethod
    def from_array_interface(cls, obj: SupportsArrayInterface, stream: CudaStreamLike | None=None):
        """
        Create a Column from an object implementing the NumPy Array Interface.

        If the object provides a raw memory pointer via the "data" field,
        we use that pointer directly and avoid copying. Otherwise, a ValueError
        is raised.

        Parameters
        ----------
        obj : Any
            Must implement the ``__array_interface__`` protocol.
        stream : Stream | None
            CUDA stream on which to perform the operation.

        Returns
        -------
        Column
            A Column containing the data from the array interface.

        Raises
        ------
        TypeError
            If the object does not implement ``__array_interface__``.
        ValueError
            If the array is not 1D or 2D, or is not C-contiguous.
            If the number of rows exceeds size_type limit.
            If the 'data' field is invalid.
        NotImplementedError
            If the object has a mask.
        """
    @classmethod
    def from_cuda_array_interface(cls, obj: SupportsCudaArrayInterface, stream: CudaStreamLike | None=None):
        """
        Create a Column from an object implementing the CUDA Array Interface.

        Parameters
        ----------
        obj : Any
            Must implement the ``__cuda_array_interface__`` protocol.
        stream : Stream | None
            CUDA stream on which to perform the operation.

        Returns
        -------
        Column
            A Column containing the data from the CUDA array interface.

        Raises
        ------
        TypeError
            If the object does not support ``__cuda_array_interface__``.
        ValueError
            If the object is not 1D or 2D, or is not C-contiguous.
            If the number of rows exceeds size_type limit.
        NotImplementedError
            If the object has a mask.
        """
    @classmethod
    def from_array(cls, obj: SupportsCudaArrayInterface | SupportsArrayInterface, stream: CudaStreamLike | None=None):
        """
        Create a Column from any object which supports the NumPy
        or CUDA array interface.

        Parameters
        ----------
        obj : object
            The input array to be converted into a `pylibcudf.Column`.
        stream : Stream | None
            CUDA stream on which to perform the operation.

        Returns
        -------
        Column

        Raises
        ------
        TypeError
            If the input does not implement a supported array interface.

        Notes
        -----
        - Only C-contiguous host and device ndarrays are supported.
          For device arrays, the data is not copied.

        Examples
        --------
        >>> import pylibcudf as plc
        >>> import cupy as cp
        >>> cp_arr = cp.array([[1,2],[3,4]])
        >>> col = plc.Column.from_array(cp_arr)
        """
    @staticmethod
    def from_iterable_of_py(obj: Iterable, dtype: DataType | None=None, stream: CudaStreamLike | None=None) -> Column:
        """
        Create a Column from a Python iterable of scalar values or nested iterables.

        Parameters
        ----------
        obj : Iterable
            An iterable of Python scalar values (int, float, bool, str) or nested lists.
        dtype : DataType | None
            The type of the leaf elements. If not specified, the type is inferred.
        stream : Stream | None
            CUDA stream on which to perform the operation.

        Returns
        -------
        Column
            A Column containing the data from the input iterable.

        Raises
        ------
        TypeError
            If the input contains unsupported scalar types.
        ValueError
            If the iterable is empty and dtype is not provided.

        Notes
        -----
        - Only scalar types int, float, bool, and str are supported.
        - Nested iterables must be materialized as lists.
        - Jagged nested lists are not supported. Inner lists must have the same shape.
        - Nulls (None) are not currently supported in input values.
        - dtype must match the inferred or actual type of the scalar values
        - Large strings are supported, meaning the combined length of all strings
          (in bytes) can exceed the maximum 32-bit integer value. In that case,
          the offsets column is automatically promoted to use 64-bit integers.
        """
    def to_pylist(self) -> list:
        """
        Convert the Column to a Python list.

        Only supports fixed-width and string columns.

        Returns
        -------
        list
            A list of Python objects representing the column data.

        Raises
        ------
        NotImplementedError
            If the column type is not fixed-width or string.
        """
    @classmethod
    def struct_from_children(cls, children: Iterable[Column]):
        """
        Create a struct Column from a list of child columns.

        Parameters
        ----------
        children : Iterable[Column]
            A list of child columns.

        Returns
        -------
        Column
            A struct Column with the provided the child columns.

        Notes
        -----
        The null count and null mask is taken from the first child column.
        Use `Column.with_mask` on the result of struct_from_children to reset
        the null count and mask.
        """
    def type(self) -> DataType:
        """The type of data in the column."""
    def child(self, index: size_type) -> Column:
        """Get a child column of this column.

        Parameters
        ----------
        index : size_type
            The index of the child column to get.

        Returns
        -------
        Column
            The child column.
        """
    def num_children(self) -> size_type:
        """The number of children of this column."""
    def list_view(self) -> ListsColumnView:
        """Accessor for methods of a Column that are specific to lists."""
    def struct_view(self) -> StructsColumnView:
        """Accessor for methods of a Column that are specific to structs."""
    def data(self) -> object:
        """The data buffer of the column."""
    def null_mask(self) -> object:
        """The null mask of the column."""
    def size(self) -> size_type:
        """The number of elements in the column."""
    def offset(self) -> size_type:
        """The offset of the column."""
    def null_count(self) -> size_type:
        """The number of null elements in the column."""
    def set_null_count(self, null_count: size_type) -> None:
        """Set the null count of the column.

        Parameters
        ----------
        null_count : size_type
            The new null count of the column.
        """
    def children(self) -> list:
        """The children of the column."""
    def copy(self, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
        """Create a copy of the column."""
    def device_buffer_size(self) -> int:
        """
        The total size of the device buffers used by the Column.

        Notes
        -----
        Since Columns rely on Python memoryview-like semantics to maintain
        shared ownership of the data, the device buffers underlying this column
        might be shared between other data structures including other columns.

        Returns
        -------
        Number of bytes.
        """
    def _create_nested_column_metadata(self): ...
    def _to_schema(self, metadata=None):
        """Create an Arrow schema from this Column."""
    def _to_host_array(self, stream: CudaStreamLike): ...
    def _to_device_array(self): ...
    def __arrow_c_array__(self, requested_schema=None): ...
    def __arrow_c_device_array__(self, requested_schema=None, **kwargs): ...

class ListsColumnView:
    """Accessor for methods of a Column that are specific to lists."""
    __hash__ = None

    def __init__(self, col: Column): ...
    def child(self):
        """The data column of the underlying list column."""
    def offsets(self):
        """The offsets column of the underlying list column."""
    def get_sliced_child(self, stream: CudaStreamLike | None=None) -> Column:
        """
        Get the list elements child properly sliced to match parent's view.

        Parameters
        ----------
        stream : Stream, optional
            CUDA stream to use

        Returns
        -------
        Column
            The sliced elements column
        """

class StructsColumnView:
    """Accessor for methods of a Column that are specific to structs."""
    __hash__ = None

    def __init__(self, col: Column): ...
    def get_sliced_child(self, index: int, stream: CudaStreamLike | None=None) -> Column:
        """
        Get the struct elements child properly sliced to match parent's view.

        Parameters
        ----------
        index : int
            The index of the child to get.
        stream : Stream, optional
            CUDA stream to use

        Returns
        -------
        Column
            The sliced elements column
        """

def _infer_list_depth_and_dtype(obj: list) -> tuple[int, type]:
    """Infer the nesting depth and final scalar type."""
def _flatten_nested_list(obj: list, depth: int) -> tuple[list, tuple[int, ...]]:
    """Flatten a nested list and compute the shape"""
def _infer_shape(obj: list, depth: int) -> tuple[int, ...]: ...
def _flatten(obj: list, out: list, offset: int) -> int: ...
def _prepare_array_metadata(iface: dict) -> tuple[int, int, tuple[int, ...], tuple[int, ...] | None, DataType]:
    """
    Parse and validate a CUDA or NumPy array interface dictionary.

    Parameters
    ----------
    iface : dict
        A dictionary conforming to the __cuda_array_interface__
        or __array_interface__ spec.

    Returns
    -------
    tuple
        - data pointer (int)
        - total number of bytes (int)
        - shape (tuple[int, ...])
        - strides (tuple[int, ...] | None)
        - data type (pylibcudf.DataType)

    Raises
    ------
    ValueError
        If the interface is invalid, big-endian, non-contiguous,
        or exceed the size_type limit.
    """
def is_c_contiguous(shape: Sequence[int], strides: None | Sequence[int], itemsize: int) -> bool:
    """Determine if shape and strides are C-contiguous

    Parameters
    ----------
    shape : Sequence[int]
        Number of elements in each dimension.
    strides : None | Sequence[int]
        The stride of each dimension in bytes.
        If None, the memory layout is C-contiguous.
    itemsize : int
        Size of an element in bytes.

    Returns
    -------
    bool
        The boolean answer.
    """
