# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/concatenate.pyx

from collections.abc import Sequence

from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

from .column import Column
from .table import Table

__all__ = ['concatenate']

def concatenate(objects: Sequence[Column] | Sequence[Table], stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None):
    """Concatenate columns or tables.

    Parameters
    ----------
    objects : Sequence[Column] | Sequence[Table]
        The Columns or Tables to concatenate.
    stream : Stream | None
        CUDA stream on which to perform the operation.
    mr : DeviceMemoryResource | None
        Device memory resource used to allocate the returned object's device memory.

    Returns
    -------
    Union[Column, Table]
        The concatenated Column or Table.
    """
