# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/contiguous_split.pyx

from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

from .table import Table

__all__ = ['ChunkedPack', 'PackedColumns', 'pack', 'unpack', 'unpack_from_memoryviews']

class HostBuffer:
    """Owning host buffer that implements the buffer protocol"""
    __hash__ = None

    def __getbuffer__(self, buffer: ..., flags: int): ...
    def __releasebuffer__(self, buffer: ...): ...

class PackedColumns:
    """Column data in a serialized format.

    Contains data from an array of columns in two contiguous buffers:
    one on host, which contains table metadata and one on device which
    contains the table data.

    For details, see :cpp:class:`cudf::packed_columns`.
    """
    __hash__ = None

    def __init__(self): ...
    def release(self) -> tuple:
        """Releases and returns the underlying serialized metadata and gpu data.

        The ownership of the memory are transferred to the returned buffers. After
        this call, `self` is empty.

        Returns
        -------
        memoryview (of a HostBuffer)
            The serialized metadata as contiguous host memory.
        gpumemoryview (of a rmm.DeviceBuffer)
            The serialized gpu data as contiguous device memory.
        """

class ChunkedPack:
    """
    A chunked version of :func:`pack`.

    This object can be used to pack (and therefore serialize) a table
    piece-by-piece through a user-provided staging buffer. This is
    useful when we want the end result to end up in host memory, but
    want control over the memory footprint.
    """
    def __init__(self): ...
    @staticmethod
    def create(input: Table, user_buffer_size: int, stream: CudaStreamLike | None=None, temp_mr: DeviceMemoryResource | None=None):
        """
        Create a chunked packer.

        Parameters
        ----------
        input
            The table to pack.
        user_buffer_size
            Size of the staging buffer to pack into, must be at least 1MB.
        stream : Stream | None
            Stream used for device memory operations and kernel launches.
        temp_mr : DeviceMemoryResource | None
            Memory resource for scratch allocations.

        Returns
        -------
        New ChunkedPack object.
        """
    def has_next(self) -> bool:
        """
        Check if the packer has more chunks to pack.

        Returns
        -------
        True if the packer has chunks still to pack.
        """
    def get_total_contiguous_size(self) -> int:
        """
        Get the total size of the packed data.

        Returns
        -------
        Size of packed data.
        """
    def next(self, buf: object) -> int:
        """
        Pack the next chunk into the provided device buffer.

        Parameters
        ----------
        buf : Span-like object
            The device buffer to use as a staging buffer, must be at
            least as large as the `user_buffer_size` used to construct the
            packer.

        Returns
        -------
        Number of bytes packed.

        Notes
        -----
        This is stream-ordered with respect to the stream used when
        creating the `ChunkedPack`.
        """
    def build_metadata(self) -> memoryview:
        """
        Build the metadata for the packed representation.

        Returns
        -------
        memoryview of metadata suitable for passing to `unpack_from_memoryviews`.
        """
    def pack_to_host(self, buf: object) -> tuple:
        """
        Pack the entire table into a host buffer.

        Parameters
        ----------
        buf : Span-like object
        The device buffer to use as a staging buffer, must be at
        least as large as the `user_buffer_size` used to construct the
        packer.

        Returns
        -------
        tuple of metadata and packed host data (as memoryviews)

        Notes
        -----
        This is stream-ordered with respect to the stream used when
        creating the `ChunkedPack` and syncs that stream before returning.

        Raises
        ------
        RuntimeError
            If the copy to host fails or an incorrectly sized buffer
            is provided.
        """

def pack(input: Table, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> PackedColumns:
    """Deep-copy a table into a serialized contiguous memory format.

    Later use `unpack` or `unpack_from_memoryviews` to unpack the serialized
    data back into the table.

    Parameters
    ----------
    input : Table
        Table to pack.
    stream : Stream | None
        CUDA stream on which to perform the operation.

    Returns
    -------
    PackedColumns
        The packed columns.

    Examples
    --------
    >>> packed = pylibcudf.contiguous_split.pack(...)
    >>> # Either unpack the whole `PackedColumns` at once.
    >>> pylibcudf.contiguous_split.unpack(packed)
    >>> # Or unpack the two serialized buffers in `PackedColumns`.
    >>> metadata, gpu_data = packed.release()
    >>> pylibcudf.contiguous_split.unpack_from_memoryviews(metadata, gpu_data)

    For details, see :cpp:func:`pack`.
    """
def unpack(input: PackedColumns, stream: CudaStreamLike | None=None) -> Table:
    """Deserialize the result of `pack`.

    Copies the result of a serialized table into a table.

    For details, see :cpp:func:`unpack`.

    Parameters
    ----------
    input : PackedColumns
        The packed columns to unpack.
    stream : Stream | None
        CUDA stream on which to perform the operation.

    Returns
    -------
    Table
        Copy of the packed columns.
    """
def unpack_from_memoryviews(metadata: memoryview, gpu_data: object, stream: CudaStreamLike | None=None) -> Table:
    """Deserialize the result of `pack`.

    Copies the result of a serialized table into a table.

    For details, see :cpp:func:`unpack`.

    Parameters
    ----------
    metadata : memoryview
        The packed metadata to unpack.
    gpu_data : Span-like object
        The packed gpu_data to unpack.
    stream : Stream | None
        CUDA stream on which to perform the operation.

    Returns
    -------
    Table
        Copy of the packed columns.
    """
