# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/expressions.pyx

import ast
import functools
from typing import TypeAlias

from pylibcudf.libcudf.expressions import ast_operator
from pylibcudf.libcudf.expressions import ast_operator as ASTOperator
from pylibcudf.libcudf.expressions import table_reference
from pylibcudf.libcudf.expressions import table_reference as TableReference
from pylibcudf.libcudf.types import size_type

from .scalar import Scalar

expression_ptr: TypeAlias = ...
__all__ = ['ASTOperator', 'ColumnNameReference', 'ColumnReference', 'Expression', 'Literal', 'Operation', 'TableReference', 'to_expression']
_python_cudf_operator_map = {ast.Add: ASTOperator.ADD, ast.Sub: ASTOperator.SUB, ast.Mult: ASTOperator.MUL, ast.Div: ASTOperator.DIV, ast.FloorDiv: ASTOperator.FLOOR_DIV, ast.Mod: ASTOperator.PYMOD, ast.Pow: ASTOperator.POW, ast.Eq: ASTOperator.EQUAL, ast.NotEq: ASTOperator.NOT_EQUAL, ast.Lt: ASTOperator.LESS, ast.Gt: ASTOperator.GREATER, ast.LtE: ASTOperator.LESS_EQUAL, ast.GtE: ASTOperator.GREATER_EQUAL, ast.BitXor: ASTOperator.BITWISE_XOR, ast.BitAnd: ASTOperator.BITWISE_AND, ast.BitOr: ASTOperator.BITWISE_OR, ast.And: ASTOperator.LOGICAL_AND, ast.Or: ASTOperator.LOGICAL_OR, ast.Invert: ASTOperator.BIT_INVERT, ast.Not: ASTOperator.NOT}
_python_cudf_function_map = {'isnull': ASTOperator.IS_NULL, 'isna': ASTOperator.IS_NULL, 'sin': ASTOperator.SIN, 'cos': ASTOperator.COS, 'tan': ASTOperator.TAN, 'arcsin': ASTOperator.ARCSIN, 'arccos': ASTOperator.ARCCOS, 'arctan': ASTOperator.ARCTAN, 'sinh': ASTOperator.SINH, 'cosh': ASTOperator.COSH, 'tanh': ASTOperator.TANH, 'arcsinh': ASTOperator.ARCSINH, 'arccosh': ASTOperator.ARCCOSH, 'arctanh': ASTOperator.ARCTANH, 'exp': ASTOperator.EXP, 'log': ASTOperator.LOG, 'sqrt': ASTOperator.SQRT, 'abs': ASTOperator.ABS, 'ceil': ASTOperator.CEIL, 'floor': ASTOperator.FLOOR}

class Expression:
    """
    The base class for all expression types.
    This class cannot be instantiated directly, please
    instantiate one of its child classes instead.

    For details, see :cpp:class:`cudf::ast::expression`.
    """
    __hash__ = None

class Literal(Expression):
    """
    A literal value used in an abstract syntax tree.

    For details, see :cpp:class:`cudf::ast::literal`.

    Parameters
    ----------
    value : Scalar
        The Scalar value of the Literal.
        Must be either numeric, string, or a timestamp/duration scalar.
    """
    def __init__(self, value: Scalar): ...

class ColumnReference(Expression):
    """
    An expression referring to data from a column in a table.

    For details, see :cpp:class:`cudf::ast::column_reference`.

    Parameters
    ----------
    index : size_type
        The index of this column in the table
        (provided when the expression is evaluated).
    table_source : TableReference, default TableReferenece.LEFT
        Which table to use in cases with two tables (e.g. joins)
    """
    def __init__(self, index: size_type, table_source: table_reference=table_reference.LEFT): ...

class Operation(Expression):
    """
    An operation expression holds an operator and zero or more operands.

    For details, see :cpp:class:`cudf::ast::operation`.

    Parameters
    ----------
    op : Operator
    left : Expression
        Left input expression (left operand)
    right: Expression, default None
        Right input expression (right operand).
        You should only pass this if the input expression is a binary operation.
    """
    def __init__(self, op: ast_operator, left: Expression, right: Expression | None=None): ...

class ColumnNameReference(Expression):
    """
    An expression referring to data from a column in a table.

    For details, see :cpp:class:`cudf::ast::column_name_reference`.

    Parameters
    ----------
    column_name : str
        Name of this column in the table metadata
        (provided when the expression is evaluated).
    """
    def __init__(self, name: str): ...

class ExpressionTransformer:
    """A NodeVisitor specialized for constructing a libcudf expression tree.

    This visitor is designed to handle AST nodes that have libcudf equivalents.
    It constructs column references from names and literals from constants,
    then builds up operations. The resulting expression is returned by the
    `visit` method

    Parameters
    ----------
    column_mapping : dict[str, ColumnNameReference | ColumnReference]
        Mapping from names to column references or column name references.
        The former can be used for `compute_column` the latter in IO filters.
    """
    def __init__(self, column_mapping: dict): ...
    def generic_visit(self, node): ...
    def visit_Module(self, node): ...
    def visit_Expr(self, node): ...
    def visit_Name(self, node): ...
    def visit_Constant(self, node): ...
    def visit_UnaryOp(self, node): ...
    def visit_BinOp(self, node): ...
    def visit_BoolOp(self, node): ...
    def visit_Compare(self, node): ...
    def visit_Call(self, node): ...

@functools.lru_cache(256)
def to_expression(expr: str, column_names: tuple[str, ...]):
    """
    Create an expression for `pylibcudf.transform.compute_column`.

    Parameters
    ----------
    expr : str
        The expression to evaluate. In (restricted) Python syntax.
    column_names : tuple[str]
        Ordered tuple of names. When calling `compute_column` on the resulting
        expression, the provided table must have columns in the same order
        as given here.

    Notes
    -----
    This function keeps a small cache of recently used expressions.

    Returns
    -------
    Expression
        Expression for the given expr and col_names
    """
