# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/gpumemoryview.pyx

import functools
from collections.abc import Mapping
from typing import Any

import cython

__all__ = ['gpumemoryview']

class gpumemoryview:
    """Minimal representation of a memory buffer.

    This class aspires to be a GPU equivalent of :py:class:`memoryview` for any
    objects exposing a `CUDA Array Interface
    <https://numba.readthedocs.io/en/stable/cuda/cuda_array_interface.html>`__.
    It will be expanded to encompass more memoryview functionality over time.
    """
    __hash__ = None
    ptr: int
    obj: object
    cai: dict
    nbytes: int

    def __init__(self, obj: object): ...
    @property
    def __cuda_array_interface__(self) -> Mapping[str, Any]: ...
    @property
    def size(self) -> int:
        """
        Size of the memory region in bytes (Span protocol).

        This is an alias for nbytes to satisfy the Span protocol.
        """
    def __len__(self) -> int: ...
    @cython.annotation_typing(False)
    def byte_slice(self, s: slice) -> gpumemoryview:
        """Return a byte-range sub-view of this buffer.

        Parameters
        ----------
        s : slice
            Byte-based slice.

        Returns
        -------
        gpumemoryview
            A ``|u1`` view of the requested byte range. The returned view
            holds a reference to the parent buffer, keeping it alive.

        Raises
        ------
        TypeError
            If ``s`` is not a slice.
        ValueError
            If the slice step is not 1. Out-of-range or reversed ranges
            return a zero-length view rather than raising.
        """

@functools.cache
def _datatype_from_dtype_desc(desc): ...
