# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/groupby.pyx

from pylibcudf.replace import ReplacePolicy
from pylibcudf.scalar import Scalar
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

from .aggregation import Aggregation
from .column import Column
from .table import Table
from .types import null_policy, sorted

__all__ = ['GroupBy', 'GroupByRequest']

class GroupByRequest:
    """A request for a groupby aggregation or scan.

    This class is functionally polymorphic and can represent either an
    aggregation or a scan depending on the algorithm it is used with. For
    details on the libcudf types it converts to, see
    :cpp:class:`cudf::groupby::aggregation_request` and
    :cpp:class:`cudf::groupby::scan_request`.

    Parameters
    ----------
    values : Column
        The column to aggregate.
    aggregations : List[Aggregation]
        The list of aggregations to perform.
    """
    __hash__ = None

    def __init__(self, values: Column, aggregations: list[Aggregation]): ...

class GroupBy:
    """Group values by keys and compute various aggregate quantities.

    For details, see :cpp:class:`cudf::groupby::groupby`.

    Parameters
    ----------
    keys : Table
        The columns to group by.
    null_handling : null_policy, optional
        Whether or not to include null rows in `keys`.
        Default is ``null_policy.EXCLUDE``.
    keys_are_sorted : sorted, optional
        Whether the keys are already sorted. Default is ``sorted.NO``.
    column_order : list[order]
        Indicates the order of each column. Default is ``order.ASCENDING``.
        Ignored if `keys_are_sorted` is ``sorted.NO``.
    null_precedence : list[null_order]
        Indicates the ordering of null values in each column.
        Default is ``null_order.AFTER``. Ignored if `keys_are_sorted` is ``sorted.NO``.
    """
    __hash__ = None

    def __init__(self, keys: Table, null_handling: null_policy=null_policy.EXCLUDE, keys_are_sorted: sorted=sorted.NO, column_order: list | None=None, null_precedence: list | None=None): ...
    def aggregate(self, requests: list[GroupByRequest], stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> tuple:
        """Compute aggregations on columns.

        For details, see :cpp:func:`cudf::groupby::groupby::aggregate`.

        Parameters
        ----------
        requests : List[GroupByRequest]
            The list of `~.pylibcudf.groupby.GroupByRequest` , each
            representing a set of aggregations to perform on a given column of values.
        stream : Stream | None
            CUDA stream on which to perform the operation.

        Returns
        -------
        Tuple[Table, List[Table, ...]]
            A tuple whose first element is the unique keys and whose second
            element is a table of aggregation results. One table is returned
            for each aggregation request, with the columns corresponding to the
            sequence of aggregations in the request.
        """
    def scan(self, requests: list[GroupByRequest], stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> tuple:
        """Compute scans on columns.

        For details, see :cpp:func:`cudf::groupby::groupby::scan`.

        Parameters
        ----------
        requests : List[GroupByRequest]
            The list of `~.pylibcudf.groupby.GroupByRequest` , each
            representing a set of aggregations to perform on a given column of values.
        stream : Stream | None
            CUDA stream on which to perform the operation.

        Returns
        -------
        Tuple[Table, List[Table, ...]]
            A tuple whose first element is the unique keys and whose second
            element is a table of aggregation results. One table is returned
            for each aggregation request, with the columns corresponding to the
            sequence of aggregations in the request.
        """
    def shift(self, values: Table, offset: list[int], fill_values: list[Scalar], stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> tuple:
        """Compute shifts on columns.

        For details, see :cpp:func:`cudf::groupby::groupby::shift`.

        Parameters
        ----------
        values : Table
            The columns to shift.
        offset : List[int]
            The offsets to shift by.
        fill_values : List[Scalar]
            The values to use to fill in missing values.
        stream : Stream | None
            CUDA stream on which to perform the operation.

        Returns
        -------
        Tuple[Table, Table]
            A tuple whose first element is the group's keys and whose second
            element is a table of shifted values.
        """
    def replace_nulls(self, value: Table, replace_policies: list[ReplacePolicy], stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> tuple:
        """Replace nulls in columns.

        For details, see :cpp:func:`cudf::groupby::groupby::replace_nulls`.

        Parameters
        ----------
        values : Table
            The columns to replace nulls in.
        replace_policies : List[replace_policy]
            The policies to use to replace nulls.
        stream : Stream | None
            CUDA stream on which to perform the operation.

        Returns
        -------
        Tuple[Table, Table]
            A tuple whose first element is the group's keys and whose second
            element is a table of values with nulls replaced.
        """
    def get_groups(self, values: Table | None=None, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> tuple:
        """Get the grouped keys and values labels for each row.

        For details, see :cpp:func:`cudf::groupby::groupby::get_groups`.

        Parameters
        ----------
        values : Table, optional
            The columns to get group labels for. If not specified,
            `None` is returned for the group values.
        stream : Stream | None
            CUDA stream on which to perform the operation.

        Returns
        -------
        Tuple[List[int], Table, Table]
            A tuple of tables containing three items:
                - A list of integer offsets into the group keys/values
                - A table of group keys
                - A table of group values or None
        """
