# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/groupby.pyx

from pylibcudf.replace import ReplacePolicy
from pylibcudf.scalar import Scalar
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

from .aggregation import Aggregation
from .column import Column
from .table import Table
from .types import NullOrder, NullPolicy, Order, Sorted, null_policy, sorted

__all__ = ['GroupBy', 'GroupByRequest']

class GroupByRequest:
    __hash__ = None

    def __init__(self, values: Column, aggregations: list[Aggregation]): ...

class GroupBy:
    __hash__ = None

    def __init__(self, keys: Table, null_handling: NullPolicy=null_policy.EXCLUDE, keys_are_sorted: Sorted=sorted.NO, column_order: list[Order] | None=None, null_precedence: list[NullOrder] | None=None): ...
    def aggregate(self, requests: list[GroupByRequest], stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> tuple: ...
    def scan(self, requests: list[GroupByRequest], stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> tuple: ...
    def shift(self, values: Table, offset: list[int], fill_values: list[Scalar], stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> tuple: ...
    def replace_nulls(self, value: Table, replace_policies: list[ReplacePolicy], stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> tuple: ...
    def get_groups(self, values: Table | None=None, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> tuple: ...
