# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/hashing.pyx

from pylibcudf.libcudf.hash import DEFAULT_HASH_SEED
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

from .column import Column
from .table import Table

__all__ = ['LIBCUDF_DEFAULT_HASH_SEED', 'md5', 'murmurhash3_x64_128', 'murmurhash3_x86_32', 'sha1', 'sha224', 'sha256', 'sha384', 'sha512', 'xxhash_32', 'xxhash_64']
LIBCUDF_DEFAULT_HASH_SEED = DEFAULT_HASH_SEED

def murmurhash3_x86_32(input: Table, seed: int=DEFAULT_HASH_SEED, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """Computes the MurmurHash3 32-bit hash value of each row in the given table.

    For details, see :cpp:func:`murmurhash3_x86_32`.

    Parameters
    ----------
    input : Table
        The table of columns to hash
    seed : uint32_t
        Optional seed value to use for the hash function

    Returns
    -------
    pylibcudf.Column
        A column where each row is the hash of a row from the input
    """
def murmurhash3_x64_128(input: Table, seed: int=DEFAULT_HASH_SEED, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Table:
    """Computes the MurmurHash3 64-bit hash value of each row in the given table.

    For details, see :cpp:func:`murmurhash3_x64_128`.

    Parameters
    ----------
    input : Table
        The table of columns to hash
    seed : uint64_t
        Optional seed value to use for the hash function

    Returns
    -------
    pylibcudf.Table
        A table of two UINT64 columns
    """
def xxhash_32(input: Table, seed: int=DEFAULT_HASH_SEED, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """Computes the xxHash 32-bit hash value of each row in the given table.

    For details, see :cpp:func:`xxhash_32`.

    Parameters
    ----------
    input : Table
        The table of columns to hash
    seed : uint32_t
        Optional seed value to use for the hash function

    Returns
    -------
    pylibcudf.Column
        A column where each row is the hash of a row from the input
    """
def xxhash_64(input: Table, seed: int=DEFAULT_HASH_SEED, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """Computes the xxHash 64-bit hash value of each row in the given table.

    For details, see :cpp:func:`xxhash_64`.

    Parameters
    ----------
    input : Table
        The table of columns to hash
    seed : uint64_t
        Optional seed value to use for the hash function

    Returns
    -------
    pylibcudf.Column
        A column where each row is the hash of a row from the input
    """
def md5(input: Table, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """Computes the MD5 hash value of each row in the given table.

    For details, see :cpp:func:`md5`.

    Parameters
    ----------
    input : Table
        The table of columns to hash
    stream : Stream | None
        CUDA stream on which to perform the operation.

    Returns
    -------
    pylibcudf.Column
        A column where each row is the md5 hash of a row from the input

    """
def sha1(input: Table, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """Computes the SHA-1 hash value of each row in the given table.

    For details, see :cpp:func:`sha1`.

    Parameters
    ----------
    input : Table
        The table of columns to hash
    stream : Stream | None
        CUDA stream on which to perform the operation.

    Returns
    -------
    pylibcudf.Column
        A column where each row is the hash of a row from the input
    """
def sha224(input: Table, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """Computes the SHA-224 hash value of each row in the given table.

    For details, see :cpp:func:`sha224`.

    Parameters
    ----------
    input : Table
        The table of columns to hash
    stream : Stream | None
        CUDA stream on which to perform the operation.

    Returns
    -------
    pylibcudf.Column
        A column where each row is the hash of a row from the input
    """
def sha256(input: Table, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """Computes the SHA-256 hash value of each row in the given table.

    For details, see :cpp:func:`sha256`.

    Parameters
    ----------
    input : Table
        The table of columns to hash
    stream : Stream | None
        CUDA stream on which to perform the operation.

    Returns
    -------
    pylibcudf.Column
        A column where each row is the hash of a row from the input
    """
def sha384(input: Table, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """Computes the SHA-384 hash value of each row in the given table.

    For details, see :cpp:func:`sha384`.

    Parameters
    ----------
    input : Table
        The table of columns to hash
    stream : Stream | None
        CUDA stream on which to perform the operation.

    Returns
    -------
    pylibcudf.Column
        A column where each row is the hash of a row from the input
    """
def sha512(input: Table, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """Computes the SHA-512 hash value of each row in the given table.

    For details, see :cpp:func:`sha512`.

    Parameters
    ----------
    input : Table
        The table of columns to hash
    stream : Stream | None
        CUDA stream on which to perform the operation.

    Returns
    -------
    pylibcudf.Column
        A column where each row is the hash of a row from the input
    """
