# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/join.pyx

from pylibcudf.libcudf.types import null_equality
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

from .column import Column
from .expressions import Expression
from .table import Table

__all__ = ['conditional_full_join', 'conditional_inner_join', 'conditional_left_anti_join', 'conditional_left_join', 'conditional_left_semi_join', 'cross_join', 'FilteredJoin', 'full_join', 'inner_join', 'left_anti_join', 'left_join', 'left_semi_join', 'mixed_full_join', 'mixed_inner_join', 'mixed_left_anti_join', 'mixed_left_join', 'mixed_left_semi_join']

class FilteredJoin:
    """
    Filtered hash join that builds a hash table from the right (filter) table
    on creation and probes results in subsequent join member functions.

    The right table is used as the filter applied to multiple left tables in
    subsequent ``semi_join`` or ``anti_join`` calls. For use cases where the
    left table should be reused with multiple right tables, use ``MarkJoin``
    instead.

    For details, see :cpp:class:`cudf::filtered_join`.
    """
    def __init__(self, right: Table, compare_nulls: null_equality=null_equality.EQUAL, load_factor: float=0.5, stream: CudaStreamLike | None=None):
        """
        Construct a filtered hash join object for subsequent probe calls.

        Parameters
        ----------
        right : Table
            The right (filter) table used to build the hash table.
        compare_nulls : NullEquality
            Controls whether null join-key values should match or not.
        load_factor : float, optional
            The desired ratio of filled slots to total slots in the hash table,
            must be in range (0,1]. Defaults to 0.5.
        stream : Stream, optional
            CUDA stream used for device memory operations and kernel launches.
        """
    def semi_join(self, left: Table, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None):
        """
        Returns a column of row indices corresponding to a semi-join
        between the right (filter) table and left table.

        For details, see :cpp:func:`cudf::filtered_join::semi_join`.

        Parameters
        ----------
        left : Table
            The left table.
        stream : Stream, optional
            CUDA stream used for device memory operations and kernel launches.
        mr : DeviceMemoryResource, optional
            Device memory resource used to allocate the returned column's device memory.

        Returns
        -------
        Column
            A column containing the row indices from the left table after the join.
        """
    def anti_join(self, left: Table, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None):
        """
        Returns a column of row indices corresponding to an anti-join
        between the right (filter) table and left table.

        For details, see :cpp:func:`cudf::filtered_join::anti_join`.

        Parameters
        ----------
        left : Table
            The left table.
        stream : Stream, optional
            CUDA stream used for device memory operations and kernel launches.
        mr : DeviceMemoryResource, optional
            Device memory resource used to allocate the returned column's device memory.

        Returns
        -------
        Column
            A column containing the row indices from the left table after the join.
        """

def inner_join(left_keys: Table, right_keys: Table, nulls_equal: null_equality, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> tuple:
    """Perform an inner join between two tables.

    For details, see :cpp:func:`inner_join`.

    Parameters
    ----------
    left_keys : Table
        The left table to join.
    right_keys : Table
        The right table to join.
    nulls_equal : NullEquality
        Should nulls compare equal?

    Returns
    -------
    Tuple[Column, Column]
        A tuple containing the row indices from the left and right tables after the
        join.
    """
def left_join(left_keys: Table, right_keys: Table, nulls_equal: null_equality, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> tuple:
    """Perform a left join between two tables.

    For details, see :cpp:func:`left_join`.

    Parameters
    ----------
    left_keys : Table
        The left table to join.
    right_keys : Table
        The right table to join.
    nulls_equal : NullEquality
        Should nulls compare equal?

    Returns
    -------
    Tuple[Column, Column]
        A tuple containing the row indices from the left and right tables after the
        join.
    """
def full_join(left_keys: Table, right_keys: Table, nulls_equal: null_equality, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> tuple:
    """Perform a full join between two tables.

    For details, see :cpp:func:`full_join`.

    Parameters
    ----------
    left_keys : Table
        The left table to join.
    right_keys : Table
        The right table to join.
    nulls_equal : NullEquality
        Should nulls compare equal?

    Returns
    -------
    Tuple[Column, Column]
        A tuple containing the row indices from the left and right tables after the
        join.
    """
def left_semi_join(left_keys: Table, right_keys: Table, nulls_equal: null_equality, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """Perform a left semi join between two tables.

    For details, see :cpp:class:`cudf::filtered_join`.

    Parameters
    ----------
    left_keys : Table
        The left table to join.
    right_keys : Table
        The right table to join.
    nulls_equal : NullEquality
        Should nulls compare equal?

    Returns
    -------
    Column
        A column containing the row indices from the left table after the join.
    """
def left_anti_join(left_keys: Table, right_keys: Table, nulls_equal: null_equality, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """Perform a left anti join between two tables.

    For details, see :cpp:class:`cudf::filtered_join`.

    Parameters
    ----------
    left_keys : Table
        The left table to join.
    right_keys : Table
        The right table to join.
    nulls_equal : NullEquality
        Should nulls compare equal?

    Returns
    -------
    Column
        A column containing the row indices from the left table after the join.
    """
def cross_join(left: Table, right: Table, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Table:
    """Perform a cross join on two tables.

    For details see :cpp:func:`cross_join`.

    Parameters
    ----------
    left : Table
        The left table to join.
    right: Table
        The right table to join.
    stream : Stream | None
        CUDA stream on which to perform the operation.
    mr : DeviceMemoryResource | None
        Device memory resource used to allocate the returned table's device memory.

    Returns
    -------
    Table
        The result of cross joining the two inputs.
    """
def conditional_inner_join(left: Table, right: Table, binary_predicate: Expression, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> tuple:
    """Perform a conditional inner join between two tables.

    For details, see :cpp:func:`conditional_inner_join`.

    Parameters
    ----------
    left : Table
        The left table to join.
    right : Table
        The right table to join.
    binary_predicate : Expression
        Condition to join on.

    Returns
    -------
    Tuple[Column, Column]
        A tuple containing the row indices from the left and right tables after the
        join.
    """
def conditional_left_join(left: Table, right: Table, binary_predicate: Expression, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> tuple:
    """Perform a conditional left join between two tables.

    For details, see :cpp:func:`conditional_left_join`.

    Parameters
    ----------
    left : Table
        The left table to join.
    right : Table
        The right table to join.
    binary_predicate : Expression
        Condition to join on.

    Returns
    -------
    Tuple[Column, Column]
        A tuple containing the row indices from the left and right tables after the
        join.
    """
def conditional_full_join(left: Table, right: Table, binary_predicate: Expression, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> tuple:
    """Perform a conditional full join between two tables.

    For details, see :cpp:func:`conditional_full_join`.

    Parameters
    ----------
    left : Table
        The left table to join.
    right : Table
        The right table to join.
    binary_predicate : Expression
        Condition to join on.

    Returns
    -------
    Tuple[Column, Column]
        A tuple containing the row indices from the left and right tables after the
        join.
    """
def conditional_left_semi_join(left: Table, right: Table, binary_predicate: Expression, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """Perform a conditional left semi join between two tables.

    For details, see :cpp:func:`conditional_left_semi_join`.

    Parameters
    ----------
    left : Table
        The left table to join.
    right : Table
        The right table to join.
    binary_predicate : Expression
        Condition to join on.

    Returns
    -------
    Column
        A column containing the row indices from the left table after the join.
    """
def conditional_left_anti_join(left: Table, right: Table, binary_predicate: Expression, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """Perform a conditional left anti join between two tables.

    For details, see :cpp:func:`conditional_left_anti_join`.

    Parameters
    ----------
    left : Table
        The left table to join.
    right : Table
        The right table to join.
    binary_predicate : Expression
        Condition to join on.

    Returns
    -------
    Column
        A column containing the row indices from the left table after the join.
    """
def mixed_inner_join(left_keys: Table, right_keys: Table, left_conditional: Table, right_conditional: Table, binary_predicate: Expression, nulls_equal: null_equality, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> tuple:
    """Perform a mixed inner join between two tables.

    For details, see :cpp:func:`mixed_inner_join`.

    Parameters
    ----------
    left_keys : Table
        The left table to use for the equality join.
    right_keys : Table
        The right table to use for the equality join.
    left_conditional : Table
        The left table to use for the conditional join.
    right_conditional : Table
        The right table to use for the conditional join.
    binary_predicate : Expression
        Condition to join on.
    nulls_equal : NullEquality
        Should nulls compare equal in the equality join?

    Returns
    -------
    Tuple[Column, Column]
        A tuple containing the row indices from the left and right tables after the
        join.
    """
def mixed_left_join(left_keys: Table, right_keys: Table, left_conditional: Table, right_conditional: Table, binary_predicate: Expression, nulls_equal: null_equality, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> tuple:
    """Perform a mixed left join between two tables.

    For details, see :cpp:func:`mixed_left_join`.

    Parameters
    ----------
    left_keys : Table
        The left table to use for the equality join.
    right_keys : Table
        The right table to use for the equality join.
    left_conditional : Table
        The left table to use for the conditional join.
    right_conditional : Table
        The right table to use for the conditional join.
    binary_predicate : Expression
        Condition to join on.
    nulls_equal : NullEquality
        Should nulls compare equal in the equality join?

    Returns
    -------
    Tuple[Column, Column]
        A tuple containing the row indices from the left and right tables after the
        join.
    """
def mixed_full_join(left_keys: Table, right_keys: Table, left_conditional: Table, right_conditional: Table, binary_predicate: Expression, nulls_equal: null_equality, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> tuple:
    """Perform a mixed full join between two tables.

    For details, see :cpp:func:`mixed_full_join`.

    Parameters
    ----------
    left_keys : Table
        The left table to use for the equality join.
    right_keys : Table
        The right table to use for the equality join.
    left_conditional : Table
        The left table to use for the conditional join.
    right_conditional : Table
        The right table to use for the conditional join.
    binary_predicate : Expression
        Condition to join on.
    nulls_equal : NullEquality
        Should nulls compare equal in the equality join?

    Returns
    -------
    Tuple[Column, Column]
        A tuple containing the row indices from the left and right tables after the
        join.
    """
def mixed_left_semi_join(left_keys: Table, right_keys: Table, left_conditional: Table, right_conditional: Table, binary_predicate: Expression, nulls_equal: null_equality, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """Perform a mixed left semi join between two tables.

    For details, see :cpp:func:`mixed_left_semi_join`.

    Parameters
    ----------
    left_keys : Table
        The left table to use for the equality join.
    right_keys : Table
        The right table to use for the equality join.
    left_conditional : Table
        The left table to use for the conditional join.
    right_conditional : Table
        The right table to use for the conditional join.
    binary_predicate : Expression
        Condition to join on.
    nulls_equal : NullEquality
        Should nulls compare equal in the equality join?

    Returns
    -------
    Column
        A column containing the row indices from the left table after the join.
    """
def mixed_left_anti_join(left_keys: Table, right_keys: Table, left_conditional: Table, right_conditional: Table, binary_predicate: Expression, nulls_equal: null_equality, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """Perform a mixed left anti join between two tables.

    For details, see :cpp:func:`mixed_left_anti_join`.

    Parameters
    ----------
    left_keys : Table
        The left table to use for the equality join.
    right_keys : Table
        The right table to use for the equality join.
    left_conditional : Table
        The left table to use for the conditional join.
    right_conditional : Table
        The right table to use for the conditional join.
    binary_predicate : Expression
        Condition to join on.
    nulls_equal : NullEquality
        Should nulls compare equal in the equality join?

    Returns
    -------
    Column
        A column containing the row indices from the left table after the join.
    """
