# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/json.pyx

from pylibcudf.column import Column
from pylibcudf.scalar import Scalar
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

__all__ = ['GetJsonObjectOptions', 'get_json_object']

class GetJsonObjectOptions:
    """Settings for `get_json_object()`"""
    __hash__ = None

    def __init__(self, *, allow_single_quotes=False, strip_quotes_from_single_strings=True, missing_fields_as_nulls=False): ...
    def get_allow_single_quotes(self):
        """
        Returns true/false depending on whether single-quotes for representing strings
        are allowed.

        Returns
        -------
        bool
            true if single-quotes are allowed, false otherwise.
        """
    def get_strip_quotes_from_single_strings(self):
        """
        Returns true/false depending on whether individually returned string values have
        their quotes stripped.

        Returns
        -------
        bool
            true if individually returned string values have their quotes stripped.
        """
    def get_missing_fields_as_nulls(self):
        """
        Whether a field not contained by an object is to be interpreted as null.

        Returns
        -------
        bool
            true if missing fields are interpreted as null.
        """
    def set_allow_single_quotes(self, val: bool):
        """
        Set whether single-quotes for strings are allowed.

        Parameters
        ----------
        val : bool
            Whether to allow single quotes

        Returns
        -------
        None
        """
    def set_strip_quotes_from_single_strings(self, val: bool):
        """
        Set whether individually returned string values have their quotes stripped.

        Parameters
        ----------
        val : bool
            Whether to strip quotes from single strings.

        Returns
        -------
        None
        """
    def set_missing_fields_as_nulls(self, val: bool):
        """
        Set whether missing fields are interpreted as null.

        Parameters
        ----------
        val : bool
            Whether to treat missing fields as nulls.

        Returns
        -------
        None
        """

def get_json_object(col: Column, json_path: Scalar, options: GetJsonObjectOptions | None=None, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """
    Apply a JSONPath string to all rows in an input strings column.

    For details, see :cpp:func:`get_json_object`

    Parameters
    ----------
    col : Column
        The input strings column. Each row must contain a valid json string.

    json_path : Scalar
        The JSONPath string to be applied to each row.

    options : GetJsonObjectOptions
        Options for controlling the behavior of the function.

    stream : Stream | None
        CUDA stream on which to perform the operation.

    Returns
    -------
    Column
        New strings column containing the retrieved json object strings.
    """
