# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/lists.pyx

from pylibcudf.libcudf.copying import out_of_bounds_policy
from pylibcudf.libcudf.lists.combine import concatenate_null_policy
from pylibcudf.libcudf.lists.combine import \
    concatenate_null_policy as ConcatenateNullPolicy
from pylibcudf.libcudf.lists.contains import duplicate_find_option
from pylibcudf.libcudf.lists.contains import \
    duplicate_find_option as DuplicateFindOption
from pylibcudf.libcudf.types import (nan_equality, null_equality, null_order,
                                     order, size_type)
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

from .column import Column
from .scalar import Scalar
from .table import Table

__all__ = ['ConcatenateNullPolicy', 'DuplicateFindOption', 'apply_boolean_mask', 'apply_deletion_mask', 'concatenate_list_elements', 'concatenate_rows', 'contains', 'contains_nulls', 'count_elements', 'difference_distinct', 'distinct', 'explode_outer', 'extract_list_element', 'have_overlap', 'index_of', 'intersect_distinct', 'reverse', 'segmented_gather', 'sequences', 'sort_lists', 'union_distinct']

def explode_outer(input: Table, explode_column_idx: size_type, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Table:
    """Explode a column of lists into rows.

    All other columns will be duplicated for each element in the list.

    For details, see :cpp:func:`explode_outer`.

    Parameters
    ----------
    input : Table
        The input table
    explode_column_idx : int
        The index of the column to explode

    Returns
    -------
    Table
        A new table with the exploded column
    """
def concatenate_rows(input: Table, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """Concatenate multiple lists columns into a single lists column row-wise.

    For details, see :cpp:func:`concatenate_list_elements`.

    Parameters
    ----------
    input : Table
        The input table
    stream : Stream | None
        CUDA stream on which to perform the operation.

    Returns
    -------
    Table
        A new Column of concatenated rows
    """
def concatenate_list_elements(input: Column, null_policy: concatenate_null_policy, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """Concatenate multiple lists on the same row into a single list.

    For details, see :cpp:func:`concatenate_list_elements`.

    Parameters
    ----------
    input : Column
        The input column
    null_policy : ConcatenateNullPolicy
        How to treat null list elements.

    Returns
    -------
    Column
        A new Column of concatenated list elements
    """
def contains(input: Column, search_key: Column | Scalar, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """Create a column of bool values indicating whether
    the search_key is contained in the input.

    ``search_key`` may be a
    :py:class:`~pylibcudf.column.Column` or a
    :py:class:`~pylibcudf.scalar.Scalar`.

    For details, see :cpp:func:`contains`.

    Parameters
    ----------
    input : Column
        The input column.
    search_key : Union[Column, Scalar]
        The search key.
    stream : Stream | None
        CUDA stream on which to perform the operation.

    Returns
    -------
    Column
        A new Column of bools indicating if the search_key was
        found in the list column.
    """
def contains_nulls(input: Column, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """Create a column of bool values indicating whether
    each row in the lists column contains a null value.

    For details, see :cpp:func:`contains_nulls`.

    Parameters
    ----------
    input : Column
        The input column.
    stream : Stream | None
        CUDA stream on which to perform the operation.

    Returns
    -------
    Column
        A new Column of bools indicating if the list column
        contains a null value.
    """
def index_of(input: Column, search_key: Column | Scalar, find_option: duplicate_find_option, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """Create a column of index values indicating the position of a search
    key row within the corresponding list row in the lists column.

    ``search_key`` may be a
    :py:class:`~pylibcudf.column.Column` or a
    :py:class:`~pylibcudf.scalar.Scalar`.

    For details, see :cpp:func:`index_of`.

    Parameters
    ----------
    input : Column
        The input column.
    search_key : Union[Column, Scalar]
        The search key.
    find_option : DuplicateFindOption
        Which match to return if there are duplicates.

    Returns
    -------
    Column
        A new Column of index values that indicate where in the
        list column tthe search_key was found. An index value
        of -1 indicates that the search_key was not found.
    """
def reverse(input: Column, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """Reverse the element order within each list of the input column.

    For details, see :cpp:func:`reverse`.

    Parameters
    ----------
    input : Column
        The input column.
    stream : Stream | None
        CUDA stream on which to perform the operation.

    Returns
    -------
    Column
        A new Column with reversed lists.
    """
def segmented_gather(input: Column, gather_map_list: Column, bounds_policy: out_of_bounds_policy=out_of_bounds_policy.DONT_CHECK, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """Create a column with elements gathered based on the indices in gather_map_list

    For details, see :cpp:func:`segmented_gather`.

    Parameters
    ----------
    input : Column
        The input column.
    gather_map_list : Column
        The indices of the lists column to gather.
    bounds_policy : OutOfBoundsPolicy
        Can be ``DONT_CHECK`` or ``NULLIFY``. Selects whether or not to nullify
        the output list row's element, when the gather index falls outside the range
        ``[-n, n)``, where ``n`` is the number of elements in list row corresponding
        to the gather-map row.

        When ``bounds_policy`` is ``DONT_CHECK``, it's the caller's responsibility to
        ensure that the indices in ``gather_map_list`` are in-bounds for the lists in
        ``input`` before calling this function. The behavior with out-of-bounds indices
        and ``DONT_CHECK`` is undefined and maybe produce invalid results or crash.

    Returns
    -------
    Column
        A new Column with elements in list of rows
        gathered based on gather_map_list
    """
def extract_list_element(input: Column, index: Column | size_type, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """Create a column of extracted list elements.

    For details, see :cpp:func:`extract_list_element`.

    Parameters
    ----------
    input : Column
        The input column.
    index : Union[Column, size_type]
        The selection index or indices.

    Returns
    -------
    Column
        A new Column with elements extracted.
    """
def count_elements(input: Column, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """Count the number of rows in each
    list element in the given lists column.
    For details, see :cpp:func:`count_elements`.

    For details, see :cpp:func:`count_elements`.

    Parameters
    ----------
    input : Column
        The input column
    stream : Stream | None
        CUDA stream on which to perform the operation.

    Returns
    -------
    Column
        A new Column of the lengths of each list element
    """
def sequences(starts: Column, sizes: Column, steps: Column | None=None, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """Create a lists column in which each row contains a sequence of
    values specified by a tuple of (start, step, size) parameters.

    For details, see :cpp:func:`sequences`.

    Parameters
    ----------
    starts : Column
        First values in the result sequences.
    sizes : Column
        Numbers of values in the result sequences.
    steps : Optional[Column]
        Increment values for the result sequences.

    Returns
    -------
    Column
        The result column containing generated sequences.
    """
def sort_lists(input: Column, sort_order: order, na_position: null_order, stable: bool=False, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """Sort the elements within a list in each row of a list column.

    For details, see :cpp:func:`sort_lists`.

    Parameters
    ----------
    input : Column
        The input column.
    ascending : Order
        Sort order in the list.
    na_position : NullOrder
        If na_position equals NullOrder.FIRST, then the null values in the output
        column are placed first. Otherwise, they are be placed after.
    stable: bool
        If true :cpp:func:`stable_sort_lists` is used, Otherwise,
        :cpp:func:`sort_lists` is used.

    Returns
    -------
    Column
        A new Column with elements in each list sorted.
    """
def difference_distinct(lhs: Column, rhs: Column, nulls_equal: null_equality=null_equality.EQUAL, nans_equal: nan_equality=nan_equality.ALL_EQUAL, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """Create a column of index values indicating the position of a search
    key row within the corresponding list row in the lists column.

    For details, see :cpp:func:`difference_distinct`.

    Parameters
    ----------
    lhs : Column
        The input lists column of elements that may be included.
    rhs : Column
        The input lists column of elements to exclude.
    nulls_equal : NullEquality, default EQUAL
        Are nulls considered equal.
    nans_equal : NanEquality, default ALL_EQUAL
        Are nans considered equal.

    Returns
    -------
    Column
        A lists column containing the difference results.
    """
def have_overlap(lhs: Column, rhs: Column, nulls_equal: null_equality=null_equality.EQUAL, nans_equal: nan_equality=nan_equality.ALL_EQUAL, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """Check if lists at each row of the given lists columns overlap.

    For details, see :cpp:func:`have_overlap`.

    Parameters
    ----------
    lhs : Column
        The input lists column for one side.
    rhs : Column
        The input lists column for the other side.
    nulls_equal : NullEquality, default EQUAL
        Are nulls considered equal.
    nans_equal : NanEquality, default ALL_EQUAL
        Are nans considered equal.

    Returns
    -------
    Column
        A column containing the check results.
    """
def intersect_distinct(lhs: Column, rhs: Column, nulls_equal: null_equality=null_equality.EQUAL, nans_equal: nan_equality=nan_equality.ALL_EQUAL, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """Create a lists column of distinct elements common to two input lists columns.

    For details, see :cpp:func:`intersect_distinct`.

    Parameters
    ----------
    lhs : Column
        The input lists column of elements that may be included.
    rhs : Column
        The input lists column of elements to exclude.
    nulls_equal : NullEquality, default EQUAL
        Are nulls considered equal.
    nans_equal : NanEquality, default ALL_EQUAL
        Are nans considered equal.

    Returns
    -------
    Column
        A lists column containing the intersection results.
    """
def union_distinct(lhs: Column, rhs: Column, nulls_equal: null_equality=null_equality.EQUAL, nans_equal: nan_equality=nan_equality.ALL_EQUAL, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """Create a lists column of distinct elements found in
    either of two input lists columns.

    For details, see :cpp:func:`union_distinct`.

    Parameters
    ----------
    lhs : Column
        The input lists column of elements that may be included.
    rhs : Column
        The input lists column of elements to exclude.
    nulls_equal : NullEquality, default EQUAL
        Are nulls considered equal.
    nans_equal : NanEquality, default ALL_EQUAL
        Are nans considered equal.

    Returns
    -------
    Column
        A lists column containing the union results.
    """
def apply_boolean_mask(input: Column, boolean_mask: Column, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """Filters elements in each row of the input lists column using a boolean mask

    For details, see :cpp:func:`apply_boolean_mask`.

    Parameters
    ----------
    input : Column
        The input column.
    boolean_mask : Column
        The boolean mask.
    stream : Stream | None
        CUDA stream on which to perform the operation.

    Returns
    -------
    Column
        A Column of filtered elements based upon the boolean mask.
    """
def apply_deletion_mask(input: Column, deletion_mask: Column, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """Filters elements in each row of the input lists column using a deletion mask.

    For details, see :cpp:func:`apply_deletion_mask`.

    Parameters
    ----------
    input : Column
        The input lists column.
    deletion_mask : Column
        A lists-of-bools column used as a deletion mask.

    Returns
    -------
    Column
        Lists column with elements removed where deletion_mask is true.
    """
def distinct(input: Column, nulls_equal: null_equality, nans_equal: nan_equality, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """Create a new list column without duplicate elements in each list.

    For details, see :cpp:func:`distinct`.

    Parameters
    ----------
    input : Column
        The input column.
    nulls_equal : NullEquality
        Are nulls considered equal.
    nans_equal : NanEquality
        Are nans considered equal.

    Returns
    -------
    Column
        A new list column without duplicate elements in each list.
    """
