# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/null_mask.pyx

from collections.abc import Sequence

from pylibcudf.libcudf.types import mask_state, size_type
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.device_buffer import DeviceBuffer
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

from .column import Column

__all__ = ['bitmask_allocation_size_bytes', 'bitmask_and', 'bitmask_or', 'copy_bitmask', 'create_null_mask', 'null_count', 'index_of_first_set_bit']

def copy_bitmask(col: Column, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> DeviceBuffer:
    """Copies ``col``'s bitmask into a ``DeviceBuffer``.

    For details, see :cpp:func:`copy_bitmask`.

    Parameters
    ----------
    col : Column
        Column whose bitmask needs to be copied
    stream : Stream | None
        CUDA stream on which to perform the operation.
    mr : DeviceMemoryResource | None
        Device memory resource for allocations.

    Returns
    -------
    rmm.DeviceBuffer
        A ``DeviceBuffer`` containing ``col``'s bitmask, or an empty
        ``DeviceBuffer`` if ``col`` is not nullable
    """
def copy_bitmask_from_bitmask(bitmask: object, begin_bit: size_type, end_bit: size_type, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> DeviceBuffer:
    """Copies a portion of a bitmask into a ``DeviceBuffer``.

    For details, see :cpp:func:`copy_bitmask`.

    Parameters
    ----------
    bitmask : Span-like object
        Object with ptr and size attributes (e.g., gpumemoryview, Buffer, DeviceBuffer).
    begin_bit : size_type
        The starting bit index (inclusive).
    end_bit : size_type
        The ending bit index (exclusive).
    stream : Stream | None
        CUDA stream on which to perform the operation.
    mr : DeviceMemoryResource | None
        Device memory resource for allocations.

    Returns
    -------
    rmm.DeviceBuffer
        A ``DeviceBuffer`` containing ``col``'s bitmask, or an empty
        ``DeviceBuffer`` if ``col`` is not nullable
    """
def bitmask_allocation_size_bytes(number_of_bits: size_type) -> int:
    """
    Computes the required bytes necessary to represent the specified number of bits
    with a 64B padding boundary.

    For details, see :cpp:func:`bitmask_allocation_size_bytes`.

    Parameters
    ----------
    number_of_bits : size_type
        The number of bits that need to be represented

    Returns
    -------
    size_t
        The necessary number of bytes
    """
def create_null_mask(size: size_type, state: mask_state=mask_state.UNINITIALIZED, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> DeviceBuffer:
    """Creates a ``DeviceBuffer`` for use as a null value indicator bitmask of a
    ``Column``.

    For details, see :cpp:func:`create_null_mask`.

    Parameters
    ----------
    size : size_type
        The number of elements to be represented by the mask
    state : mask_state, optional
        The desired state of the mask. Can be one of { MaskState.UNALLOCATED,
        MaskState.UNINITIALIZED, MaskState.ALL_VALID, MaskState.ALL_NULL }
        (default MaskState.UNINITIALIZED)
    stream : Stream | None
        CUDA stream on which to perform the operation.
    mr : DeviceMemoryResource | None
        Device memory resource for allocations.

    Returns
    -------
    rmm.DeviceBuffer
        A ``DeviceBuffer`` for use as a null bitmask satisfying the desired size and
        state
    """
def bitmask_and(columns: Sequence[Column], stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> tuple:
    """Performs bitwise AND of the bitmasks of a list of columns.

    For details, see :cpp:func:`bitmask_and`.

    Parameters
    ----------
    columns : Sequence[Column]
        The columns
    stream : Stream | None
        CUDA stream on which to perform the operation.
    mr : DeviceMemoryResource | None
        Device memory resource for allocations.

    Returns
    -------
    tuple[DeviceBuffer, size_type]
        A tuple of the resulting mask and count of unset bits
    """
def bitmask_or(columns: Sequence[Column], stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> tuple:
    """Performs bitwise OR of the bitmasks of a list of columns.

    For details, see :cpp:func:`bitmask_or`.

    Parameters
    ----------
    columns : Sequence[Column]
        The columns
    stream : Stream | None
        CUDA stream on which to perform the operation.
    mr : DeviceMemoryResource | None
        Device memory resource for allocations.

    Returns
    -------
    tuple[DeviceBuffer, size_type]
        A tuple of the resulting mask and count of unset bits
    """
def null_count(bitmask: object, start: size_type, stop: size_type, stream: CudaStreamLike | None=None) -> size_type:
    """Given a validity bitmask, counts the number of null elements.

    For details, see :cpp:func:`null_count`.

    Parameters
    ----------
    bitmask : Span-like object
        Object with ptr and size attributes (e.g., gpumemoryview, Buffer, DeviceBuffer).
    start : int
        Index of the first bit to count (inclusive).
    stop : int
        Index of the last bit to count (exclusive).
    stream : Stream | None
        CUDA stream on which to perform the operation.

    Returns
    -------
    int
        The number of null elements in the specified range.
    """
def index_of_first_set_bit(bitmask: object, start: size_type, stop: size_type, stream: CudaStreamLike | None=None) -> size_type:
    """Given a validity bitmask, returns the index of the first valid element
    relative to ``start``.

    For details, see :cpp:func:`index_of_first_set_bit`.

    Parameters
    ----------
    bitmask : Span-like object
        Object with ptr and size attributes (e.g., gpumemoryview, Buffer, DeviceBuffer).
    start : int
        Index of the first bit to check (inclusive).
    stop : int
        Index of the last bit to check (exclusive).
    stream : Stream | None
        CUDA stream on which to perform the operation.

    Returns
    -------
    int
        The index of the first set bit relative to ``start``
    """
