# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/partitioning.pyx

from pylibcudf.libcudf import partitioning as cpp_partitioning
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

from .column import Column
from .table import Table

__all__ = ['hash_partition', 'partition', 'round_robin_partition']

def hash_partition(input: Table, keys: Table | list, num_partitions: int, hash_function: cpp_partitioning.hash_id=cpp_partitioning.hash_id.HASH_MURMUR3, seed: int=cpp_partitioning.DEFAULT_HASH_SEED, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> tuple[object, object]:
    """
    Partitions rows from the input table into multiple output tables.

    For details, see :cpp:func:`hash_partition`.

    Parameters
    ----------
    input : Table
        The table to partition
    keys : Table | list[int]
        Table providing keys to hash or list of indices of input columns to hash
    num_partitions : int
        The number of partitions to use
    hash_function : HashId
        Hashing function apply to key columns.
    seed : int
        Seed for hash function.
    stream : Stream | None
        CUDA stream on which to perform the operation.
    mr : DeviceMemoryResource | None
        Device memory resource used to allocate the returned table's device memory.

    Returns
    -------
    tuple[Table, list[int]]
        An output table and a list of `num_partitions + 1` row offsets where
        partition `i` contains rows in the range `[offsets[i], offsets[i+1])`
    """
def partition(t: Table, partition_map: Column, num_partitions: int, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> tuple[object, object]:
    """
    Partitions rows of `t` according to the mapping specified by `partition_map`.

    For details, see :cpp:func:`partition`.

    Parameters
    ----------
    t : Table
        The table to partition
    partition_map : Column
        Non-nullable column of integer values that map each row
        in `t` to it's partition.
    num_partitions : int
        The total number of partitions
    stream : Stream | None
        CUDA stream on which to perform the operation.
    mr : DeviceMemoryResource | None
        Device memory resource used to allocate the returned table's device memory.

    Returns
    -------
    tuple[Table, list[int]]
        An output table and a list of `num_partitions + 1` row offsets where
        partition `i` contains rows in the range `[offsets[i], offsets[i+1])`
    """
def round_robin_partition(input: Table, num_partitions: int, start_partition: int=0, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> tuple[object, object]:
    """
    Round-robin partition.

    For details, see :cpp:func:`round_robin_partition`.

    Parameters
    ----------
    input : Table
        The input table to be round-robin partitioned
    num_partitions : int
        Number of partitions for the table
    start_partition : int, default 0
        Index of the 1st partition
    stream : Stream | None
        CUDA stream on which to perform the operation.
    mr : DeviceMemoryResource | None
        Device memory resource used to allocate the returned table's device memory.

    Returns
    -------
    tuple[Table, list[int]]
        The partitioned table and a list of `num_partitions + 1` partition offsets
        where partition `i` contains rows in the range `[offsets[i], offsets[i+1])`.
    """
