# SPDX-FileCopyrightText: Copyright (c) 2025-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/prefetch.pyx

__all__ = ['disable', 'disable_debugging', 'enable', 'enable_debugging']

def enable():
    """Turn on prefetching of managed memory."""
def disable():
    """Turn off prefetching of managed memory."""
def enable_debugging():
    """Enable prefetch debugging."""
def disable_debugging():
    """Disable prefetch debugging."""
