# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/quantiles.pyx

from collections.abc import Iterable

from pylibcudf.libcudf.types import interpolation, sorted
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

from .column import Column
from .table import Table

__all__ = ['quantile', 'quantiles']

def quantile(input: Column, q: Iterable[float], interp: interpolation=interpolation.LINEAR, ordered_indices: Column | None=None, exact: bool=True, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """Computes quantiles with interpolation.

    Computes the specified quantiles by interpolating values between which they lie,
    using the interpolation strategy specified in interp.

    For details see :cpp:func:`quantile`.

    Parameters
    ----------
    input: Column
        The Column to calculate quantiles on.
    q: array-like that implements buffer-protocol
        The quantiles to calculate in range [0,1]
    interp: Interpolation, default Interpolation.LINEAR
        The strategy used to select between values adjacent to a specified quantile.
    ordered_indices: Column, default empty column
        The column containing the sorted order of input.

        If empty, all input values are used in existing order.
        Indices must be in range [0, input.size()), but are not required to be unique.
        Values not indexed by this column will be ignored.
    exact: bool, default True
        Returns doubles if True. Otherwise, returns same type as input
    stream : Stream | None
        CUDA stream on which to perform the operation.

    For details, see :cpp:func:`quantile`.

    Returns
    -------
    Column
        A Column containing specified quantiles, with nulls for indeterminable values
    """
def quantiles(input: Table, q: Iterable[float], interp: interpolation=interpolation.NEAREST, is_input_sorted: sorted=sorted.NO, column_order: list | None=None, null_precedence: list | None=None, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Table:
    """Computes row quantiles with interpolation.

    Computes the specified quantiles by retrieving the row corresponding to the
    specified quantiles. In the event a quantile lies in between rows, the specified
    interpolation strategy is used to pick between the rows.

    For details see :cpp:func:`quantiles`.

    Parameters
    ----------
    input: Table
        The Table to calculate row quantiles on.
    q: array-like
        The quantiles to calculate in range [0,1]
    interp: Interpolation, default Interpolation.NEAREST
        The strategy used to select between values adjacent to a specified quantile.

        Must be a non-arithmetic interpolation strategy
        (i.e. one of
        {`Interpolation.HIGHER`, `Interpolation.LOWER`, `Interpolation.NEAREST`,
        `Interpolation.NEAREST_HALF_UP`})
    is_input_sorted: Sorted, default Sorted.NO
        Whether the input table has been pre-sorted or not.
    column_order: list, default None
        A list of `Order` enums,
        indicating the desired sort order for each column.
        By default, will sort all columns so that they are in ascending order.

        Ignored if `is_input_sorted` is `Sorted.YES`
    null_precedence: list, default None
        A list of `NullOrder` enums,
        indicating how nulls should be sorted.
        By default, will sort all columns so that nulls appear before
        all other elements.

        Ignored if `is_input_sorted` is `Sorted.YES`
    stream : Stream | None
        CUDA stream on which to perform the operation.

    For details, see :cpp:func:`quantiles`.

    Returns
    -------
    Column
        A Column containing specified quantiles, with nulls for indeterminable values
    """
