# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/reduce.pyx

from pylibcudf.libcudf.reduce import scan_type
from pylibcudf.libcudf.reduce import scan_type as ScanType
from pylibcudf.libcudf.types import (nan_policy, null_equality, null_policy,
                                     size_type)
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

from .aggregation import Aggregation
from .column import Column
from .scalar import Scalar
from .table import Table
from .types import DataType

__all__ = ['ScanType', 'distinct_count', 'is_valid_reduce_aggregation', 'minmax', 'reduce', 'scan', 'unique_count']

def reduce(col: Column, agg: Aggregation, data_type: DataType, init: Scalar | None=None, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Scalar: ...
def scan(col: Column, agg: Aggregation, inclusive: scan_type, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column: ...
def minmax(col: Column, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> tuple: ...
def is_valid_reduce_aggregation(source: DataType, agg: Aggregation) -> bool: ...
def unique_count(source: Column, null_handling: null_policy, nan_handling: nan_policy, stream: CudaStreamLike | None=None) -> size_type: ...
def distinct_count(source: Column, null_handling: null_policy, nan_handling: nan_policy, stream: CudaStreamLike | None=None) -> size_type: ...
def unique_count_table(source: Table, nulls_equal: null_equality, stream: CudaStreamLike | None=None) -> size_type: ...
def distinct_count_table(source: Table, nulls_equal: null_equality, stream: CudaStreamLike | None=None) -> size_type: ...
