# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/reduce.pyx

from pylibcudf.libcudf.reduce import scan_type
from pylibcudf.libcudf.reduce import scan_type as ScanType
from pylibcudf.libcudf.types import (nan_policy, null_equality, null_policy,
                                     size_type)
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

from .aggregation import Aggregation
from .column import Column
from .scalar import Scalar
from .table import Table
from .types import DataType

__all__ = ['ScanType', 'distinct_count', 'is_valid_reduce_aggregation', 'minmax', 'reduce', 'scan', 'unique_count']

def reduce(col: Column, agg: Aggregation, data_type: DataType, init: Scalar | None=None, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Scalar:
    """Perform a reduction on a column

    For details, see ``cudf::reduce`` documentation.

    Parameters
    ----------
    col : Column
        The column to perform the reduction on.
    agg : Aggregation
        The aggregation to perform.
    data_type : DataType
        The data type of the result.
    init : Scalar | None
        The initial value for the reduction.
    stream : Stream | None
        CUDA stream on which to perform the operation.
    mr : DeviceMemoryResource | None
        Device memory resource used to allocate the returned scalar's device memory.

    Returns
    -------
    Scalar
        The result of the reduction.
    """
def scan(col: Column, agg: Aggregation, inclusive: scan_type, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """Perform a scan on a column

    For details, see ``cudf::scan`` documentation.

    Parameters
    ----------
    col : Column
        The column to perform the scan on.
    agg : Aggregation
        The aggregation to perform.
    inclusive : scan_type
        The type of scan to perform.
    stream : Stream | None
        CUDA stream on which to perform the operation.
    mr : DeviceMemoryResource | None
        Device memory resource used to allocate the returned column's device memory.

    Returns
    -------
    Column
        The result of the scan.
    """
def minmax(col: Column, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> tuple:
    """Compute the minimum and maximum of a column

    For details, see ``cudf::minmax`` documentation.

    Parameters
    ----------
    col : Column
        The column to compute the minimum and maximum of.
    stream : Stream | None
        CUDA stream on which to perform the operation.
    mr : DeviceMemoryResource | None
        Device memory resource used to allocate the returned scalars' device memory.

    Returns
    -------
    tuple
        A tuple of two Scalars, the first being the minimum and the second
        being the maximum.
    """
def is_valid_reduce_aggregation(source: DataType, agg: Aggregation) -> bool:
    """
    Return if an aggregation is supported for a given datatype.

    Parameters
    ----------
    source
        The type of the column the aggregation is being performed on.
    agg
        The aggregation.

    Returns
    -------
    True if the aggregation is supported.
    """
def unique_count(source: Column, null_handling: null_policy, nan_handling: nan_policy, stream: CudaStreamLike | None=None) -> size_type:
    """Returns the number of unique consecutive elements in the input column.

    For details, see :cpp:func:`cudf::unique_count`.

    Parameters
    ----------
    source : Column
        The input column to count the unique elements of.
    null_handling : null_policy
        Flag to include or exclude nulls from the count. If included, all
        nulls compare equal.
    nan_handling : nan_policy
        Whether to treat NaNs as null, or valid elements. If valid all NaNs
        compare equal.

    Returns
    -------
    size_type
        The number of unique consecutive elements in the input column.

    Notes
    -----
    If the input column is sorted, then unique_count can produce the
    same result as distinct_count, but faster.
    """
def distinct_count(source: Column, null_handling: null_policy, nan_handling: nan_policy, stream: CudaStreamLike | None=None) -> size_type:
    """Returns the number of distinct elements in the input column.

    For details, see :cpp:func:`cudf::distinct_count`.

    Parameters
    ----------
    source : Column
        The input column to count the unique elements of.
    null_handling : null_policy
        Flag to include or exclude nulls from the count. If included, all
        nulls compare equal.
    nan_handling : nan_policy
        Whether to treat NaNs as null, or valid elements. If valid all NaNs
        compare equal.

    Returns
    -------
    size_type
        The number of distinct elements in the input column.
    """
def unique_count_table(source: Table, nulls_equal: null_equality, stream: CudaStreamLike | None=None) -> size_type:
    """Returns the number of unique consecutive rows in the input table.

    For details, see :cpp:func:`cudf::unique_count`.

    Parameters
    ----------
    source : Table
        The input table to count the unique elements of.
    nulls_equal : null_equality
        Whether nulls should compare equal.

    Returns
    -------
    size_type
        The number of unique consecutive rows.

    Notes
    -----
    NaNs compare equal in this comparison.
    """
def distinct_count_table(source: Table, nulls_equal: null_equality, stream: CudaStreamLike | None=None) -> size_type:
    """Returns the number of distinct rows in the input table.

    For details, see :cpp:func:`cudf::distinct_count`.

    Parameters
    ----------
    source : Table
        The input table to count the unique rows of.
    nulls_equal : null_equality
        Whether nulls should compare equal.

    Returns
    -------
    size_type
        The number of distinct rows.

    Notes
    -----
    NaNs compare equal in this comparison.
    """
