# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/round.pyx

from pylibcudf.libcudf.round import rounding_method
from pylibcudf.libcudf.round import rounding_method as RoundingMethod
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

from .column import Column

__all__ = ['RoundingMethod', 'round']

def round(source: Column, decimal_places: int=0, round_method: rounding_method=rounding_method.HALF_UP, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """Rounds all the values in a column to the specified number of decimal places.

    .. deprecated:: release 26.04
        round is deprecated for float type.
        Use ``round_decimal`` for decimal and integer types.

    For details, see :cpp:func:`round`.

    Parameters
    ----------
    source : Column
        The Column for which to round values.
    decimal_places: int32_t, optional
        The number of decimal places to round to (default 0)
    round_method: rounding_method, optional
        The method by which to round each value.
        Can be one of { RoundingMethod.HALF_UP, RoundingMethod.HALF_EVEN }
        (default rounding_method.HALF_UP)
    stream : Stream | None
        CUDA stream on which to perform the operation.
    mr : DeviceMemoryResource | None
        Device memory resource used to allocate the returned column's device memory.

    Returns
    -------
    pylibcudf.Column
        A Column with values rounded
    """
def round_decimal(source: Column, decimal_places: int=0, round_method: rounding_method=rounding_method.HALF_UP, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """Rounds all the values in a column to the specified number of decimal places.
    Only decimal and integer types are supported.

    For details, see :cpp:func:`round_decimal`.

    Parameters
    ----------
    source : Column
        The Column for which to round values.
    decimal_places: int32_t, optional
        The number of decimal places to round to (default 0)
    round_method: rounding_method, optional
        The method by which to round each value.
        Can be one of { RoundingMethod.HALF_UP, RoundingMethod.HALF_EVEN }
        (default rounding_method.HALF_UP)
    stream : Stream | None
        CUDA stream on which to perform the operation.
    mr : DeviceMemoryResource | None
        Device memory resource used to allocate the returned column's device memory.

    Returns
    -------
    pylibcudf.Column
        A Column with values rounded
    """
