# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/scalar.pyx

import datetime
import decimal
from functools import singledispatch
from typing import Any, overload

from cpython import bool as py_bool
from cython import no_gc_clear
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource
from rmm.pylibrmm.stream import Stream

from ._interop_helpers import ArrowLike, ColumnMetadata
from .types import DataType

__all__ = ['Scalar']

@no_gc_clear
class Scalar:
    """A scalar value in device memory.

    This is the Cython representation of :cpp:class:`cudf::scalar`.
    """
    __hash__ = None

    def __init__(self, *args, **kwargs): ...
    def type(self) -> DataType:
        """The type of data in the column."""
    def is_valid(self, stream: CudaStreamLike | None=None) -> bool:
        """True if the scalar is valid, false if not"""
    def to_arrow(self, metadata: ColumnMetadata | str | None=None, stream: Stream | None=None) -> ArrowLike:
        """Create a PyArrow array from a pylibcudf scalar.

        Parameters
        ----------
        metadata : ColumnMetadata | str | None
            The metadata to attach to the scalar.
        stream : Stream | None
            CUDA stream on which to perform the operation.

        Returns
        -------
        pyarrow.Scalar
        """
    @staticmethod
    def from_arrow(pa_val, dtype: DataType | None=None, stream: Stream | None=None) -> Scalar:
        """
        Convert a pyarrow scalar to a pylibcudf.Scalar.

        Parameters
        ----------
        pa_val: pyarrow scalar
            Value to convert to a pylibcudf.Scalar
        dtype: DataType | None
            The datatype to cast the value to. If None,
            the type is inferred from the pyarrow scalar.
        stream : Stream | None
            CUDA stream on which to perform the operation.

        Returns
        -------
        Scalar
            New pylibcudf.Scalar
        """
    @classmethod
    def from_py(cls, py_val, dtype: DataType | None=None, stream: Stream | None=None, mr: DeviceMemoryResource | None=None):
        """
        Convert a Python standard library object to a Scalar.

        Parameters
        ----------
        py_val: None, bool, int, float, str, datetime, timedelta, list, dict
            Value to convert to a pylibcudf.Scalar
        dtype: DataType | None
            The datatype to cast the value to. If None,
            the type is inferred from `py_val`.
        stream : Stream | None
            CUDA stream on which to perform the operation.
        mr : DeviceMemoryResource | None
            Memory resource for allocations

        Returns
        -------
        Scalar
            New pylibcudf.Scalar
        """
    @classmethod
    def from_numpy(cls, np_val, stream: Stream | None=None, mr: DeviceMemoryResource | None=None):
        """
        Convert a NumPy scalar to a Scalar.

        Parameters
        ----------
        np_val: numpy.generic
            Value to convert to a pylibcudf.Scalar
        stream : Stream | None
            CUDA stream on which to perform the operation.
        mr : DeviceMemoryResource | None
            Memory resource for allocations

        Returns
        -------
        Scalar
            New pylibcudf.Scalar
        """
    def to_py(self, stream: Stream | None=None):
        """
        Convert a Scalar to a Python scalar.

        Parameters
        ----------
        stream : Stream | None
            CUDA stream on which to perform the operation.

        Returns
        -------
        Python scalar
            A Python scalar associated with the type of the Scalar.
        """

@overload
def _from_py(py_val: type(None), dtype: DataType | None, stream: Stream, mr: DeviceMemoryResource) -> Any: ...
@overload
def _from_py(py_val: dict, dtype: DataType | None, stream: Stream, mr: DeviceMemoryResource) -> Any: ...
@overload
def _from_py(py_val: list, dtype: DataType | None, stream: Stream, mr: DeviceMemoryResource) -> Any: ...
@overload
def _from_py(py_val: float, dtype: DataType | None, stream: Stream, mr: DeviceMemoryResource) -> Any: ...
@overload
def _from_py(py_val: int, dtype: DataType | None, stream: Stream, mr: DeviceMemoryResource) -> Any: ...
@overload
def _from_py(py_val: py_bool, dtype: DataType | None, stream: Stream, mr: DeviceMemoryResource) -> Any: ...
@overload
def _from_py(py_val: str, dtype: DataType | None, stream: Stream, mr: DeviceMemoryResource) -> Any: ...
@overload
def _from_py(py_val: datetime.timedelta, dtype: DataType | None, stream: Stream, mr: DeviceMemoryResource) -> Any: ...
@overload
def _from_py(py_val: datetime.date, dtype: DataType | None, stream: Stream, mr: DeviceMemoryResource) -> Any: ...
@overload
def _from_py(py_val: decimal.Decimal, dtype: DataType | None, stream: Stream, mr: DeviceMemoryResource) -> Any: ...
@singledispatch
def _from_numpy(np_val, stream: Stream, mr: DeviceMemoryResource): ...
def _from_arrow(obj: ..., dtype: DataType | None=None, stream: Stream | None=None) -> Scalar: ...
