# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/sorting.pyx

from pylibcudf.libcudf.aggregation import rank_method
from pylibcudf.libcudf.types import null_order, null_policy, order, size_type
from pylibcudf.types import NullOrder, Order
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

from .column import Column
from .table import Table

__all__ = ['is_sorted', 'rank', 'segmented_sort_by_key', 'sort', 'sort_by_key', 'sorted_order', 'stable_segmented_sort_by_key', 'stable_sort', 'stable_sort_by_key', 'stable_sorted_order', 'top_k', 'top_k_order']

def sorted_order(source_table: Table, column_order: list[Order], null_precedence: list[NullOrder], stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """Computes the row indices required to sort the table.

    For details, see :cpp:func:`sorted_order`.

    Parameters
    ----------
    source_table : Table
        The table to sort.
    column_order : List[ColumnOrder]
        Whether each column should be sorted in ascending or descending order.
    null_precedence : List[NullOrder]
        Whether nulls should come before or after non-nulls.

    Returns
    -------
    Column
        The row indices required to sort the table.
    """
def stable_sorted_order(source_table: Table, column_order: list[Order], null_precedence: list[NullOrder], stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """Computes the row indices required to sort the table,
    preserving order of equal elements.

    For details, see :cpp:func:`stable_sorted_order`.

    Parameters
    ----------
    source_table : Table
        The table to sort.
    column_order : List[ColumnOrder]
        Whether each column should be sorted in ascending or descending order.
    null_precedence : List[NullOrder]
        Whether nulls should come before or after non-nulls.

    Returns
    -------
    Column
        The row indices required to sort the table.
    """
def rank(input_view: Column, method: rank_method, column_order: order, null_handling: null_policy, null_precedence: null_order, percentage: bool, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """Computes the rank of each element in the column.

    For details, see :cpp:func:`rank`.

    Parameters
    ----------
    input_view : Column
        The column to rank.
    method : rank_method
        The method to use for ranking ties.
    column_order : order
        Whether the column should be sorted in ascending or descending order.
    null_handling : null_policy
        Whether or not nulls should be included in the ranking.
    null_precedence : null_order
        Whether nulls should come before or after non-nulls.
    percentage : bool
        Whether to return the rank as a percentage.

    Returns
    -------
    Column
        The rank of each element in the column.
    """
def is_sorted(tbl: Table, column_order: list[Order], null_precedence: list[NullOrder], stream: CudaStreamLike | None=None) -> bool:
    """Checks if the table is sorted.

    For details, see :cpp:func:`is_sorted`.

    Parameters
    ----------
    tbl : Table
        The table to check.
    column_order : List[ColumnOrder]
        Whether each column is expected to be sorted in ascending or descending order.
    null_precedence : List[NullOrder]
        Whether nulls are expected before or after non-nulls.

    Returns
    -------
    bool
        Whether the table is sorted.
    """
def segmented_sort_by_key(values: Table, keys: Table, segment_offsets: Column, column_order: list[Order], null_precedence: list[NullOrder], stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Table:
    """Sorts the table by key, within segments.

    For details, see :cpp:func:`segmented_sort_by_key`.

    Parameters
    ----------
    values : Table
        The table to sort.
    keys : Table
        The table to sort by.
    segment_offsets : Column
        The offsets of the segments.
    column_order : List[ColumnOrder]
        Whether each column should be sorted in ascending or descending order.
    null_precedence : List[NullOrder]
        Whether nulls should come before or after non-nulls.

    Returns
    -------
    Table
        The sorted table.
    """
def stable_segmented_sort_by_key(values: Table, keys: Table, segment_offsets: Column, column_order: list[Order], null_precedence: list[NullOrder], stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Table:
    """Sorts the table by key preserving order of equal elements,
    within segments.

    For details, see :cpp:func:`stable_segmented_sort_by_key`.

    Parameters
    ----------
    values : Table
        The table to sort.
    keys : Table
        The table to sort by.
    segment_offsets : Column
        The offsets of the segments.
    column_order : List[ColumnOrder]
        Whether each column should be sorted in ascending or descending order.
    null_precedence : List[NullOrder]
        Whether nulls should come before or after non-nulls.

    Returns
    -------
    Table
        The sorted table.
    """
def sort_by_key(values: Table, keys: Table, column_order: list[Order], null_precedence: list[NullOrder], stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Table:
    """Sorts the table by key.

    For details, see :cpp:func:`sort_by_key`.

    Parameters
    ----------
    values : Table
        The table to sort.
    keys : Table
        The table to sort by.
    column_order : List[ColumnOrder]
        Whether each column should be sorted in ascending or descending order.
    null_precedence : List[NullOrder]
        Whether nulls should come before or after non-nulls.

    Returns
    -------
    Table
        The sorted table.
    """
def stable_sort_by_key(values: Table, keys: Table, column_order: list[Order], null_precedence: list[NullOrder], stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Table:
    """Sorts the table by key preserving order of equal elements.

    For details, see :cpp:func:`stable_sort_by_key`.

    Parameters
    ----------
    values : Table
        The table to sort.
    keys : Table
        The table to sort by.
    column_order : List[ColumnOrder]
        Whether each column should be sorted in ascending or descending order.
    null_precedence : List[NullOrder]
        Whether nulls should come before or after non-nulls.

    Returns
    -------
    Table
        The sorted table.
    """
def sort(source_table: Table, column_order: list[Order], null_precedence: list[NullOrder], stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Table:
    """Sorts the table.

    For details, see :cpp:func:`sort`.

    Parameters
    ----------
    source_table : Table
        The table to sort.
    column_order : List[ColumnOrder]
        Whether each column should be sorted in ascending or descending order.
    null_precedence : List[NullOrder]
        Whether nulls should come before or after non-nulls.

    Returns
    -------
    Table
        The sorted table.
    """
def stable_sort(source_table: Table, column_order: list[Order], null_precedence: list[NullOrder], stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Table:
    """Sorts the table preserving order of equal elements.

    For details, see :cpp:func:`stable_sort`.

    Parameters
    ----------
    source_table : Table
        The table to sort.
    column_order : List[ColumnOrder]
        Whether each column should be sorted in ascending or descending order.
    null_precedence : List[NullOrder]
        Whether nulls should come before or after non-nulls.

    Returns
    -------
    Table
        The sorted table.
    """
def top_k(col: Column, k: size_type, sort_order: order=order.DESCENDING, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """
    Computes the top-k values of a column.

    For details, see :cpp:func:`top_k`.

    Parameters
    ----------
    col : Column
        The input column.
    k : int
        The number of top values to retrieve.
    sort_order : Order, default DESCENDING
        The desired order of the top values. If ASCENDING, the smallest `k` values
        are returned. If DESCENDING, the largest `k` values are returned.

    Returns
    -------
    Column
        A column of the top ``k`` elements from the input.
    """
def top_k_order(col: Column, k: size_type, sort_order: order=order.DESCENDING, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """
    Computes the indices of the top-k values of a column.

    This returns the row indices of the top-k elements.

    For details, see :cpp:func:`top_k_order`.

    Parameters
    ----------
    col : Column
        The input column.
    k : int
        The number of top values to retrieve.
    sort_order : Order, default DESCENDING
        The desired order of the top values. If ASCENDING, the indices of the smallest
        `k` values are returned. If DESCENDING, the indices of the largest `k` values
        are returned.

    Returns
    -------
    Column
        A column of the indices of the top ``k`` elements.
    """
