# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/stream_compaction.pyx

from pylibcudf.libcudf.stream_compaction import duplicate_keep_option
from pylibcudf.libcudf.stream_compaction import \
    duplicate_keep_option as DuplicateKeepOption
from pylibcudf.libcudf.types import nan_equality, null_equality, size_type
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

from .column import Column
from .expressions import Expression
from .table import Table

__all__ = ['DuplicateKeepOption', 'apply_boolean_mask', 'apply_deletion_mask', 'distinct', 'distinct_indices', 'drop_nans', 'drop_nulls', 'filter', 'stable_distinct', 'unique']

def drop_nulls(source_table: Table, keys: list[int], keep_threshold: size_type, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Table:
    """Filters out rows from the input table based on the presence of nulls.

    For details, see :cpp:func:`drop_nulls`.

    Parameters
    ----------
    source_table : Table
        The input table to filter.
    keys : List[size_type]
        The list of column indexes to consider for null filtering.
    keep_threshold : size_type
        The minimum number of non-nulls required to keep a row.

    Returns
    -------
    Table
        A new table with rows removed based on the null count.
    """
def drop_nans(source_table: Table, keys: list[int], keep_threshold: size_type, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Table:
    """Filters out rows from the input table based on the presence of NaNs.

    For details, see :cpp:func:`drop_nans`.

    Parameters
    ----------
    source_table : Table
        The input table to filter.
    keys : List[size_type]
        The list of column indexes to consider for NaN filtering.
    keep_threshold : size_type
        The minimum number of non-NaNs required to keep a row.

    Returns
    -------
    Table
        A new table with rows removed based on NaNs.
    """
def apply_boolean_mask(source_table: Table, boolean_mask: Column, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Table:
    """Filters out rows from the input table based on a boolean mask.

    For details, see :cpp:func:`apply_boolean_mask`.

    Parameters
    ----------
    source_table : Table
        The input table to filter.
    boolean_mask : Column
        The boolean mask to apply to the input table.

    Returns
    -------
    Table
        A new table with rows removed based on the boolean mask.
    """
def apply_deletion_mask(source_table: Table, deletion_mask: Column, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Table:
    """Filters out rows from the input table using a deletion mask.

    For details, see :cpp:func:`apply_deletion_mask`.

    Parameters
    ----------
    source_table : Table
        The input table to filter.
    deletion_mask : Column
        A boolean column used as a deletion mask.

    Returns
    -------
    Table
        Table with rows removed where deletion_mask is true.
    """
def unique(input: Table, keys: list[int], keep: duplicate_keep_option, nulls_equal: null_equality, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Table:
    """Filter duplicate consecutive rows from the input table.

    For details, see :cpp:func:`unique`.

    Parameters
    ----------
    input : Table
        The input table to filter
    keys : list[int]
        The list of column indexes to consider for filtering.
    keep : duplicate_keep_option
        The option to specify which rows to keep in the case of duplicates.
    nulls_equal : null_equality
        The option to specify how nulls are handled in the comparison.

    Returns
    -------
    Table
        New Table with unique rows from each sequence of equivalent rows
        as specified by keep. In the same order as the input table.

    Notes
    -----
    If the input columns to be filtered on are sorted, then
    unique can produce the same result as stable_distinct, but faster.
    """
def distinct(input: Table, keys: list[int], keep: duplicate_keep_option, nulls_equal: null_equality, nans_equal: nan_equality, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Table:
    """Get the distinct rows from the input table.

    For details, see :cpp:func:`distinct`.

    Parameters
    ----------
    input : Table
        The input table to filter.
    keys : list
        The list of column indexes to consider for distinct filtering.
    keep : duplicate_keep_option
        The option to specify which rows to keep in the case of duplicates.
    nulls_equal : null_equality
        The option to specify how nulls are handled in the comparison.
    nans_equal : nan_equality
        The option to specify how NaNs are handled in the comparison.

    Returns
    -------
    Table
        A new table with distinct rows from the input table. The
        output will not necessarily be in the same order as the input.
    """
def distinct_indices(input: Table, keep: duplicate_keep_option, nulls_equal: null_equality, nans_equal: nan_equality, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """Get the indices of the distinct rows from the input table.

    For details, see :cpp:func:`distinct_indices`.

    Parameters
    ----------
    input : Table
        The input table to filter.
    keep : duplicate_keep_option
        The option to specify which rows to keep in the case of duplicates.
    nulls_equal : null_equality
        The option to specify how nulls are handled in the comparison.
    nans_equal : nan_equality
        The option to specify how NaNs are handled in the comparison.

    Returns
    -------
    Column
        A new column with the indices of the distinct rows from the input table.
    """
def stable_distinct(input: Table, keys: list[int], keep: duplicate_keep_option, nulls_equal: null_equality, nans_equal: nan_equality, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Table:
    """Get the distinct rows from the input table, preserving input order.

    For details, see :cpp:func:`stable_distinct`.

    Parameters
    ----------
    input : Table
        The input table to filter.
    keys : list
        The list of column indexes to consider for distinct filtering.
    keep : duplicate_keep_option
        The option to specify which rows to keep in the case of duplicates.
    nulls_equal : null_equality
        The option to specify how nulls are handled in the comparison.
    nans_equal : nan_equality
        The option to specify how NaNs are handled in the comparison.

    Returns
    -------
    Table
        A new table with distinct rows from the input table, preserving
        the input table order.
    """
def filter(predicate_table: Table, predicate_expr: Expression, filter_table: Table, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Table:
    """Filters a table using a predicate expression.

    For details, see :cpp:func:`filter`.

    Parameters
    ----------
    predicate_table : Table
        The table used for predicate expression evaluation.
    predicate_expr : Expression
        The predicate filter expression.
    filter_table : Table
        The table to be filtered.

    Returns
    -------
    Table
        The filtered table.
    """
