# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/traits.pyx

from .types import DataType

__all__ = ['is_bit_castable', 'is_boolean', 'is_chrono', 'is_compound', 'is_dictionary', 'is_duration', 'is_equality_comparable', 'is_fixed_point', 'is_fixed_width', 'is_floating_point', 'is_index_type', 'is_integral', 'is_integral_not_bool', 'is_nested', 'is_numeric', 'is_numeric_not_bool', 'is_relationally_comparable', 'is_timestamp', 'is_unsigned']

def is_relationally_comparable(typ: DataType) -> bool:
    """Checks if the given data type supports relational comparisons.

    For details, see :cpp:func:`is_relationally_comparable`.
    """
def is_equality_comparable(typ: DataType) -> bool:
    """Checks if the given data type supports equality comparisons.

    For details, see :cpp:func:`is_equality_comparable`.
    """
def is_numeric(typ: DataType) -> bool:
    """Checks if the given data type is numeric.

    For details, see :cpp:func:`is_numeric`.
    """
def is_numeric_not_bool(typ: DataType) -> bool:
    """Checks if the given data type is numeric excluding booleans.

    For details, see :cpp:func:`is_numeric_not_bool`.
    """
def is_index_type(typ: DataType) -> bool:
    """Checks if the given data type is an index type.

    For details, see :cpp:func:`is_index_type`.
    """
def is_unsigned(typ: DataType) -> bool:
    """Checks if the given data type is an unsigned type.

    For details, see :cpp:func:`is_unsigned`.
    """
def is_integral(typ: DataType) -> bool:
    """Checks if the given data type is an integral type.

    For details, see :cpp:func:`is_integral`.
    """
def is_integral_not_bool(typ: DataType) -> bool:
    """Checks if the given data type is an integral type excluding booleans.

    For details, see :cpp:func:`is_integral_not_bool`.
    """
def is_floating_point(typ: DataType) -> bool:
    """Checks if the given data type is a floating point type.

    For details, see :cpp:func:`is_floating_point`.
    """
def is_boolean(typ: DataType) -> bool:
    """Checks if the given data type is a boolean type.

    For details, see :cpp:func:`is_boolean`.
    """
def is_timestamp(typ: DataType) -> bool:
    """Checks if the given data type is a timestamp type.

    For details, see :cpp:func:`is_timestamp`.
    """
def is_fixed_point(typ: DataType) -> bool:
    """Checks if the given data type is a fixed point type.

    For details, see :cpp:func:`is_fixed_point`.
    """
def is_duration(typ: DataType) -> bool:
    """Checks if the given data type is a duration type.

    For details, see :cpp:func:`is_duration`.
    """
def is_chrono(typ: DataType) -> bool:
    """Checks if the given data type is a chrono type.

    For details, see :cpp:func:`is_chrono`.
    """
def is_dictionary(typ: DataType) -> bool:
    """Checks if the given data type is a dictionary type.

    For details, see :cpp:func:`is_dictionary`.
    """
def is_fixed_width(typ: DataType) -> bool:
    """Checks if the given data type is a fixed width type.

    For details, see :cpp:func:`is_fixed_width`.
    """
def is_compound(typ: DataType) -> bool:
    """Checks if the given data type is a compound type.

    For details, see :cpp:func:`is_compound`.
    """
def is_nested(typ: DataType) -> bool:
    """Checks if the given data type is a nested type.

    For details, see :cpp:func:`is_nested`.
    """
def is_bit_castable(source: DataType, target: DataType) -> bool:
    """Checks if the source type is bit-castable to the target type.

    For details, see :cpp:func:`is_bit_castable`.
    """
