# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/transform.pyx

from collections.abc import Sequence

from pylibcudf.libcudf.types import null_aware, output_nullability
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

from .column import Column
from .expressions import Expression
from .table import Table
from .types import DataType

const_transform_input = ...
const_transform_output = ...
__all__ = ['bools_to_mask', 'column_nans_to_nulls', 'compute_column', 'compute_column_jit', 'encode', 'mask_to_bools', 'nans_to_nulls', 'one_hot_encode', 'transform']

def nans_to_nulls(input: Column, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> tuple[object, int]:
    """Create a null mask preserving existing nulls and converting nans to null.

    For details, see :cpp:func:`nans_to_nulls`.

    Parameters
    ----------
    input : Column
        Column to produce new mask from.
    stream : Stream | None
        CUDA stream on which to perform the operation.
    mr : DeviceMemoryResource | None
        Device memory resource used to allocate the returned mask's device memory.

    Returns
    -------
    Two-tuple of a gpumemoryview wrapping the null mask and the new null count.
    """
def column_nans_to_nulls(input: Column, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """Create a column with nans converted to nulls.

    For details, see :cpp:func:`column_nans_to_nulls`.

    Parameters
    ----------
    input : Column
        Column to convert nans to nulls.
    stream : Stream | None
        CUDA stream on which to perform the operation.
    mr : DeviceMemoryResource | None
        Device memory resource used to allocate the returned column's device memory.

    Returns
    -------
    Column
        New column with nans converted to nulls.
    """
def compute_column(input: Table, expr: Expression, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """Create a column by evaluating an expression on a table.

    For details see :cpp:func:`compute_column`.

    Parameters
    ----------
    input : Table
        Table used for expression evaluation
    expr : Expression
        Expression to evaluate
    stream : Stream | None
        CUDA stream on which to perform the operation.
    mr : DeviceMemoryResource | None
        Device memory resource used to allocate the returned column's device memory.

    Returns
    -------
    Column of the evaluated expression
    """
def compute_column_jit(input: Table, expr: Expression, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """
    Create a column by evaluating an expression on a table
    using a JIT-compiled kernel.

    For details see :cpp:func:`compute_column_jit`.

    Parameters
    ----------
    input : Table
        Table used for expression evaluation
    expr : Expression
        Expression to evaluate
    stream : Stream | None
        CUDA stream on which to perform the operation.
    mr : DeviceMemoryResource | None
        Device memory resource used to allocate the returned column's device memory.

    Returns
    -------
    Column of the evaluated expression
    """
def bools_to_mask(input: Column, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> tuple[object, int]:
    """Create a bitmask from a column of boolean elements

    Parameters
    ----------
    input : Column
        Column to produce new mask from.
    stream : Stream | None
        CUDA stream on which to perform the operation.
    mr : DeviceMemoryResource | None
        Device memory resource used to allocate the returned mask's device memory.

    Returns
    -------
    tuple[gpumemoryview, int]
        Two-tuple of a gpumemoryview wrapping the bitmask and the null count.
    """
def mask_to_bools(bitmask: int, begin_bit: int, end_bit: int, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """Creates a boolean column from given bitmask.

    Parameters
    ----------
    bitmask : int
        Pointer to the bitmask which needs to be converted
    begin_bit : int
        Position of the bit from which the conversion should start
    end_bit : int
        Position of the bit before which the conversion should stop
    stream : Stream | None
        CUDA stream on which to perform the operation.
    mr : DeviceMemoryResource | None
        Device memory resource used to allocate the returned column's device memory.

    Returns
    -------
    Column
        Boolean column of the bitmask from [begin_bit, end_bit]
    """
def transform(inputs: Sequence[Column], transform_udf: str, output_type: DataType, is_ptx: bool, is_null_aware: null_aware, null_policy: output_nullability, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """Create a new column by applying a transform function against
       multiple input columns.

    Parameters
    ----------
    inputs : Sequence[Column]
        Columns to transform.
    transform_udf : str
        The PTX/CUDA string of the transform function to apply.
    output_type : DataType
        The output type that is compatible with the output type in the unary_udf.
    is_ptx : bool
        If `True`, the UDF is treated as PTX code.
        If `False`, the UDF is treated as CUDA code.
    is_null_aware: NullAware
        If `NO`, the UDF gets non-nullable parameters
        If `YES`, the UDF gets nullable parameters
    null_policy: OutputNullability
        If `PRESERVE`, null-masks are produced if necessary.
        If `ALL_VALID`, null-masks are not produced.
        `ALL_VALID` has undefined behavior if the UDF can produce nulls.
    stream : Stream | None
        CUDA stream on which to perform the operation.
    mr : DeviceMemoryResource | None
        Device memory resource used to allocate the returned column's device memory.

    Returns
    -------
    Column
        The transformed column having the UDF applied to each element.
    """
def encode(input: Table, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> tuple[object, object]:
    """Encode the rows of the given table as integers.

    Parameters
    ----------
    input : Table
        Table containing values to be encoded
    stream : Stream | None
        CUDA stream on which to perform the operation.
    mr : DeviceMemoryResource | None
        Device memory resource used to allocate the returned objects' device memory.

    Returns
    -------
    tuple[Table, Column]
        The distinct row of the input table in sorted order,
        and a column of integer indices representing the encoded rows.
    """
def one_hot_encode(input: Column, categories: Column, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Table:
    """Encodes `input` by generating a new column
    for each value in `categories` indicating the presence
    of that value in `input`.

    Parameters
    ----------
    input : Column
        Column containing values to be encoded.
    categories : Column
        Column containing categories
    stream : Stream | None
        CUDA stream on which to perform the operation.
    mr : DeviceMemoryResource | None
        Device memory resource used to allocate the returned table's device memory.

    Returns
    -------
    Column
        A table of the encoded values.
    """
