# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/types.pyx

from functools import cache

import pyarrow as pa
from pylibcudf.libcudf.types import bitmask_type
from pylibcudf.libcudf.types import interpolation as Interpolation
from pylibcudf.libcudf.types import mask_state as MaskState
from pylibcudf.libcudf.types import nan_equality as NanEquality
from pylibcudf.libcudf.types import nan_policy as NanPolicy
from pylibcudf.libcudf.types import null_aware as NullAware
from pylibcudf.libcudf.types import null_equality as NullEquality
from pylibcudf.libcudf.types import null_order as NullOrder
from pylibcudf.libcudf.types import null_policy as NullPolicy
from pylibcudf.libcudf.types import order as Order
from pylibcudf.libcudf.types import output_nullability as OutputNullability
from pylibcudf.libcudf.types import size_type
from pylibcudf.libcudf.types import sorted as Sorted
from pylibcudf.libcudf.types import type_id
from pylibcudf.libcudf.types import type_id as TypeId
from pylibcudf.libcudf.utilities.type_dispatcher import type_to_id

__all__ = ['DataType', 'Interpolation', 'MaskState', 'NanEquality', 'NanPolicy', 'NullEquality', 'NullOrder', 'NullAware', 'OutputNullability', 'NullPolicy', 'Order', 'SIZE_TYPE', 'SIZE_TYPE_ID', 'Sorted', 'TypeId', 'size_of']
SIZE_TYPE = DataType(type_to_id[size_type]())
SIZE_TYPE_ID = SIZE_TYPE.id()
BITMASK_TYPE = DataType(type_to_id[bitmask_type]())

class DataType:
    """Indicator for the logical data type of an element in a column.

    This is the Cython representation of :cpp:class:`cudf::data_type`.

    Parameters
    ----------
    id : type_id
        The type's identifier
    scale : int
        The scale associated with the data. Only used for decimal data types.
    """
    def __init__(self, id: type_id, scale: int=0): ...
    def id(self) -> type_id:
        """Get the id associated with this data type."""
    def scale(self) -> int:
        """Get the scale associated with this data type."""
    @property
    def _python_typecode(self) -> str:
        """The Python struct module typecode string."""
    @property
    def typestr(self) -> str:
        """The array interface type string."""
    def __eq__(self, other): ...
    def __hash__(self): ...
    def __reduce__(self): ...
    def to_arrow(self, **kwargs) -> pa.DataType:
        """
        Convert a datatype to arrow.

        Returns
        -------
        pyarrow.DataType

        Notes
        -----
        Translation of some types requires extra information as a keyword
        argument. Specifically:

        - When translating a decimal type, provide ``precision``
        - When translating a struct type, provide ``fields``
        - When translating a list type, provide the wrapped ``value_type``
        """
    @staticmethod
    def from_arrow(pa_typ: pa.DataType) -> DataType:
        """
        Construct a DataType from a Python type.

        Parameters
        ----------
        pa_typ : pyarrow type
            A Pyarrow type (eg. pa)

        Returns
        -------
        DataType
            The corresponding pylibcudf DataType.

        Raises
        ------
        ImportError
            If pyarrow is not installed.
        TypeError
            If the Python type is not supported.
        """
    @staticmethod
    def from_py(typ: type) -> DataType:
        """
        Construct a DataType from a Python type.

        Parameters
        ----------
        typ : type
            A Python type (eg. int, str, list)

        Returns
        -------
        DataType
            The corresponding pylibcudf DataType.

        Raises
        ------
        TypeError
            If the Python type is not supported.
        """

def size_of(t: DataType) -> int:
    """Returns the size in bytes of elements of the specified data_type.

    Only fixed-width types are supported.

    For details, see :cpp:func:`size_of`.

    Parameters
    ----------
    t : DataType
        The DataType to get the size of.

    Returns
    -------
    int
        Size in bytes of an element of the specified type.
    """
@cache
def _from_arrow(obj: pa.DataType) -> DataType: ...
