# SPDX-FileCopyrightText: Copyright (c) 2025-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/utils.pyx

from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.stream import Stream

constscalar = ...

def _get_stream(stream: CudaStreamLike | None=None) -> Stream: ...
