# SPDX-FileCopyrightText: Copyright (c) 2025-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/utilities.pyx

__all__ = ['is_ptds_enabled']

def is_ptds_enabled() -> bool:
    """Checks if per-thread default stream is enabled.

    For details, see :cpp:func:`is_ptds_enabled`.
    """
