# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/io/avro.pyx

from pylibcudf.io.types import SourceInfo, TableWithMetadata
from pylibcudf.libcudf.types import size_type
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

__all__ = ['read_avro', 'AvroReaderOptions', 'AvroReaderOptionsBuilder']

class AvroReaderOptions:
    """
    The settings to use for ``read_avro``
    For details, see :cpp:class:`cudf::io::avro_reader_options`
    """
    @staticmethod
    def builder(source: SourceInfo):
        """
        Create a AvroWriterOptionsBuilder object

        For details, see :cpp:func:`cudf::io::avro_reader_options::builder`

        Parameters
        ----------
        sink : SourceInfo
            The source to read the Avro file from.

        Returns
        -------
        AvroReaderOptionsBuilder
            Builder to build AvroReaderOptions
        """
    def set_columns(self, col_names: list[str]) -> None:
        """
        Set names of the column to be read.

        Parameters
        ----------
        col_names : list[str]
            List of column names

        Returns
        -------
        None
        """
    def set_source(self, src: SourceInfo) -> None:
        """
        Set a new source info location.

        Parameters
        ----------
        src : SourceInfo
            New source information, replacing existing information.

        Returns
        -------
        None
        """

class AvroReaderOptionsBuilder:
    def columns(self, col_names: list[str]) -> AvroReaderOptionsBuilder:
        """
        Set names of the column to be read.

        Parameters
        ----------
        col_names : list
            List of column names

        Returns
        -------
        AvroReaderOptionsBuilder
        """
    def skip_rows(self, skip_rows: size_type) -> AvroReaderOptionsBuilder:
        """
        Sets number of rows to skip.

        Parameters
        ----------
        skip_rows : size_type
            Number of rows to skip from start

        Returns
        -------
        AvroReaderOptionsBuilder
        """
    def num_rows(self, num_rows: size_type) -> AvroReaderOptionsBuilder:
        """
        Sets number of rows to read.

        Parameters
        ----------
        num_rows : size_type
            Number of rows to read after skip

        Returns
        -------
        AvroReaderOptionsBuilder
        """
    def build(self) -> AvroReaderOptions:
        """Create a AvroReaderOptions object"""

def read_avro(options: AvroReaderOptions, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> TableWithMetadata:
    """
    Read from Avro format.

    The source to read from and options are encapsulated
    by the `options` object.

    For details, see :cpp:func:`read_avro`.

    Parameters
    ----------
    options: AvroReaderOptions
        Settings for controlling reading behavior
    stream : Stream | None
        CUDA stream used for device memory operations and kernel launches
    mr : DeviceMemoryResource, optional
        Device memory resource used to allocate the returned table's device memory.
    """
