# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/io/csv.pyx

from pylibcudf.io.types import SinkInfo, SourceInfo, TableWithMetadata
from pylibcudf.libcudf.io.types import compression_type, quote_style
from pylibcudf.libcudf.types import size_type
from pylibcudf.table import Table
from pylibcudf.types import DataType
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

__all__ = ['read_csv', 'write_csv', 'CsvWriterOptions', 'CsvWriterOptionsBuilder', 'CsvReaderOptions', 'CsvReaderOptionsBuilder']

class CsvReaderOptions:
    """The settings to use for ``read_csv``
    For details, see :cpp:class:`cudf::io::csv_reader_options`
    """
    @staticmethod
    def builder(source: SourceInfo):
        """
        Create a CsvWriterOptionsBuilder object

        For details, see :cpp:func:`cudf::io::csv_reader_options::builder`

        Parameters
        ----------
        sink : SourceInfo
            The source to read the CSV file from.

        Returns
        -------
        CsvReaderOptionsBuilder
            Builder to build CsvReaderOptions
        """
    def set_header(self, header: size_type) -> None:
        """
        Sets header row index.

        Parameters
        ----------
        header : size_type
            Index where header row is located

        Returns
        -------
        None
        """
    def set_names(self, col_names: list[str]) -> None:
        """
        Sets names of the column.

        Parameters
        ----------
        col_names : list[str]
            List of column names

        Returns
        -------
        None
        """
    def set_prefix(self, prefix: str) -> None:
        """
        Sets prefix to be used for column ID.

        Parameters
        ----------
        prefix : str
            String used as prefix in for each column name

        Returns
        -------
        None
        """
    def set_use_cols_indexes(self, col_indices: list[int]) -> None:
        """
        Sets indexes of columns to read.

        Parameters
        ----------
        col_indices : list[int]
            List of column indices that are needed

        Returns
        -------
        None
        """
    def set_use_cols_names(self, col_names: list[str]) -> None:
        """
        Sets names of the columns to be read.

        Parameters
        ----------
        col_names : list[str]
            List of column indices that are needed

        Returns
        -------
        None
        """
    def set_delimiter(self, delimiter: str) -> None:
        """
        Sets field delimiter.

        Parameters
        ----------
        delimiter : str
            A character to indicate delimiter

        Returns
        -------
        None
        """
    def set_thousands(self, thousands: str) -> None:
        """
        Sets numeric data thousands separator.

        Parameters
        ----------
        thousands : str
            A character that separates thousands

        Returns
        -------
        None
        """
    def set_comment(self, comment: str) -> None:
        """
        Sets comment line start character.

        Parameters
        ----------
        comment : str
            A character that indicates comment

        Returns
        -------
        None
        """
    def set_parse_dates(self, val: list[int | str]) -> None:
        """
        Sets indexes or names of columns to read as datetime.

        Parameters
        ----------
        val : list[int | str]
            List column indices or names to infer as datetime.

        Returns
        -------
        None
        """
    def set_parse_hex(self, val: list[int | str]) -> None:
        """
        Sets indexes or names of columns to parse as hexadecimal.

        Parameters
        ----------
        val : list[int | str]
            List of column indices or names to parse as hexadecimal

        Returns
        -------
        None
        """
    def set_dtypes(self, types: dict[str, DataType] | list[DataType]) -> None:
        """
        Sets per-column types.

        Parameters
        ----------
        types : dict[str, data_type] | list[data_type]
            Column name to data type map specifying the columns' target data types.
            Or a list specifying the columns' target data types.

        Returns
        -------
        None
        """
    def set_true_values(self, true_values: list[str]) -> None:
        """
        Sets additional values to recognize as boolean true values.

        Parameters
        ----------
        true_values : list[str]
            List of values to be considered to be true

        Returns
        -------
        None
        """
    def set_false_values(self, false_values: list[str]) -> None:
        """
        Sets additional values to recognize as boolean false values.

        Parameters
        ----------
        false_values : list[str]
            List of values to be considered to be false

        Returns
        -------
        None
        """
    def set_na_values(self, na_values: list[str]) -> None:
        """
        Sets additional values to recognize as null values.

        Parameters
        ----------
        na_values : list[str]
            List of values to be considered to be null

        Returns
        -------
        None
        """
    def set_source(self, src: SourceInfo) -> None:
        """
        Set a new source info location.

        Parameters
        ----------
        src : SourceInfo
            New source information, replacing existing information.

        Returns
        -------
        None
        """

class CsvReaderOptionsBuilder:
    """
    Builder to build options for ``read_csv``

    For details, see :cpp:class:`cudf::io::csv_reader_options_builder`
    """
    def compression(self, compression: compression_type) -> CsvReaderOptionsBuilder:
        """
        Sets compression format of the source.

        Parameters
        ----------
        compression : compression_type
            Compression type

        Returns
        -------
        CsvReaderOptionsBuilder
        """
    def mangle_dupe_cols(self, mangle_dupe_cols: bool) -> CsvReaderOptionsBuilder:
        """
        Sets whether to rename duplicate column names.

        Parameters
        ----------
        mangle_dupe_cols : bool
            Boolean value to enable/disable

        Returns
        -------
        CsvReaderOptionsBuilder
        """
    def byte_range_offset(self, byte_range_offset: int) -> CsvReaderOptionsBuilder:
        """
        Sets number of bytes to skip from source start.

        Parameters
        ----------
        byte_range_offset : size_t
            Number of bytes of offset

        Returns
        -------
        CsvReaderOptionsBuilder
        """
    def byte_range_size(self, byte_range_size: int) -> CsvReaderOptionsBuilder:
        """
        Sets number of bytes to read.

        Parameters
        ----------
        byte_range_offset : size_t
            Number of bytes to read

        Returns
        -------
        CsvReaderOptionsBuilder
        """
    def nrows(self, nrows: size_type) -> CsvReaderOptionsBuilder:
        """
        Sets number of rows to read.

        Parameters
        ----------
        nrows : size_type
            Number of rows to read

        Returns
        -------
        CsvReaderOptionsBuilder
        """
    def skiprows(self, skiprows: size_type) -> CsvReaderOptionsBuilder:
        """
        Sets number of rows to skip from start.

        Parameters
        ----------
        skiprows : size_type
            Number of rows to skip

        Returns
        -------
        CsvReaderOptionsBuilder
        """
    def skipfooter(self, skipfooter: size_type) -> CsvReaderOptionsBuilder:
        """
        Sets number of rows to skip from end.

        Parameters
        ----------
        skipfooter : size_type
            Number of rows to skip

        Returns
        -------
        CsvReaderOptionsBuilder
        """
    def quoting(self, quoting: quote_style) -> CsvReaderOptionsBuilder:
        """
        Sets quoting style.

        Parameters
        ----------
        quoting : quote_style
            Quoting style used

        Returns
        -------
        CsvReaderOptionsBuilder
        """
    def lineterminator(self, lineterminator: str) -> CsvReaderOptionsBuilder:
        """
        Sets line terminator.

        Parameters
        ----------
        quoting : str
            A character to indicate line termination

        Returns
        -------
        CsvReaderOptionsBuilder
        """
    def quotechar(self, quotechar: str) -> CsvReaderOptionsBuilder:
        """
        Sets quoting character.

        Parameters
        ----------
        quotechar : str
            A character to indicate quoting

        Returns
        -------
        CsvReaderOptionsBuilder
        """
    def decimal(self, decimal: str) -> CsvReaderOptionsBuilder:
        """
        Sets decimal point character.

        Parameters
        ----------
        quotechar : str
            A character that indicates decimal values

        Returns
        -------
        CsvReaderOptionsBuilder
        """
    def delim_whitespace(self, delim_whitespace: bool) -> CsvReaderOptionsBuilder:
        """
        Sets whether to treat whitespace as field delimiter.

        Parameters
        ----------
        delim_whitespace : bool
            Boolean value to enable/disable

        Returns
        -------
        CsvReaderOptionsBuilder
        """
    def skipinitialspace(self, skipinitialspace: bool) -> CsvReaderOptionsBuilder:
        """
        Sets whether to skip whitespace after the delimiter.

        Parameters
        ----------
        skipinitialspace : bool
            Boolean value to enable/disable

        Returns
        -------
        CsvReaderOptionsBuilder
        """
    def skip_blank_lines(self, skip_blank_lines: bool) -> CsvReaderOptionsBuilder:
        """
        Sets whether to ignore empty lines or parse line values as invalid.

        Parameters
        ----------
        skip_blank_lines : bool
            Boolean value to enable/disable

        Returns
        -------
        CsvReaderOptionsBuilder
        """
    def doublequote(self, doublequote: bool) -> CsvReaderOptionsBuilder:
        """
        Sets a quote inside a value is double-quoted.

        Parameters
        ----------
        doublequote : bool
            Boolean value to enable/disable

        Returns
        -------
        CsvReaderOptionsBuilder
        """
    def keep_default_na(self, keep_default_na: bool) -> CsvReaderOptionsBuilder:
        """
        Sets whether to keep the built-in default NA values.

        Parameters
        ----------
        keep_default_na : bool
            Boolean value to enable/disable

        Returns
        -------
        CsvReaderOptionsBuilder
        """
    def na_filter(self, na_filter: bool) -> CsvReaderOptionsBuilder:
        """
        Sets whether to disable null filter.

        Parameters
        ----------
        na_filter : bool
            Boolean value to enable/disable

        Returns
        -------
        CsvReaderOptionsBuilder
        """
    def dayfirst(self, dayfirst: bool) -> CsvReaderOptionsBuilder:
        """
        Sets whether to parse dates as DD/MM versus MM/DD.

        Parameters
        ----------
        dayfirst : bool
            Boolean value to enable/disable

        Returns
        -------
        CsvReaderOptionsBuilder
        """
    def delimiter(self, delimiter: str) -> CsvReaderOptionsBuilder:
        """
        Sets field delimiter.

        Parameters
        ----------
        delimiter : str
            A character to indicate delimiter

        Returns
        -------
        CsvReaderOptionsBuilder
        """
    def build(self) -> CsvReaderOptions:
        """Create a CsvReaderOptions object"""

class CsvWriterOptions:
    """The settings to use for ``write_csv``

    For details, see :cpp:class:`cudf::io::csv_writer_options`
    """
    @staticmethod
    def builder(sink: SinkInfo, table: Table):
        """Create a CsvWriterOptionsBuilder object

        For details, see :cpp:func:`cudf::io::csv_writer_options::builder`

        Parameters
        ----------
        sink : SinkInfo
            The sink used for writer output
        table : Table
            Table to be written to output

        Returns
        -------
        CsvWriterOptionsBuilder
            Builder to build CsvWriterOptions
        """

class CsvWriterOptionsBuilder:
    """Builder to build options for ``write_csv``

    For details, see :cpp:class:`cudf::io::csv_writer_options_builder`
    """
    def names(self, names: list) -> CsvWriterOptionsBuilder:
        """Sets optional column names.

        Parameters
        ----------
        names : list[str]
            Column names

        Returns
        -------
        CsvWriterOptionsBuilder
            Builder to build CsvWriterOptions
        """
    def na_rep(self, val: str) -> CsvWriterOptionsBuilder:
        """Sets string to used for null entries.

        Parameters
        ----------
        val : str
            String to represent null value

        Returns
        -------
        CsvWriterOptionsBuilder
            Builder to build CsvWriterOptions
        """
    def include_header(self, val: bool) -> CsvWriterOptionsBuilder:
        """Enables/Disables headers being written to csv.

        Parameters
        ----------
        val : bool
            Boolean value to enable/disable

        Returns
        -------
        CsvWriterOptionsBuilder
            Builder to build CsvWriterOptions
        """
    def rows_per_chunk(self, val: int) -> CsvWriterOptionsBuilder:
        """Sets maximum number of rows to process for each file write.

        Parameters
        ----------
        val : int
            Number of rows per chunk

        Returns
        -------
        CsvWriterOptionsBuilder
            Builder to build CsvWriterOptions
        """
    def line_terminator(self, term: str) -> CsvWriterOptionsBuilder:
        """Sets character used for separating lines.

        Parameters
        ----------
        term : str
            Character to represent line termination

        Returns
        -------
        CsvWriterOptionsBuilder
            Builder to build CsvWriterOptions
        """
    def inter_column_delimiter(self, delim: str) -> CsvWriterOptionsBuilder:
        """Sets character used for separating column values.

        Parameters
        ----------
        delim : str
            Character to delimit column values

        Returns
        -------
        CsvWriterOptionsBuilder
            Builder to build CsvWriterOptions
        """
    def true_value(self, val: str) -> CsvWriterOptionsBuilder:
        """Sets string used for values != 0

        Parameters
        ----------
        val : str
            String to represent values != 0

        Returns
        -------
        CsvWriterOptionsBuilder
            Builder to build CsvWriterOptions
        """
    def false_value(self, val: str) -> CsvWriterOptionsBuilder:
        """Sets string used for values == 0

        Parameters
        ----------
        val : str
            String to represent values == 0

        Returns
        -------
        CsvWriterOptionsBuilder
            Builder to build CsvWriterOptions
        """
    def quoting(self, style: quote_style) -> CsvWriterOptionsBuilder:
        """Sets quoting style for string columns.

        Parameters
        ----------
        style : quote_style
            Quoting style (MINIMAL or NONE).
            MINIMAL: Quote only fields containing special characters.
            NONE: Never quote fields.

        Returns
        -------
        CsvWriterOptionsBuilder
            Builder to build CsvWriterOptions
        """
    def build(self) -> CsvWriterOptions:
        """Create a CsvWriterOptions object"""

def read_csv(options: CsvReaderOptions, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> TableWithMetadata:
    """
    Read from CSV format.

    The source to read from and options are encapsulated
    by the `options` object.

    For details, see :cpp:func:`read_csv`.

    Parameters
    ----------
    options: CsvReaderOptions
        Settings for controlling reading behavior
    stream : Stream | None
        CUDA stream used for device memory operations and kernel launches
    mr : DeviceMemoryResource, optional
        Device memory resource used to allocate the returned table's device memory.
    """
def write_csv(options: CsvWriterOptions, stream: CudaStreamLike | None=None) -> None:
    """
    Write to CSV format.

    The table to write, output paths, and options are encapsulated
    by the `options` object.

    For details, see :cpp:func:`write_csv`.

    Parameters
    ----------
    options: CsvWriterOptions
        Settings for controlling writing behavior
    stream : Stream | None
        CUDA stream used for device memory operations and kernel launches
    """
def is_supported_write_csv(type: DataType) -> bool:
    """Check if the dtype is supported for CSV writing

    For details, see :cpp:func:`is_supported_write_type`.
    """
