# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/io/json.pyx

from typing import TypeAlias

from pylibcudf.column import Column
from pylibcudf.io.types import (SinkInfo, SourceInfo, TableWithMetadata,
                                compression_type)
from pylibcudf.libcudf.io.json import json_recovery_mode_t
from pylibcudf.libcudf.types import size_type
from pylibcudf.scalar import Scalar
from pylibcudf.table import Table
from pylibcudf.types import DataType
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

__all__ = ['chunked_read_json', 'read_json', 'read_json_from_string_column', 'write_json', 'JsonReaderOptions', 'JsonReaderOptionsBuilder', 'JsonWriterOptions', 'JsonWriterOptionsBuilder']
NameAndType: TypeAlias = tuple[str, DataType, list['NameAndType']]

class JsonReaderOptions:
    """
    The settings to use for ``read_json``

    For details, see `:cpp:class:`cudf::io::json_reader_options`
    """
    @staticmethod
    def builder(source: SourceInfo):
        """
        Create a JsonReaderOptionsBuilder object

        For details, see :cpp:func:`cudf::io::json_reader_options::builder`

        Parameters
        ----------
        sink : SourceInfo
            The source to read the JSON file from.

        Returns
        -------
        JsonReaderOptionsBuilder
            Builder to build JsonReaderOptions
        """
    def set_dtypes(self, types: list[DataType] | list[NameAndType]) -> None:
        """
        Set data types for columns to be read.

        Parameters
        ----------
        types : list
            List of dtypes or a list of tuples of
            column names, dtypes, and list of tuples
            (to support nested column hierarchy)

        Returns
        -------
        None
        """
    def enable_keep_quotes(self, keep_quotes: bool) -> None:
        """
        Set whether the reader should keep quotes of string values.

        Parameters
        ----------
        keep_quotes : bool
           Boolean value to indicate whether the reader should
           keep quotes of string values

        Returns
        -------
        None
        """
    def enable_mixed_types_as_string(self, mixed_types_as_string: bool) -> None:
        """
        Set whether to parse mixed types as a string column.
        Also enables forcing to read a struct as string column using schema.

        Parameters
        ----------
        mixed_types_as_string : bool
           Boolean value to enable/disable parsing mixed types
           as a string column

        Returns
        -------
        None
        """
    def enable_prune_columns(self, prune_columns: bool) -> None:
        """
        Set whether to prune columns on read, selected
        based on the ``set_dtypes`` option.

        Parameters
        ----------
        prune_columns : bool
           When set as true, if the reader options include
           ``set_dtypes``, then the reader will only return those
           columns which are mentioned in ``set_dtypes``. If false,
           then all columns are returned, independent of the
           ``set_dtypes`` setting.

        Returns
        -------
        None
        """
    def set_byte_range_offset(self, offset: int) -> None:
        """
        Set number of bytes to skip from source start.

        Parameters
        ----------
        offset : size_t
            Number of bytes of offset

        Returns
        -------
        None
        """
    def set_byte_range_size(self, size: int) -> None:
        """
        Set number of bytes to read.

        Parameters
        ----------
        size : size_t
            Number of bytes to read

        Returns
        -------
        None
        """
    def enable_lines(self, val: bool) -> None:
        """
        Set whether to read the file as a json object per line.

        Parameters
        ----------
        val : bool
            Boolean value to enable/disable the option
            to read each line as a json object

        Returns
        -------
        None
        """
    def set_delimiter(self, val: str) -> None: ...
    def enable_dayfirst(self, val: bool) -> None: ...
    def enable_experimental(self, val: bool) -> None: ...
    def enable_normalize_single_quotes(self, val: bool) -> None: ...
    def enable_normalize_whitespace(self, val: bool) -> None: ...
    def set_strict_validation(self, val: bool) -> None: ...
    def allow_unquoted_control_chars(self, val: bool) -> None: ...
    def allow_numeric_leading_zeros(self, val: bool) -> None: ...
    def allow_nonnumeric_numbers(self, val: bool) -> None: ...
    def set_na_values(self, vals: list[str]) -> None: ...
    def set_source(self, src: SourceInfo) -> None:
        """
        Set a new source info location.

        Parameters
        ----------
        src : SourceInfo
            New source information, replacing existing information.

        Returns
        -------
        None
        """

class JsonReaderOptionsBuilder:
    def byte_range_offset(self, byte_range_offset: int) -> JsonReaderOptionsBuilder:
        """
        Set number of bytes to skip from source start.

        Parameters
        ----------
        byte_range_offset : size_t
            Number of bytes of offset

        Returns
        -------
        Self
        """
    def byte_range_size(self, byte_range_size: int) -> JsonReaderOptionsBuilder:
        """
        Set number of bytes to read.

        Parameters
        ----------
        byte_range_size : size_t
            Number of bytes to read

        Returns
        -------
        Self
        """
    def compression(self, compression: compression_type) -> JsonReaderOptionsBuilder:
        """
        Sets compression type.

        Parameters
        ----------
        compression : CompressionType
            The compression type to use

        Returns
        -------
        Self
        """
    def dayfirst(self, val: bool) -> JsonReaderOptionsBuilder:
        """
        Set whether the reader should parse dates as DD/MM versus MM/DD.

        Parameters
        ----------
        val : bool
            Boolean value to indicate whether the
            reader should enable/disable DD/MM parsing

        Returns
        -------
        Self
        """
    def delimiter(self, delimiter: str) -> JsonReaderOptionsBuilder:
        """
        Set delimiter character separating records in JSON lines inputs

        Parameters
        ----------
        delimiter : str
            Character to be used as delimiter separating records

        Returns
        -------
        Self
        """
    def dtypes(self, types: list) -> JsonReaderOptionsBuilder:
        """
        Set data type for columns to be read

        Parameters
        ----------
        types : list
            List of dtypes or a list of tuples of
            column names, dtypes, and list of tuples
            (to support nested column hierarchy)

        Returns
        -------
        Self
        """
    def experimental(self, val: bool) -> JsonReaderOptionsBuilder:
        """
        Set whether to enable experimental features.
        When set to true, experimental features, such as the new column tree
        construction, utf-8 matching of field names will be enabled.

        Parameters
        ----------
        val : bool
            Boolean value to enable/disable experimental features

        Returns
        -------
        Self
        """
    def keep_quotes(self, val: bool) -> JsonReaderOptionsBuilder:
        """
        Set whether the reader should keep quotes of string values.

        Parameters
        ----------
        val : bool
            Boolean value to indicate whether the
            reader should keep quotes of string values

        Returns
        -------
        Self
        """
    def lines(self, val: bool) -> JsonReaderOptionsBuilder:
        """
        Set whether to read the file as a json object per line.

        Parameters
        ----------
        val : bool
            Boolean value to enable/disable the option
            to read each line as a json object

        Returns
        -------
        Self
        """
    def mixed_types_as_string(self, val: bool) -> JsonReaderOptionsBuilder:
        """
        Set whether to parse mixed types as a string column.
        Also enables forcing to read a struct as string column using schema.

        Parameters
        ----------
        val : bool
            Boolean value to enable/disable parsing mixed types as a string column

        Returns
        -------
        Self
        """
    def na_values(self, vals: list) -> JsonReaderOptionsBuilder:
        """
        Sets additional values to recognize as null values.

        Parameters
        ----------
        vals : list
            Vector of values to be considered to be null

        Returns
        -------
        Self
        """
    def nonnumeric_numbers(self, val: bool) -> JsonReaderOptionsBuilder:
        """
        Set whether unquoted number values should be allowed NaN, +INF, -INF, +Infinity,
        Infinity, and -Infinity. Strict validation must be enabled for this to work.

        Parameters
        ----------
        val : bool
            Boolean value to indicate whether leading zeros are allowed in numeric
            values

        Returns
        -------
        Self
        """
    def normalize_single_quotes(self, val: bool) -> JsonReaderOptionsBuilder:
        """
        Sets whether to normalize single quotes around strings.

        Parameters
        ----------
        val : bool
            Boolean value to enable/disable the option to normalize single quotes
            around strings

        Returns
        -------
        Self
        """
    def normalize_whitespace(self, val: bool) -> JsonReaderOptionsBuilder:
        """
        Sets whether to normalize unquoted whitespace characters

        Parameters
        ----------
        val : bool
            Boolean value to enable/disable the option to normalize unquoted
            whitespace characters

        Returns
        -------
        Self
        """
    def numeric_leading_zeros(self, val: bool) -> JsonReaderOptionsBuilder:
        """
        Set whether leading zeros are allowed in numeric values. Strict validation
        must be enabled for this to work.

        Parameters
        ----------
        val : bool
            Boolean value to indicate whether leading zeros are allowed in numeric
            values

        Returns
        -------
        Self
        """
    def prune_columns(self, val: bool) -> JsonReaderOptionsBuilder:
        """
        Set whether to prune columns on read, selected based on the @ref dtypes option.
        When set as true, if the reader options include @ref dtypes, then
        the reader will only return those columns which are mentioned in @ref dtypes.
        If false, then all columns are returned, independent of the @ref dtypes setting.

        Parameters
        ----------
        val : bool
            Boolean value to enable/disable column pruning

        Returns
        -------
        Self
        """
    def recovery_mode(self, recovery_mode: json_recovery_mode_t) -> JsonReaderOptionsBuilder:
        """
        Specifies the JSON reader's behavior on invalid JSON lines.

        Parameters
        ----------
        recovery_mode : json_recovery_mode_t
            An enum value to indicate the JSON reader's
            behavior on invalid JSON lines.

        Returns
        -------
        Self
        """
    def strict_validation(self, val: bool) -> JsonReaderOptionsBuilder:
        """
        Set whether strict validation is enabled or not

        Parameters
        ----------
        val : bool
            Boolean value to indicate whether strict validation is to be enabled

        Returns
        -------
        Self
        """
    def unquoted_control_chars(self, val: bool) -> JsonReaderOptionsBuilder:
        """
        Set whether in a quoted string should characters greater than or equal to 0
        and less than 32 be allowed without some form of escaping. Strict validation
        must be enabled for this to work.

        Parameters
        ----------
        val : bool
            Boolean value to indicate whether unquoted control chars are allowed

        Returns
        -------
        Self
        """
    def build(self):
        """Create a JsonReaderOptions object"""

class JsonWriterOptions:
    """
    The settings to use for ``write_json``

    For details, see :cpp:class:`cudf::io::json_writer_options`
    """
    @staticmethod
    def builder(sink: SinkInfo, table: Table):
        """
        Create a JsonWriterOptionsBuilder object

        Parameters
        ----------
        sink : SinkInfo
            The sink used for writer output
        table : Table
            Table to be written to output

        Returns
        -------
        JsonWriterOptionsBuilder
            Builder to build JsonWriterOptions
        """
    def set_rows_per_chunk(self, val: size_type) -> None:
        """
        Sets string to used for null entries.

        Parameters
        ----------
        val : size_type
            String to represent null value

        Returns
        -------
        None
        """
    def set_true_value(self, val: str) -> None:
        """
        Sets string used for values != 0

        Parameters
        ----------
        val : str
            String to represent values != 0

        Returns
        -------
        None
        """
    def set_false_value(self, val: str) -> None:
        """
        Sets string used for values == 0

        Parameters
        ----------
        val : str
            String to represent values == 0

        Returns
        -------
        None
        """
    def set_compression(self, comptype: compression_type) -> None:
        """
        Sets compression type to be used

        Parameters
        ----------
        comptype : CompressionType
            Compression type for sink

        Returns
        -------
        None
        """

class JsonWriterOptionsBuilder:
    def metadata(self, tbl_w_meta: TableWithMetadata) -> JsonWriterOptionsBuilder:
        """
        Sets optional metadata (with column names).

        Parameters
        ----------
        tbl_w_meta : TableWithMetadata
            Associated metadata

        Returns
        -------
        Self
        """
    def na_rep(self, val: str) -> JsonWriterOptionsBuilder:
        """
        Sets string to used for null entries.

        Parameters
        ----------
        val : str
            String to represent null value

        Returns
        -------
        Self
        """
    def include_nulls(self, val: bool) -> JsonWriterOptionsBuilder:
        """
        Enables/Disables output of nulls as 'null'.

        Parameters
        ----------
        val : bool
            Boolean value to enable/disable

        Returns
        -------
        Self
        """
    def lines(self, val: bool) -> JsonWriterOptionsBuilder:
        """
        Enables/Disables JSON lines for records format.

        Parameters
        ----------
        val : bool
            Boolean value to enable/disable

        Returns
        -------
        Self
        """
    def compression(self, comptype: compression_type) -> JsonWriterOptionsBuilder:
        """
        Sets compression type of output sink.

        Parameters
        ----------
        comptype : CompressionType
            Compression type used

        Returns
        -------
        Self
        """
    def utf8_escaped(self, val: bool) -> JsonWriterOptionsBuilder:
        """
        Sets whether to write UTF-8 characters in string fields
        without escaping them.

        Parameters
        ----------
        val : bool
            If False, disables escaping of UTF-8 characters in output

        Returns
        -------
        Self
        """
    def build(self) -> JsonWriterOptions:
        """Create a JsonWriterOptions object"""

def _setup_json_reader_options(source_info: SourceInfo, dtypes: list, compression: compression_type=compression_type.AUTO, lines: bool=False, byte_range_offset: int=0, byte_range_size: int=0, keep_quotes: bool=False, mixed_types_as_string: bool=False, prune_columns: bool=False, recovery_mode: json_recovery_mode_t=json_recovery_mode_t.FAIL, extra_parameters: dict | None=None) -> JsonReaderOptions: ...
def chunked_read_json(options: JsonReaderOptions, chunk_size: int=100000000, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> tuple:
    """
    Reads chunks of a JSON file into a :py:class:`~.types.TableWithMetadata`.

    Parameters
    ----------
    options : JsonReaderOptions
        Settings for controlling reading behavior
    chunk_size : int, default 100_000_000 bytes.
        The number of bytes to be read in chunks.
        The chunk_size should be set to at least row_size.
    stream : Stream | None
        CUDA stream used for device memory operations and kernel launches

    Returns
    -------
    tuple
        A tuple of (columns, column_name, child_names)
    """
def read_json(options: JsonReaderOptions, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> TableWithMetadata:
    """
    Read from JSON format.

    The source to read from and options are encapsulated
    by the `options` object.

    For details, see :cpp:func:`read_json`.

    Parameters
    ----------
    options: JsonReaderOptions
        Settings for controlling reading behavior
    stream : Stream | None
        CUDA stream used for device memory operations and kernel launches

    Returns
    -------
    TableWithMetadata
        The Table and its corresponding metadata (column names) that were read in.
    """
def read_json_from_string_column(input: Column, separator: Scalar, narep: Scalar, dtypes: list | None=None, compression: compression_type=compression_type.NONE, recovery_mode: json_recovery_mode_t=json_recovery_mode_t.RECOVER_WITH_NULL, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> TableWithMetadata:
    """
    Joins a column of JSON strings into a device buffer and reads it into
    a table using the JSON reader.

    The source to read from is a string column of JSON records.

    For details, see :cpp:func:`join_strings` and :cpp:func:`read_json`.

    Parameters
    ----------
    input: Column
        String column with json-like strings as rows
    separator: Scalar
        String scalar used to join the input strings
    narep: Scalar
        String scalar used to replace null values during join
    dtypes: List
        Set data types for columns to be read.
    compression: CompressionType
        Set compression type of the string column contents
    recovery_mode: JSONRecoveryMode
        Set recovery option for corrupted JSON input in string column
    stream : Stream | None
        CUDA stream used for device memory operations and kernel launches

    Returns
    -------
    TableWithMetadata
        The Table and its corresponding metadata (column names)
    """
def write_json(options: JsonWriterOptions, stream: CudaStreamLike | None=None) -> None:
    """
    Writes a set of columns to JSON format.

    Parameters
    ----------
    options : JsonWriterOptions
        Settings for controlling writing behavior
    stream: Stream
        CUDA stream used for device memory operations and kernel launches

    Returns
    -------
    None
    """
def is_supported_write_json(type: DataType) -> bool:
    """Check if the dtype is supported for JSON writing

    For details, see :cpp:func:`is_supported_write_json`.
    """
