# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/io/parquet.pyx

from collections.abc import Mapping, Sequence

from pylibcudf.expressions import Expression
from pylibcudf.io.parquet_metadata import FileMetaData
from pylibcudf.io.types import (PartitionInfo, SinkInfo, SourceInfo,
                                TableInputMetadata, TableWithMetadata,
                                compression_type, statistics_freq)
from pylibcudf.libcudf.io.types import dictionary_policy as dictionary_policy_t
from pylibcudf.libcudf.types import size_type, type_id
from pylibcudf.table import Table
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

__all__ = ['ChunkedParquetReader', 'ChunkedParquetWriterOptions', 'ChunkedParquetWriterOptionsBuilder', 'ParquetChunkedWriter', 'ParquetReaderOptions', 'ParquetReaderOptionsBuilder', 'ParquetWriterOptions', 'ParquetWriterOptionsBuilder', 'is_supported_read_parquet', 'is_supported_write_parquet', 'merge_row_group_metadata', 'read_parquet', 'write_parquet']

class ParquetReaderOptions:
    """The settings to use for ``read_parquet``
    For details, see :cpp:class:`cudf::io::parquet_reader_options`
    """
    @staticmethod
    def builder(source: SourceInfo):
        """
        Create a ParquetReaderOptionsBuilder object

        For details, see :cpp:func:`cudf::io::parquet_reader_options::builder`

        Parameters
        ----------
        sink : SourceInfo
            The source to read the Parquet file from.

        Returns
        -------
        ParquetReaderOptionsBuilder
            Builder to build ParquetReaderOptions
        """
    def set_row_groups(self, row_groups: list[list[int]]) -> None:
        """
        Sets list of individual row groups to read.

        Parameters
        ----------
        row_groups : list[list[int]]
            Row groups to read, one inner list per input source.

        Notes
        -----
        Rows are emitted in input-source order; all rows selected from
        source 0 are emitted before rows selected from source 1, and so on.
        Within each source, row groups are read in the order provided;
        indices are not sorted or deduplicated, and repeated indices are
        emitted multiple times. Empty inner lists contribute no rows.
        When unset, all row groups are read in source order, then in
        on-disk order within each source. Predicate pushdown drops row
        groups in place; remaining row groups keep their relative order.

        Returns
        -------
        None
        """
    def set_num_rows(self, nrows: int) -> None:
        """
        Sets number of rows to read.

        Parameters
        ----------
        nrows : int64_t
            Number of rows to read after skip

        Notes
        -----
        Although this allows one to request more than `size_type::max()`
        rows, if any single read would produce a table larger than this row
        limit, an error is thrown.

        Returns
        -------
        None
        """
    def set_skip_rows(self, skip_rows: int) -> None:
        """
        Sets number of rows to skip.

        Parameters
        ----------
        skip_rows : int64_t
            Number of rows to skip from start

        Returns
        -------
        None
        """
    def set_columns(self, col_names: list[str]) -> None:
        """
        Sets names of the columns to be read. Deprecated and will be
        removed in a future version. Use set_column_names instead.

        Parameters
        ----------
        col_names : list
            List of column names

        Returns
        -------
        None
        """
    def set_column_names(self, col_names: list[str]) -> None:
        """
        Sets names of the columns to be read.

        Parameters
        ----------
        col_names : list
            List of column names

        Returns
        -------
        None
        """
    def set_column_indices(self, col_indices: list[int]) -> None:
        """
        Sets indices of the top-level columns to be read.

        Parameters
        ----------
        col_indices : list
            List of top-level column indices

        Returns
        -------
        None
        """
    def set_column_field_ids(self, column_field_ids: list[int]) -> None:
        """
        Sets Parquet field IDs of the columns/fields to be read.

        Parameters
        ----------
        column_field_ids : list
            List of Parquet field IDs

        Returns
        -------
        None
        """
    def set_filter(self, filter: Expression) -> None:
        """
        Sets AST based filter for predicate pushdown.

        Parameters
        ----------
        filter : Expression
            AST expression to use as filter

        Returns
        -------
        None
        """
    def set_source(self, src: SourceInfo) -> None:
        """
        Set a new source info location.

        Parameters
        ----------
        src : SourceInfo
            New source information, replacing existing information.

        Returns
        -------
        None
        """
    def is_enabled_use_jit_filter(self) -> bool:
        """Returns whether to use JIT compilation for filtering."""
    def enable_case_sensitive_names(self, val: bool) -> None:
        """
        Sets whether column names are matched case-sensitively.

        Parameters
        ----------
        val : bool
            Enables case-sensitive matching

        Returns
        -------
        None
        """
    def is_enabled_case_sensitive_names(self) -> bool:
        """
        Returns whether column name matching is case sensitive.

        Returns
        -------
        bool
            Whether column names are matched case-sensitively
        """

class ParquetReaderOptionsBuilder:
    def convert_strings_to_categories(self, val: bool) -> ParquetReaderOptionsBuilder:
        """
        Sets enable/disable conversion of strings to categories.

        Parameters
        ----------
        val : bool
            Boolean value to enable/disable conversion of string columns to categories

        Returns
        -------
        ParquetReaderOptionsBuilder
        """
    def use_pandas_metadata(self, val: bool) -> ParquetReaderOptionsBuilder:
        """
        Sets to enable/disable use of pandas metadata to read.

        Parameters
        ----------
        val : bool
            Boolean value whether to use pandas metadata

        Returns
        -------
        ParquetReaderOptionsBuilder
        """
    def allow_mismatched_pq_schemas(self, val: bool) -> ParquetReaderOptionsBuilder:
        """
        Sets to enable/disable reading of matching projected and filter
        columns from mismatched Parquet sources.

        Parameters
        ----------
        val : bool
            Boolean value whether to read matching projected and filter
            columns from mismatched Parquet sources.

        Returns
        -------
        ParquetReaderOptionsBuilder
        """
    def ignore_missing_columns(self, val: bool) -> ParquetReaderOptionsBuilder:
        """
        Sets to enable/disable ignoring of non-existent projected columns while reading.

        Parameters
        ----------
        val : bool
            Boolean indicating whether to ignore non-existent projected columns
            while reading.

        Returns
        -------
        ParquetReaderOptionsBuilder
        """
    def use_arrow_schema(self, val: bool) -> ParquetReaderOptionsBuilder:
        """
        Sets to enable/disable use of arrow schema to read.

        Parameters
        ----------
        val : bool
            Boolean value whether to use arrow schema

        Returns
        -------
        ParquetReaderOptionsBuilder
        """
    def filter(self, filter: Expression) -> ParquetReaderOptionsBuilder:
        """
        Sets AST based filter for predicate pushdown.

        Parameters
        ----------
        filter : Expression
            AST expression to use as filter

        Returns
        -------
        ParquetReaderOptionsBuilder
        """
    def columns(self, col_names: list[str]) -> ParquetReaderOptionsBuilder:
        """
        Sets names of the columns to be read. Deprecated and will be
        removed in a future version. Use column_names instead.

        Parameters
        ----------
        col_names : list[str]
            List of column names

        Returns
        -------
        ParquetReaderOptionsBuilder
        """
    def column_names(self, col_names: list[str]) -> ParquetReaderOptionsBuilder:
        """
        Sets names of the columns to be read.

        Parameters
        ----------
        col_names : list[str]
            List of column names

        Returns
        -------
        ParquetReaderOptionsBuilder
        """
    def column_indices(self, col_indices: list[int]) -> ParquetReaderOptionsBuilder:
        """
        Sets indices of the top-level columns to be read.

        Parameters
        ----------
        col_indices : list[int]
            List of top-level column indices

        Returns
        -------
        ParquetReaderOptionsBuilder
        """
    def column_field_ids(self, column_field_ids: list[int]) -> ParquetReaderOptionsBuilder:
        """
        Sets Parquet field IDs of the columns/fields to be read.

        Parameters
        ----------
        column_field_ids : list[int]
            List of Parquet field IDs

        Returns
        -------
        ParquetReaderOptionsBuilder
        """
    def use_jit_filter(self, use_jit_filter: bool) -> ParquetReaderOptionsBuilder:
        """
        Sets whether to use JIT compilation for filtering.

        Parameters
        ----------
        use_jit_filter : bool
            Boolean value whether to use JIT filter

        Returns
        -------
        ParquetReaderOptionsBuilder
        """
    def case_sensitive_names(self, val: bool) -> ParquetReaderOptionsBuilder:
        """
        Sets whether column name matching is case sensitive.

        Parameters
        ----------
        val : bool
            ``True`` to enable case-sensitive matching (default),
            ``False`` for case-insensitive matching.

        Returns
        -------
        ParquetReaderOptionsBuilder
        """
    def decimal_width(self, width: type_id) -> ParquetReaderOptionsBuilder:
        """
        Sets the decimal width used to cast all decimal columns.

        Parameters
        ----------
        width : TypeId
            The decimal type_id (DECIMAL32, DECIMAL64, or DECIMAL128) to which
            all decimal columns should be cast.

        Returns
        -------
        ParquetReaderOptionsBuilder
        """
    def build(self):
        """Create a ParquetReaderOptions object"""

class ChunkedParquetReader:
    """
    Reads chunks of a Parquet file into a :py:class:`~.types.TableWithMetadata`.

    For details, see :cpp:class:`chunked_parquet_reader`.

    Parameters
    ----------
    options : ParquetReaderOptions
        Settings for controlling reading behavior
    stream : Stream | None
        CUDA stream used for device memory operations and kernel launches
    mr : DeviceMemoryResource, optional
        Device memory resource used to allocate the returned table's device memory.
    chunk_read_limit : size_t, default 0
        Limit on total number of bytes to be returned per read,
        or 0 if there is no limit.
    pass_read_limit : size_t, default 1024000000
        Limit on the amount of memory used for reading and decompressing data
        or 0 if there is no limit.
    parquet_metadatas : list[FileMetaData], optional
        Pre-materialized parquet footer metadata, one for each source. If not
        provided, footers are read from the sources internally.
    """
    __hash__ = None

    def __init__(self, options: ParquetReaderOptions, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None, chunk_read_limit: int=0, pass_read_limit: int=1024000000, parquet_metadatas: Sequence[FileMetaData] | None=None): ...
    def has_next(self) -> bool:
        """
        Returns True if there is another chunk in the Parquet file
        to be read.

        Returns
        -------
        True if we have not finished reading the file.
        """
    def read_chunk(self, mr: DeviceMemoryResource | None=None) -> TableWithMetadata:
        """
        Read the next chunk into a :py:class:`~.types.TableWithMetadata`

        Parameters
        ----------
        mr : DeviceMemoryResource, optional
            Device memory resource used to allocate the returned table's device memory.

        Returns
        -------
        TableWithMetadata
            The Table and its corresponding metadata (column names) that were read in.
        """

class ChunkedParquetWriter:
    def close(self, metadata_file_path: list) -> memoryview:
        """
        Closes the chunked Parquet writer.

        Parameters
        ----------
        metadata_file_path: list
            Column chunks file path to be set in the raw output metadata

        Returns
        -------
        None
        """
    def write(self, table: Table, partitions_info: object | None=None) -> None:
        """
        Writes table to output.

        Parameters
        ----------
        table: Table
            Table that needs to be written
        partitions_info: object, default None
            Optional partitions to divide the table into.
            If specified, must be same size as number of sinks.

        Returns
        -------
        None
        """
    @staticmethod
    def from_options(options: ChunkedParquetWriterOptions, stream: CudaStreamLike | None=None) -> ChunkedParquetWriter:
        """
        Creates a chunked Parquet writer from options

        Parameters
        ----------
        options: ChunkedParquetWriterOptions
            Settings for controlling writing behavior
        stream : Stream | None
            CUDA stream used for device memory operations and kernel launches

        Returns
        -------
        ChunkedParquetWriter
        """

class ChunkedParquetWriterOptions:
    @staticmethod
    def builder(sink: SinkInfo):
        """
        Create builder to create ChunkedParquetWriterOptions.

        Parameters
        ----------
        sink: SinkInfo
            The sink used for writer output

        Returns
        -------
        ChunkedParquetWriterOptionsBuilder
        """
    def set_dictionary_policy(self, policy: dictionary_policy_t) -> None:
        """
        Sets the policy for dictionary use.

        Parameters
        ----------
        policy : DictionaryPolicy
            Policy for dictionary use

        Returns
        -------
        None
        """

class ChunkedParquetWriterOptionsBuilder:
    def metadata(self, metadata: TableInputMetadata) -> ChunkedParquetWriterOptionsBuilder: ...
    def key_value_metadata(self, metadata: Sequence[Mapping[str, str]]) -> ChunkedParquetWriterOptionsBuilder:
        """
        Sets Key-Value footer metadata.

        Parameters
        ----------
        metadata : list[dict[str, str]]
            Key-Value footer metadata

        Returns
        -------
        Self
        """
    def compression(self, compression: compression_type) -> ChunkedParquetWriterOptionsBuilder:
        """
        Sets compression type.

        Parameters
        ----------
        compression : CompressionType
            The compression type to use

        Returns
        -------
        Self
        """
    def stats_level(self, sf: statistics_freq) -> ChunkedParquetWriterOptionsBuilder:
        """
        Sets the level of statistics.

        Parameters
        ----------
        sf : StatisticsFreq
            Level of statistics requested in the output file

        Returns
        -------
        Self
        """
    def row_group_size_bytes(self, val: int) -> ChunkedParquetWriterOptionsBuilder:
        """
        Sets the maximum row group size, in bytes.

        Parameters
        ----------
        val : size_t
            Maximum row group size, in bytes to set

        Returns
        -------
        Self
        """
    def row_group_size_rows(self, val: size_type) -> ChunkedParquetWriterOptionsBuilder:
        """
        Sets the maximum row group size, in rows.

        Parameters
        ----------
        val : size_type
            Maximum row group size, in rows to set

        Returns
        -------
        Self
        """
    def max_page_size_bytes(self, val: int) -> ChunkedParquetWriterOptionsBuilder:
        """
        Sets the maximum uncompressed page size, in bytes.

        Parameters
        ----------
        val : size_t
            Maximum uncompressed page size, in bytes to set

        Returns
        -------
        Self
        """
    def max_page_size_rows(self, val: size_type) -> ChunkedParquetWriterOptionsBuilder:
        """
        Sets the maximum page size, in rows.

        Parameters
        ----------
        val : size_type
            Maximum page size, in rows to set.

        Returns
        -------
        Self
        """
    def max_dictionary_size(self, val: int) -> ChunkedParquetWriterOptionsBuilder:
        """
        Sets the maximum dictionary size, in bytes.

        Parameters
        ----------
        val : size_t
            Sets the maximum dictionary size, in bytes.

        Returns
        -------
        Self
        """
    def write_arrow_schema(self, enabled: bool) -> ChunkedParquetWriterOptionsBuilder:
        """
        Set to true if arrow schema is to be written.

        Parameters
        ----------
        enabled : bool
            Boolean value to enable/disable writing of arrow schema.

        Returns
        -------
        Self
        """
    def build(self) -> ChunkedParquetWriterOptions:
        """Create a ChunkedParquetWriterOptions object"""

class ParquetWriterOptions:
    @staticmethod
    def builder(sink: SinkInfo, table: Table):
        """
        Create builder to create ParquetWriterOptionsBuilder.

        Parameters
        ----------
        sink : SinkInfo
            The sink used for writer output

        table : Table
            Table to be written to output

        Returns
        -------
        ParquetWriterOptionsBuilder
        """
    def set_partitions(self, partitions: list[PartitionInfo]) -> None:
        """
        Sets partitions.

        Parameters
        ----------
        partitions : list[Partitions]
            Partitions of input table in {start_row, num_rows} pairs.

        Returns
        -------
        None
        """
    def set_column_chunks_file_paths(self, file_paths: Sequence[str]) -> None:
        """
        Sets column chunks file path to be set in the raw output metadata.

        Parameters
        ----------
        file_paths : list[str]
            Vector of strings which indicate file paths.

        Returns
        -------
        None
        """
    def set_row_group_size_bytes(self, size_bytes: int) -> None:
        """
        Sets the maximum row group size, in bytes.

        Parameters
        ----------
        size_bytes : int
            Maximum row group size, in bytes to set

        Returns
        -------
        None
        """
    def set_row_group_size_rows(self, size_rows: size_type) -> None:
        """
        Sets the maximum row group size, in rows.

        Parameters
        ----------
        size_rows : int
            Maximum row group size, in rows to set

        Returns
        -------
        None
        """
    def set_max_page_size_bytes(self, size_bytes: int) -> None:
        """
        Sets the maximum uncompressed page size, in bytes.

        Parameters
        ----------
        size_bytes : int
            Maximum uncompressed page size, in bytes to set

        Returns
        -------
        None
        """
    def set_max_page_size_rows(self, size_rows: size_type) -> None:
        """
        Sets the maximum page size, in rows.

        Parameters
        ----------
        size_rows : int
            Maximum page size, in rows to set.

        Returns
        -------
        None
        """
    def set_max_dictionary_size(self, size_bytes: int) -> None:
        """
        Sets the maximum dictionary size, in bytes.

        Parameters
        ----------
        size_bytes : int
            Sets the maximum dictionary size, in bytes.

        Returns
        -------
        None
        """

class ParquetWriterOptionsBuilder:
    def metadata(self, metadata: TableInputMetadata) -> ParquetWriterOptionsBuilder:
        """
        Sets metadata.

        Parameters
        ----------
        metadata : TableInputMetadata
            Associated metadata

        Returns
        -------
        Self
        """
    def key_value_metadata(self, metadata: Sequence[Mapping[str, str]]) -> ParquetWriterOptionsBuilder:
        """
        Sets Key-Value footer metadata.

        Parameters
        ----------
        metadata : list[dict[str, str]]
            Key-Value footer metadata

        Returns
        -------
        Self
        """
    def compression(self, compression: compression_type) -> ParquetWriterOptionsBuilder:
        """
        Sets compression type.

        Parameters
        ----------
        compression : CompressionType
            The compression type to use

        Returns
        -------
        Self
        """
    def stats_level(self, sf: statistics_freq) -> ParquetWriterOptionsBuilder:
        """
        Sets the level of statistics.

        Parameters
        ----------
        sf : StatisticsFreq
            Level of statistics requested in the output file

        Returns
        -------
        Self
        """
    def int96_timestamps(self, enabled: bool) -> ParquetWriterOptionsBuilder:
        """
        Sets whether timestamps are written as int96 or timestamp micros.

        Parameters
        ----------
        enabled : bool
            Boolean value to enable/disable int96 timestamps

        Returns
        -------
        Self
        """
    def write_v2_headers(self, enabled: bool) -> ParquetWriterOptionsBuilder:
        """
        Set to true to write V2 page headers, otherwise false to write V1 page headers.

        Parameters
        ----------
        enabled : bool
            Boolean value to enable/disable writing of V2 page headers.

        Returns
        -------
        Self
        """
    def page_level_compression(self, enabled: bool) -> ParquetWriterOptionsBuilder:
        """
        Set to true to enable per-page compression decisions for V2 data pages.

        When enabled, each V2 data page independently decides whether to compress
        based on compression ratio. When disabled (default), all V2 data pages
        in a chunk follow the same compression decision as dictionary pages.

        Parameters
        ----------
        enabled : bool
            Boolean value to enable/disable per-page compression decisions.

        Returns
        -------
        Self
        """
    def dictionary_policy(self, val: dictionary_policy_t) -> ParquetWriterOptionsBuilder:
        """
        Sets the policy for dictionary use.

        Parameters
        ----------
        val : DictionaryPolicy
            Policy for dictionary use.

        Returns
        -------
        Self
        """
    def utc_timestamps(self, enabled: bool) -> ParquetWriterOptionsBuilder:
        """
        Set to true if timestamps are to be written as UTC.

        Parameters
        ----------
        enabled : bool
            Boolean value to enable/disable writing of timestamps as UTC.

        Returns
        -------
        Self
        """
    def write_arrow_schema(self, enabled: bool) -> ParquetWriterOptionsBuilder:
        """
        Set to true if arrow schema is to be written.

        Parameters
        ----------
        enabled : bool
            Boolean value to enable/disable writing of arrow schema.

        Returns
        -------
        Self
        """
    def row_group_size_rows(self, val: size_type) -> ParquetWriterOptionsBuilder:
        """
        Sets the maximum row group size, in rows.

        Parameters
        ----------
        val : size_type
            Maximum row group size, in rows to set

        Returns
        -------
        Self
        """
    def max_page_size_bytes(self, val: int) -> ParquetWriterOptionsBuilder:
        """
        Sets the maximum uncompressed page size, in bytes.

        Parameters
        ----------
        val : size_t
            Maximum uncompressed page size, in bytes to set

        Returns
        -------
        Self
        """
    def build(self) -> ParquetWriterOptions:
        """
        Create a ParquetWriterOptions from the set options.

        Returns
        -------
        ParquetWriterOptions
        """

def _warn_deprecated(api_name, new_api): ...
def read_parquet(options: ParquetReaderOptions, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None, parquet_metadatas: Sequence[FileMetaData] | None=None) -> TableWithMetadata:
    """
    Read from Parquet format.

    The source to read from and options are encapsulated
    by the `options` object.

    For details, see :cpp:func:`read_parquet`.

    Parameters
    ----------
    options: ParquetReaderOptions
        Settings for controlling reading behavior
    stream : Stream | None
        CUDA stream used for device memory operations and kernel launches
    mr : DeviceMemoryResource, optional
        Device memory resource used to allocate the returned table's device memory.
    parquet_metadatas : list[FileMetaData], optional
        Pre-materialized parquet footer metadata, one for each source. If not
        provided, footers are read from the sources internally.
    """
def write_parquet(options: ParquetWriterOptions, stream: CudaStreamLike | None=None) -> memoryview:
    """
    Writes a set of columns to parquet format.

    Parameters
    ----------
    options : ParquetWriterOptions
        Settings for controlling writing behavior
    stream : Stream | None
        CUDA stream used for device memory operations and kernel launches

    Returns
    -------
    memoryview
        A blob that contains the file metadata
        (parquet FileMetadata thrift message) if requested in
        parquet_writer_options (empty blob otherwise).
    """
def is_supported_read_parquet(compression: compression_type) -> bool:
    """Check if the compression type is supported for reading Parquet files.

    For details, see :cpp:func:`is_supported_read_parquet`.

    Parameters
    ----------
    compression : CompressionType
        The compression type to check

    Returns
    -------
    bool
        True if the compression type is supported for reading Parquet files
    """
def is_supported_write_parquet(compression: compression_type) -> bool:
    """Check if the compression type is supported for writing Parquet files.

    For details, see :cpp:func:`is_supported_write_parquet`.

    Parameters
    ----------
    compression : CompressionType
        The compression type to check

    Returns
    -------
    bool
        True if the compression type is supported for writing Parquet files
    """
def merge_row_group_metadata(metdata_list: list) -> memoryview:
    """
    Merges multiple raw metadata blobs that were previously
    created by write_parquet into a single metadata blob.

    For details, see :cpp:func:`merge_row_group_metadata`.

    Parameters
    ----------
    metdata_list : list
        List of input file metadata

    Returns
    -------
    memoryview
        A parquet-compatible blob that contains the data for all row groups in the list
    """
