# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/io/text.pyx

from pylibcudf.column import Column
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

__all__ = ['ByteRangeInfo', 'DataChunkSource', 'ParseOptions', 'make_source', 'make_source_from_bgzip_file', 'make_source_from_file', 'multibyte_split']

class ByteRangeInfo:
    """Information about a byte range in a file.

    For details, see :cpp:class:`cudf::io::text::byte_range_info`

    Parameters
    ----------
    offset : int
        Offset in bytes from the start of the file
    size : int
        Size of the range in bytes
    """
    def __init__(self, offset: int, size: int): ...
    @property
    def offset(self):
        """Get the offset in bytes."""
    @property
    def size(self):
        """Get the size in bytes."""

class ParseOptions:
    """
    Parsing options for `multibyte_split`

    Parameters
    ----------
    byte_range : list | tuple, default None
        Only rows starting inside this byte range will be
        part of the output column.

    strip_delimiters : bool, default True
        Whether delimiters at the end of rows should
        be stripped from the output column.
    """
    def __init__(self, *, byte_range: tuple[int, int] | list[int] | None=None, strip_delimiters=False): ...

class DataChunkSource:
    """
    Data source for `multibyte_split`

    Parameters
    ----------
    data : str
        Filename or data itself.
    """
    def __init__(self, data: str): ...

def make_source(data: str) -> DataChunkSource:
    """
    Creates a data source capable of producing device-buffered views
    of the given string.

    Parameters
    ----------
    data : str
        The host data to be exposed as a data chunk source.

    Returns
    -------
    DataChunkSource
        The data chunk source for the provided host data.
    """
def make_source_from_file(filename: str) -> DataChunkSource:
    """
    Creates a data source capable of producing device-buffered views of the file.

    Parameters
    ----------
    filename : str
        The filename of the file to be exposed as a data chunk source.

    Returns
    -------
    DataChunkSource
        The data chunk source for the provided filename.
    """
def make_source_from_bgzip_file(filename: str, virtual_begin: int=-1, virtual_end: int=-1) -> DataChunkSource:
    """
    Creates a data source capable of producing device-buffered views of
    a BGZIP compressed file with virtual record offsets.

    Parameters
    ----------
    filename : str
        The filename of the BGZIP-compressed file to be exposed as a data chunk source.

    virtual_begin : int
        The virtual (Tabix) offset of the first byte to be read. Its upper 48 bits
        describe the offset into the compressed file, its lower 16 bits describe the
        block-local offset.

    virtual_end : int, default None
        The virtual (Tabix) offset one past the last byte to be read

    Returns
    -------
    DataChunkSource
        The data chunk source for the provided filename.
    """
def multibyte_split(source: DataChunkSource, delimiter: str, options: ParseOptions | None=None, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """
    Splits the source text into a strings column using a multiple byte delimiter.

    For details, see :cpp:func:`multibyte_split`

    Parameters
    ----------
    source :
        The source string.

    delimiter : str
        UTF-8 encoded string for which to find offsets in the source.

    options : ParseOptions
        The parsing options to use (including byte range).

    stream : Stream, optional
        CUDA stream for device memory operations and kernel launches

    Returns
    -------
    Column
        The strings found by splitting the source by the delimiter
        within the relevant byte range.
    """
