# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/strings/split/partition.pyx

from pylibcudf.column import Column
from pylibcudf.scalar import Scalar
from pylibcudf.table import Table
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

__all__ = ['partition', 'rpartition']

def partition(input: Column, delimiter: Scalar | None=None, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Table:
    """
    Returns a set of 3 columns by splitting each string using the
    specified delimiter.

    For details, see :cpp:func:`partition`.

    Parameters
    ----------
    input : Column
        Strings instance for this operation

    delimiter : Scalar
        UTF-8 encoded string indicating where to split each string.

    Returns
    -------
    Table
        New table of strings columns
    """
def rpartition(input: Column, delimiter: Scalar | None=None, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Table:
    """
    Returns a set of 3 columns by splitting each string using the
    specified delimiter starting from the end of each string.

    For details, see :cpp:func:`rpartition`.

    Parameters
    ----------
    input : Column
        Strings instance for this operation

    delimiter : Scalar
        UTF-8 encoded string indicating where to split each string.

    Returns
    -------
    Table
       New strings columns
    """
