# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/strings/split/split.pyx

from pylibcudf.column import Column
from pylibcudf.libcudf.types import size_type
from pylibcudf.scalar import Scalar
from pylibcudf.strings.regex_program import RegexProgram
from pylibcudf.table import Table
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

__all__ = ['rsplit', 'rsplit_re', 'rsplit_record', 'rsplit_record_re', 'split', 'split_re', 'split_record', 'split_record_re']

def split(strings_column: Column, delimiter: Scalar, maxsplit: size_type, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Table:
    """
    Returns a list of columns by splitting each string using the
    specified delimiter.

    For details, see :cpp:func:`split`.

    Parameters
    ----------
    strings_column : Column
        Strings instance for this operation

    delimiter : Scalar
        UTF-8 encoded string indicating the split points in each string.

    maxsplit : int
        Maximum number of splits to perform. -1 indicates all possible
        splits on each string.

    stream : Stream | None
        CUDA stream on which to perform the operation.

    Returns
    -------
    Table
        New table of strings columns
    """
def rsplit(strings_column: Column, delimiter: Scalar, maxsplit: size_type, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Table:
    """
    Returns a list of columns by splitting each string using the
    specified delimiter starting from the end of each string.

    For details, see :cpp:func:`rsplit`.

    Parameters
    ----------
    strings_column : Column
        Strings instance for this operation

    delimiter : Scalar
        UTF-8 encoded string indicating the split points in each string.

    maxsplit : int
        Maximum number of splits to perform. -1 indicates all possible
        splits on each string.

    stream : Stream | None
        CUDA stream on which to perform the operation.

    Returns
    -------
    Table
        New table of strings columns.
    """
def split_record(strings: Column, delimiter: Scalar, maxsplit: size_type, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """
    Splits individual strings elements into a list of strings.

    For details, see :cpp:func:`split_record`.

    Parameters
    ----------
    strings : Column
        A column of string elements to be split.

    delimiter : Scalar
        The string to identify split points in each string.

    maxsplit : int
        Maximum number of splits to perform. -1 indicates all possible
        splits on each string.

    Returns
    -------
    Column
        Lists column of strings.
    """
def rsplit_record(strings: Column, delimiter: Scalar, maxsplit: size_type, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """
    Splits individual strings elements into a list of strings starting
    from the end of each string.

    For details, see :cpp:func:`rsplit_record`.

    Parameters
    ----------
    strings : Column
        A column of string elements to be split.

    delimiter : Scalar
        The string to identify split points in each string.

    maxsplit : int
        Maximum number of splits to perform. -1 indicates all possible
        splits on each string.

    Returns
    -------
    Column
        Lists column of strings.
    """
def split_re(input: Column, prog: RegexProgram, maxsplit: size_type, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Table:
    """
    Splits strings elements into a table of strings columns
    using a regex_program's pattern to delimit each string.

    For details, see :cpp:func:`split_re`.

    Parameters
    ----------
    input : Column
        A column of string elements to be split.

    prog : RegexProgram
        Regex program instance.

    maxsplit : int
        Maximum number of splits to perform. -1 indicates all possible
        splits on each string.

    Returns
    -------
    Table
        A table of columns of strings.
    """
def rsplit_re(input: Column, prog: RegexProgram, maxsplit: size_type, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Table:
    """
    Splits strings elements into a table of strings columns
    using a regex_program's pattern to delimit each string starting from
    the end of the string.

    For details, see :cpp:func:`rsplit_re`.

    Parameters
    ----------
    input : Column
        A column of string elements to be split.

    prog : RegexProgram
        Regex program instance.

    maxsplit : int
        Maximum number of splits to perform. -1 indicates all possible
        splits on each string.

    Returns
    -------
    Table
        A table of columns of strings.
    """
def split_record_re(input: Column, prog: RegexProgram, maxsplit: size_type, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """
    Splits strings elements into a list column of strings using the given
    regex_program to delimit each string.

    For details, see :cpp:func:`split_record_re`.

    Parameters
    ----------
    input : Column
        A column of string elements to be split.

    prog : RegexProgram
        Regex program instance.

    maxsplit : int
        Maximum number of splits to perform. -1 indicates all possible
        splits on each string.

    Returns
    -------
    Column
        Lists column of strings.
    """
def rsplit_record_re(input: Column, prog: RegexProgram, maxsplit: size_type, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """
    Splits strings elements into a list column of strings using the given
    regex_program to delimit each string starting from the end of the string.

    For details, see :cpp:func:`rsplit_record_re`.

    Parameters
    ----------
    input : Column
        A column of string elements to be split.

    prog : RegexProgram
        Regex program instance.

    maxsplit : int
        Maximum number of splits to perform. -1 indicates all possible
        splits on each string.

    Returns
    -------
    Column
        Lists column of strings.
    """
def split_part(input: Column, delimiter: Scalar, index: size_type, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column: ...
