# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/strings/combine.pyx

from pylibcudf.column import Column
from pylibcudf.libcudf.strings.combine import output_if_empty_list
from pylibcudf.libcudf.strings.combine import \
    output_if_empty_list as OutputIfEmptyList
from pylibcudf.libcudf.strings.combine import separator_on_nulls
from pylibcudf.libcudf.strings.combine import \
    separator_on_nulls as SeparatorOnNulls
from pylibcudf.scalar import Scalar
from pylibcudf.table import Table
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

__all__ = ['OutputIfEmptyList', 'SeparatorOnNulls', 'concatenate', 'join_list_elements', 'join_strings']

def concatenate(strings_columns: Table, separator: Column | Scalar, narep: Scalar | None=None, col_narep: Scalar | None=None, separate_nulls: separator_on_nulls=separator_on_nulls.YES, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """
    Concatenate all columns in the table horizontally into one new string
    delimited by an optional separator string.

    Parameters
    ----------
    strings_columns : Table
        Strings for this operation

    separator : Column or Scalar
        Separator(s) for a given row

    narep : Scalar
        String to replace a null separator for a given row.

    col_narep : Scalar
        String that should be used in place of any null strings found in any column.
        An exception is raised when separator is a Scalar.

    separate_nulls : SeparatorOnNulls
        If YES, then the separator is included for null rows.

    Returns
    -------
    Column
        New column with concatenated results
    """
def join_strings(input: Column, separator: Scalar, narep: Scalar, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """
    Concatenates all strings in the column into one new string delimited
    by an optional separator string.

    Parameters
    ----------
    input : Column
        List of strings columns to concatenate

    separator : Scalar
        Strings column that provides the separator for a given row

    narep : Scalar
        String to replace any null strings found.

    Returns
    -------
    Column
        New column containing one string
    """
def join_list_elements(lists_strings_column: Column, separator: Column | Scalar, separator_narep: Scalar, string_narep: Scalar, separate_nulls: separator_on_nulls, empty_list_policy: output_if_empty_list, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """
    Given a lists column of strings (each row is a list of strings),
    concatenates the strings within each row and returns a single strings
    column result.

    Parameters
    ----------
    lists_strings_column : Column
        Column containing lists of strings to concatenate

    separator : Column or Scalar
        String(s) that should inserted between each string from each row.

    separator_narep : Scalar
        String that should be used to replace a null separator.

    string_narep : Scalar
        String to replace null strings in any non-null list row.
        Ignored if separator is a Scalar.

    separate_nulls : SeparatorOnNulls
        If YES, then the separator is included for null rows
        if `narep` is valid

    empty_list_policy : OutputIfEmptyList
        If set to EMPTY_STRING, any input row that is an empty
        list will result in an empty string. Otherwise, it will
        result in a null.


    Returns
    -------
    Column
        New strings column with concatenated results
    """
