# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/strings/contains.pyx

from pylibcudf.column import Column
from pylibcudf.strings.regex_program import RegexProgram
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

__all__ = ['contains_re', 'count_re', 'like', 'matches_re']

def contains_re(input: Column, prog: RegexProgram, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """Returns a boolean column identifying rows which match the given
    regex_program object.

    For details, see :cpp:func:`contains_re`.

    Parameters
    ----------
    input : Column
        The input strings
    prog : RegexProgram
        Regex program instance

    Returns
    -------
    pylibcudf.Column
        New column of boolean results for each string
    """
def count_re(input: Column, prog: RegexProgram, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """Returns the number of times the given regex_program's pattern
    matches in each string.

    For details, see :cpp:func:`count_re`.

    Parameters
    ----------
    input : Column
        The input strings
    prog : RegexProgram
        Regex program instance

    Returns
    -------
    pylibcudf.Column
        New column of match counts for each string
    """
def matches_re(input: Column, prog: RegexProgram, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """Returns a boolean column identifying rows which
    matching the given regex_program object but only at
    the beginning the string.

    For details, see :cpp:func:`matches_re`.

    Parameters
    ----------
    input : Column
        The input strings
    prog : RegexProgram
        Regex program instance

    Returns
    -------
    pylibcudf.Column
        New column of boolean results for each string
    """
def like(input: Column, pattern: str, escape_character: str | None=None, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """
    Returns a boolean column identifying rows which
    match the given like pattern.

    For details, see :cpp:func:`like`.

    Parameters
    ----------
    input : Column
        The input strings
    pattern : str
        Like pattern to match within each string
    escape_character : str
        Optional character specifies the escape prefix.
        Default is no escape character.

    Returns
    -------
    pylibcudf.Column
        New column of boolean results for each string
    """
