# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/strings/findall.pyx

from pylibcudf.column import Column
from pylibcudf.strings.regex_program import RegexProgram
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

__all__ = ['findall', 'find_re']

def findall(input: Column, pattern: RegexProgram, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """
    Returns a lists column of strings for each matching occurrence using
    the regex_program pattern within each string.

    For details, see :cpp:func:`findall`.

    Parameters
    ----------
    input : Column
        Strings instance for this operation
    pattern : RegexProgram
        Regex pattern
    stream : Stream | None
        CUDA stream on which to perform the operation.

    Returns
    -------
    Column
        New lists column of strings
    """
def find_re(input: Column, pattern: RegexProgram, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """
    Returns character positions where the pattern first matches
    the elements in input strings.

    For details, see :cpp:func:`find_re`

    Parameters
    ----------
    input : Column
        Strings instance for this operation
    pattern : RegexProgram
        Regex pattern
    stream : Stream | None
        CUDA stream on which to perform the operation.

    Returns
    -------
    Column
        New column of integers
    """
