# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/strings/padding.pyx

from pylibcudf.column import Column
from pylibcudf.libcudf.strings.side_type import side_type
from pylibcudf.libcudf.types import size_type
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

__all__ = ['pad', 'zfill', 'zfill_by_widths']

def pad(input: Column, width: size_type, side: side_type, fill_char: str, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """
    Add padding to each string using a provided character.

    For details, see :cpp:func:`pad`.

    Parameters
    ----------
    input : Column
        Strings instance for this operation
    width : int
        The minimum number of characters for each string.
    side : SideType
        Where to place the padding characters.
    fill_char : str
        Single UTF-8 character to use for padding
    stream : Stream | None
        CUDA stream on which to perform the operation.

    Returns
    -------
    Column
        New column with padded strings.
    """
def zfill(input: Column, width: size_type, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """
    Add '0' as padding to the left of each string.

    For details, see :cpp:func:`zfill`.

    Parameters
    ----------
    input : Column
        Strings instance for this operation
    width : int
        The minimum number of characters for each string.
    stream : Stream | None
        CUDA stream on which to perform the operation.

    Returns
    -------
    Column
        New column of strings.
    """
def zfill_by_widths(input: Column, widths: Column, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """
    Add '0' as padding to the left of each string.

    For details, see :cpp:func:`zfill_by_widths`.

    Parameters
    ----------
    input : Column
        Strings instance for this operation
    widths : Column
        The minimum number of characters for each string.
    stream : Stream | None
        CUDA stream on which to perform the operation.

    Returns
    -------
    Column
        New column of strings.
    """
