# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/strings/regex_program.pyx

from pylibcudf.libcudf.strings.regex_flags import regex_flags

__all__ = ['RegexProgram']

class RegexProgram:
    """Regex program class.

    This is the Cython representation of
    :cpp:class:`cudf::strings::regex_program`.

    Do not instantiate this class directly, use the `create` method.

    """
    __hash__ = None

    def __init__(self, *args, **kwargs): ...
    @staticmethod
    def create(pattern: str, flags: regex_flags):
        """Create a program from a pattern.

        For detils, see :cpp:func:`create`.

        Parameters
        ----------
        pattern : str
            Regex pattern
        flags : RegexFlags
            Regex flags for interpreting special characters in the pattern

        Returns
        -------
        RegexProgram
            A new RegexProgram
        """
