# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/strings/replace.pyx

from pylibcudf.column import Column
from pylibcudf.libcudf.types import size_type
from pylibcudf.scalar import Scalar
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

__all__ = ['replace', 'replace_multiple', 'replace_slice']

def replace(input: Column, target: Scalar, repl: Scalar, maxrepl: size_type=-1, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """Replaces target string within each string with the specified replacement string.

    Null string entries will return null output string entries.

    For details, see :cpp:func:`replace`.

    Parameters
    ----------
    input : Column
        The input strings
    target : Scalar
        String to search for in each string.
    repl : Scalar
        String to replace target with.
    maxrepl : size_type, default -1
        Maximum times to replace if target appears multiple times in the input string.
        Default of -1 specifies to replace all occurrences of target in each string.

    Returns
    -------
    pylibcudf.Column
        New string column with target replaced.
    """
def replace_multiple(input: Column, target: Column, repl: Column, maxrepl: size_type=-1, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """Replaces target string within each string with the specified replacement string.

    Null string entries will return null output string entries.

    For details, see :cpp:func:`replace_multiple`.

    Parameters
    ----------
    input : Column
        The input strings
    target : Column
        Column containing strings to search for in the input column.
    repl : Column
        Column containing strings to replace target with.
        Each target, when found, will be replaced by the value at the
        corresponding index in the repl Column.

        Must be of the same length as target.

    Returns
    -------
    pylibcudf.Column
        New string column with target replaced.
    """
def replace_slice(input: Column, repl: Scalar | None=None, start: size_type=0, stop: size_type=-1, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """Replaces each string in the column with the provided repl string
    within the [start,stop) character position range.

    Null string entries will return null output string entries.
    This function can be used to insert a string into specific position
    by specifying the same position value for start and stop.
    The repl string can be appended to each string by specifying -1
    for both start and stop.

    For details, see :cpp:func:`replace_slice`.

    Parameters
    ----------
    input : Column
        The input strings
    repl : Scalar, default ""
        String scalar to replace target with.
    start : size_type, default 0
        Start position where repl will be added.
    stop : size_type, default -1
        End position (exclusive) to use for replacement.

    Returns
    -------
    pylibcudf.Column
        New string column
    """
