# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/strings/translate.pyx

from pylibcudf.column import Column
from pylibcudf.libcudf.strings.translate import filter_type
from pylibcudf.libcudf.strings.translate import filter_type as FilterType
from pylibcudf.scalar import Scalar
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

__all__ = ['FilterType', 'filter_characters', 'translate']

def translate(input: Column, chars_table: dict[int | str, int | str], stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """
    Translates individual characters within each string.

    For details, see :cpp:func:`translate`.

    Parameters
    ----------
    input : Column
        Strings instance for this operation

    chars_table : dict
        Table of UTF-8 character mappings
    stream : Stream | None
        CUDA stream on which to perform the operation.

    Returns
    -------
    Column
        New column with padded strings.
    """
def filter_characters(input: Column, characters_to_filter: dict[int | str, int | str], keep_characters: filter_type, replacement: Scalar, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """
    Removes ranges of characters from each string in a strings column.

    For details, see :cpp:func:`filter_characters`.

    Parameters
    ----------
    input : Column
        Strings instance for this operation

    characters_to_filter : dict
        Table of character ranges to filter on

    keep_characters : FilterType
        If true, the `characters_to_filter` are retained
        and all other characters are removed.

    replacement : Scalar
        Replacement string for each character removed.
    stream : Stream | None
        CUDA stream on which to perform the operation.

    Returns
    -------
    Column
        New column with filtered strings.
    """
