# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/nvtext/byte_pair_encode.pyx

from pylibcudf.column import Column
from pylibcudf.scalar import Scalar
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

__all__ = ['BPEMergePairs', 'byte_pair_encoding']

class BPEMergePairs:
    """The table of merge pairs for the BPE encoder.

    For details, see :cpp:class:`cudf::nvtext::bpe_merge_pairs`.
    """
    __hash__ = None

    def __init__(self, merge_pairs: Column, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None): ...

def byte_pair_encoding(input: Column, merge_pairs: BPEMergePairs, separator: Scalar | None=None, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """
    Byte pair encode the input strings.

    For details, see cpp:func:`cudf::nvtext::byte_pair_encoding`

    Parameters
    ----------
    input : Column
        Strings to encode.
    merge_pairs : BPEMergePairs
       Substrings to rebuild each string on.
    separator : Scalar
        String used to build the output after encoding. Default is a space.
    stream : Stream | None
        CUDA stream on which to perform the operation.

    Returns
    -------
    Column
        An encoded column of strings.
    """
