# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/nvtext/edit_distance.pyx

from pylibcudf.column import Column
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

__all__ = ['edit_distance']

def edit_distance(input: Column, targets: Column, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """
    Returns the edit distance between individual strings in two strings columns

    For details, see :cpp:func:`edit_distance`

    Parameters
    ----------
    input : Column
        Input strings
    targets : Column
        Strings to compute edit distance against
    stream : Stream | None
        CUDA stream on which to perform the operation.

    Returns
    -------
    Column
        New column of edit distance values
    """
