# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/nvtext/generate_ngrams.pyx

from pylibcudf.column import Column
from pylibcudf.libcudf.types import size_type
from pylibcudf.scalar import Scalar
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

__all__ = ['generate_ngrams', 'generate_character_ngrams', 'hash_character_ngrams']

def generate_ngrams(input: Column, ngrams: size_type, separator: Scalar, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """
    Returns a single column of strings by generating ngrams from a strings column.

    For details, see :cpp:func:`generate_ngrams`

    Parameters
    ----------
    input : Column
        Input strings
    ngram : size_type
        The ngram number to generate
    separator : Scalar
        The string to use for separating ngram tokens
    stream : Stream | None
        CUDA stream on which to perform the operation.

    Returns
    -------
    Column
        New strings columns of tokens
    """
def generate_character_ngrams(input: Column, ngrams: size_type=2, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """
    Returns a lists column of ngrams of characters within each string.

    For details, see :cpp:func:`generate_character_ngrams`

    Parameters
    ----------
    input : Column
        Input strings
    ngram : size_type
        The ngram number to generate
    stream : Stream | None
        CUDA stream on which to perform the operation.

    Returns
    -------
    Column
        Lists column of strings
    """
def hash_character_ngrams(input: Column, ngrams: size_type, seed: int, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """
    Returns a lists column of hash values of the characters in each string

    For details, see :cpp:func:`hash_character_ngrams`

    Parameters
    ----------
    input : Column
        Input strings
    ngram : size_type
        The ngram number to generate
    seed : uint32_t
        Seed used for the hash algorithm
    stream : Stream | None
        CUDA stream on which to perform the operation.

    Returns
    -------
    Column
        Lists column of hash values
    """
