# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/nvtext/minhash.pyx

from pylibcudf.column import Column
from pylibcudf.libcudf.types import size_type
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

__all__ = ['minhash', 'minhash64', 'minhash_ngrams', 'minhash64_ngrams']

def minhash(input: Column, seed: int, a: Column, b: Column, width: size_type, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """
    Returns the minhash values for each string.
    This function uses MurmurHash3_x86_32 for the hash algorithm.

    For details, see :cpp:func:`minhash`.

    Parameters
    ----------
    input : Column
        Strings column to compute minhash
    seed : uint32_t
        Seed used for the hash function
    a : Column
        1st parameter value used for the minhash algorithm.
    b : Column
        2nd parameter value used for the minhash algorithm.
    width : size_type
        Character width used for apply substrings;

    Returns
    -------
    Column
        List column of minhash values for each string per seed
    """
def minhash64(input: Column, seed: int, a: Column, b: Column, width: size_type, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """
    Returns the minhash values for each string.
    This function uses MurmurHash3_x64_128 for the hash algorithm.

    For details, see :cpp:func:`minhash64`.

    Parameters
    ----------
    input : Column
        Strings column to compute minhash
    seed : uint64_t
        Seed used for the hash function
    a : Column
        1st parameter value used for the minhash algorithm.
    b : Column
        2nd parameter value used for the minhash algorithm.
    width : size_type
        Character width used for apply substrings;
    stream : Stream | None
        CUDA stream on which to perform the operation.

    Returns
    -------
    Column
        List column of minhash values for each string per seed
    """
def minhash_ngrams(input: Column, ngrams: size_type, seed: int, a: Column, b: Column, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """
    Returns the minhash values for each input row of strings.
    This function uses MurmurHash3_x86_32 for the hash algorithm.

    For details, see :cpp:func:`minhash_ngrams`.

    Parameters
    ----------
    input : Column
        List column of strings to compute minhash
    ngrams : size_type
        Number of consecutive strings to hash in each row
    seed : uint32_t
        Seed used for the hash function
    a : Column
        1st parameter value used for the minhash algorithm.
    b : Column
        2nd parameter value used for the minhash algorithm.
    stream : Stream | None
        CUDA stream on which to perform the operation.

    Returns
    -------
    Column
        List column of minhash values for each row per
        value in columns a and b.
    """
def minhash64_ngrams(input: Column, ngrams: size_type, seed: int, a: Column, b: Column, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """
    Returns the minhash values for each input row of strings.
    This function uses MurmurHash3_x64_128 for the hash algorithm.

    For details, see :cpp:func:`minhash64_ngrams`.

    Parameters
    ----------
    input : Column
        Strings column to compute minhash
    ngrams : size_type
        Number of consecutive strings to hash in each row
    seed : uint64_t
        Seed used for the hash function
    a : Column
        1st parameter value used for the minhash algorithm.
    b : Column
        2nd parameter value used for the minhash algorithm.
    stream : Stream | None
        CUDA stream on which to perform the operation.

    Returns
    -------
    Column
        List column of minhash values for each row per
        value in columns a and b.
    """
