# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/nvtext/tokenize.pyx

from pylibcudf.column import Column
from pylibcudf.libcudf.types import size_type
from pylibcudf.scalar import Scalar
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

__all__ = ['TokenizeVocabulary', 'character_tokenize', 'count_tokens_column', 'count_tokens_scalar', 'detokenize', 'tokenize_column', 'tokenize_scalar', 'tokenize_with_vocabulary']

class TokenizeVocabulary:
    """The Vocabulary object to be used with ``tokenize_with_vocabulary``.

    For details, see :cpp:class:`cudf::nvtext::tokenize_vocabulary`.
    """
    __hash__ = None

    def __init__(self, vocab: Column, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None): ...

def tokenize_scalar(input: Column, delimiter: Scalar | None=None, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """
    Returns a single column of strings by tokenizing the input
    strings column using the provided characters as delimiters.

    For details, see cpp:func:`cudf::nvtext::tokenize`

    Parameters
    ----------
    input : Column
        Strings column to tokenize
    delimiter : Scalar
        String scalar used to separate individual strings into tokens
    stream : Stream | None
        CUDA stream on which to perform the operation.

    Returns
    -------
    Column
        New strings columns of tokens
    """
def tokenize_column(input: Column, delimiters: Column, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """
    Returns a single column of strings by tokenizing the input
    strings column using multiple strings as delimiters.

    For details, see cpp:func:`cudf::nvtext::tokenize`

    Parameters
    ----------
    input : Column
        Strings column to tokenize
    delimiters : Column
        Strings column used to separate individual strings into tokens
    stream : Stream | None
        CUDA stream on which to perform the operation.

    Returns
    -------
    Column
        New strings columns of tokens
    """
def count_tokens_scalar(input: Column, delimiter: Scalar | None=None, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """
    Returns the number of tokens in each string of a strings column
    using the provided characters as delimiters.

    For details, see cpp:func:`cudf::nvtext::count_tokens`

    Parameters
    ----------
    input : Column
        Strings column to count tokens
    delimiters : Scalar
        String scalar used to separate each string into tokens
    stream : Stream | None
        CUDA stream on which to perform the operation.

    Returns
    -------
    Column
        New column of token counts
    """
def count_tokens_column(input: Column, delimiters: Column, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """
    Returns the number of tokens in each string of a strings column
    using multiple strings as delimiters.

    For details, see cpp:func:`cudf::nvtext::count_tokens`

    Parameters
    ----------
    input : Column
        Strings column to count tokens
    delimiters : Column
        Strings column used to separate each string into tokens
    stream : Stream | None
        CUDA stream on which to perform the operation.

    Returns
    -------
    Column
        New column of token counts
    """
def character_tokenize(input: Column, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """
    Returns a single column of strings by converting
    each character to a string.

    For details, see cpp:func:`cudf::nvtext::character_tokens`

    Parameters
    ----------
    input : Column
        Strings column to tokenize
    stream : Stream | None
        CUDA stream on which to perform the operation.

    Returns
    -------
    Column
        New strings columns of tokens
    """
def detokenize(input: Column, row_indices: Column, separator: Scalar | None=None, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """
    Creates a strings column from a strings column of tokens
    and an associated column of row ids.

    For details, see cpp:func:`cudf::nvtext::detokenize`

    Parameters
    ----------
    input : Column
        Strings column to detokenize
    row_indices : Column
        The relative output row index assigned for each token in the input column
    separator : Scalar
        String to append after concatenating each token to the proper output row
    stream : Stream | None
        CUDA stream on which to perform the operation.

    Returns
    -------
    Column
        New strings columns of tokens
    """
def tokenize_with_vocabulary(input: Column, vocabulary: TokenizeVocabulary, delimiter: Scalar, default_id: size_type=-1, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """
    Returns the token ids for the input string by looking
    up each delimited token in the given vocabulary.

    For details, see cpp:func:`cudf::nvtext::tokenize_with_vocabulary`

    Parameters
    ----------
    input : Column
        Strings column to tokenize
    vocabulary : TokenizeVocabulary
        Used to lookup tokens within ``input``
    delimiter : Scalar
        Used to identify tokens within ``input``
    default_id : size_type
        The token id to be used for tokens not found in the vocabulary; Default is -1
    stream : Stream | None
        CUDA stream on which to perform the operation.

    Returns
    -------
    Column
        Lists column of token ids
    """
