# SPDX-FileCopyrightText: Copyright (c) 2025-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/nvtext/wordpiece_tokenize.pyx

from pylibcudf.column import Column
from pylibcudf.libcudf.types import size_type
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

__all__ = ['WordPieceVocabulary', 'wordpiece_tokenize']

class WordPieceVocabulary:
    """The Vocabulary object to be used with ``wordpiece_tokenize``.

    For details, see :cpp:class:`cudf::nvtext::wordpiece_tokenize`.
    """
    __hash__ = None

    def __init__(self, vocab: Column, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None): ...

def wordpiece_tokenize(input: Column, vocabulary: WordPieceVocabulary, max_words_per_row: size_type, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """
    Returns the token ids for the input string by looking
    up each delimited token in the given vocabulary.
    The input is expected to be normalized.

    For details, see cpp:func:`cudf::nvtext::wordpiece_tokenize`

    Parameters
    ----------
    input : Column
        Normalized strings column to tokenize
    vocabulary : WordPieceVocabulary
        Used to lookup tokens within ``input``
    max_words_per_row : size_type
        Maximum number of words to tokenize per input row
    stream : Stream | None
        CUDA stream on which to perform the operation.

    Returns
    -------
    Column
        Lists column of token ids
    """
