# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/strings/convert/convert_lists.pyx

from pylibcudf.column import Column
from pylibcudf.scalar import Scalar
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

__all__ = ['format_list_column']

def format_list_column(input: Column, na_rep: Scalar | None=None, separators: Column | None=None, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """
    Convert a list column of strings into a formatted strings column.

    For details, see :cpp:func`cudf::strings::format_list_column`

    Parameters
    ----------
    input : Column
        Lists column to format

    na_rep : Scalar
        Replacement string for null elements.
        Default, empty string

    separators : Column
        Strings to use for enclosing list components and separating elements.
        Default, ``,``, ``[``, ``]``

    stream : Stream | None
        CUDA stream on which to perform the operation.

    Returns
    -------
    Column
        New strings column
    """
