# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/strings/convert/convert_floats.pyx

from pylibcudf.column import Column
from pylibcudf.types import DataType
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

__all__ = ['from_floats', 'is_float', 'to_floats']

def to_floats(strings: Column, output_type: DataType, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """
    Returns a new numeric column by parsing float values from each string
    in the provided strings column.

    For details, see cpp:func:`cudf::strings::to_floats`

    Parameters
    ----------
    strings : Column
        Strings instance for this operation.

    output_type : DataType
        Type of float numeric column to return.

    stream : Stream | None
        CUDA stream on which to perform the operation.

    Returns
    -------
    Column
        New column with floats converted from strings.
    """
def from_floats(floats: Column, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """
    Returns a new strings column converting the float values from the
    provided column into strings.

    For details, see cpp:func:`cudf::strings::from_floats`

    Parameters
    ----------
    floats : Column
        Numeric column to convert.

    stream : Stream | None
        CUDA stream on which to perform the operation.

    Returns
    -------
    Column
        New strings column with floats as strings.
    """
def is_float(input: Column, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """
    Returns a boolean column identifying strings in which all
    characters are valid for conversion to floats.

    For details, see cpp:func:`cudf::strings::is_float`

    Parameters
    ----------
    input : Column
        Strings instance for this operation.

    stream : Stream | None
        CUDA stream on which to perform the operation.

    Returns
    -------
    Column
        New column of boolean results for each string.
    """
