# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/strings/convert/convert_fixed_point.pyx

from pylibcudf.column import Column
from pylibcudf.types import DataType
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

__all__ = ['from_fixed_point', 'is_fixed_point', 'to_fixed_point']

def to_fixed_point(input: Column, output_type: DataType, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """
    Returns a new fixed-point column parsing decimal values from the
    provided strings column.

    For details, see :cpp:func:`to_fixed_point`

    Parameters
    ----------
    input : Column
        Strings instance for this operation.

    output_type : DataType
        Type of fixed-point column to return including the scale value.

    stream : Stream | None
        CUDA stream on which to perform the operation.

    Returns
    -------
    Column
        New column of output_type.
    """
def from_fixed_point(input: Column, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """
    Returns a new strings column converting the fixed-point values
    into a strings column.

    For details, see :cpp:func:`from_fixed_point`

    Parameters
    ----------
    input : Column
        Fixed-point column to convert.

    stream : Stream | None
        CUDA stream on which to perform the operation.

    Returns
    -------
    Column
        New strings column.
    """
def is_fixed_point(input: Column, decimal_type: DataType | None=None, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """
    Returns a boolean column identifying strings in which all
    characters are valid for conversion to fixed-point.

    For details, see :cpp:func:`is_fixed_point`

    Parameters
    ----------
    input : Column
        Strings instance for this operation.

    decimal_type : DataType
        Fixed-point type (with scale) used only for checking overflow.
        Defaults to Decimal64

    stream : Stream | None
        CUDA stream on which to perform the operation.

    Returns
    -------
    Column
        New column of boolean results for each string.
    """
