# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/strings/convert/convert_ipv4.pyx

from pylibcudf.column import Column
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

__all__ = ['integers_to_ipv4', 'ipv4_to_integers', 'is_ipv4']

def ipv4_to_integers(input: Column, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """
    Converts IPv4 addresses into integers.

    For details, see cpp:func:`cudf::strings::ipv4_to_integers`

    Parameters
    ----------
    input : Column
        Strings instance for this operation

    stream : Stream | None
        CUDA stream on which to perform the operation.

    Returns
    -------
    Column
        New uint32 column converted from strings.
    """
def integers_to_ipv4(integers: Column, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """
    Converts integers into IPv4 addresses as strings.

    For details, see cpp:func:`cudf::strings::integers_to_ipv4`

    Parameters
    ----------
    integers : Column
        Integer (uint32) column to convert.

    stream : Stream | None
        CUDA stream on which to perform the operation.

    Returns
    -------
    Column
        New strings column.
    """
def is_ipv4(input: Column, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """
    Returns a boolean column identifying strings in which all
    characters are valid for conversion to integers from IPv4 format.

    For details, see cpp:func:`cudf::strings::is_ipv4`

    Parameters
    ----------
    input : Column
        Strings instance for this operation.

    stream : Stream | None
        CUDA stream on which to perform the operation.

    Returns
    -------
    Column
        New column of boolean results for each string.
    """
