# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/strings/convert/convert_integers.pyx

from pylibcudf.column import Column
from pylibcudf.types import DataType
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource

__all__ = ['from_integers', 'hex_to_integers', 'integers_to_hex', 'is_hex', 'is_integer', 'to_integers']

def to_integers(input: Column, output_type: DataType, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """
    Returns a new integer numeric column parsing integer values from the
    provided strings column.

    For details, cpp:func:`cudf::strings::to_integers`.

    Parameters
    ----------
    input : Column
        Strings instance for this operation.

    output_type : DataType
        Type of integer numeric column to return.

    stream : Stream | None
        CUDA stream on which to perform the operation.

    Returns
    -------
    Column
        New column with integers converted from strings.
    """
def from_integers(integers: Column, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """
    Returns a new strings column converting the integer values from the
    provided column into strings.

    For details, cpp:func:`cudf::strings::from_integers`.

    Parameters
    ----------
    integers : Column
        Strings instance for this operation.

    stream : Stream | None
        CUDA stream on which to perform the operation.

    Returns
    -------
    Column
        New strings column with integers as strings.
    """
def is_integer(input: Column, int_type: DataType | None=None, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """
    Returns a boolean column identifying strings in which all
    characters are valid for conversion to integers.

    For details, cpp:func:`cudf::strings::is_integer`.

    Parameters
    ----------
    input : Column
        Strings instance for this operation.

    int_type : DataType
        Integer type used for checking underflow and overflow.
        By default, does not check an integer type for underflow
        or overflow.

    stream : Stream | None
        CUDA stream on which to perform the operation.

    Returns
    -------
    Column
        New column of boolean results for each string.
    """
def hex_to_integers(input: Column, output_type: DataType, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """
    Returns a new integer numeric column parsing hexadecimal values
    from the provided strings column.

    For details, cpp:func:`cudf::strings::hex_to_integers`.

    Parameters
    ----------
    input : Column
        Strings instance for this operation.

    output_type : DataType
        Type of integer numeric column to return.

    stream : Stream | None
        CUDA stream on which to perform the operation.

    Returns
    -------
    Column
        New column with integers converted from strings.
    """
def is_hex(input: Column, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """
    Returns a boolean column identifying strings in which all
    characters are valid for conversion to integers from hex.

    For details, cpp:func:`cudf::strings::is_hex`.

    Parameters
    ----------
    input : Column
        Strings instance for this operation.

    stream : Stream | None
        CUDA stream on which to perform the operation.

    Returns
    -------
    Column
        New column of boolean results for each string.
    """
def integers_to_hex(input: Column, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
    """
    Returns a new strings column converting integer columns to hexadecimal
    characters.

    For details, cpp:func:`cudf::strings::integers_to_hex`.

    Parameters
    ----------
    input : Column
        Integer column to convert to hex.

    stream : Stream | None
        CUDA stream on which to perform the operation.

    Returns
    -------
    Column
        New strings column with hexadecimal characters.
    """
