# SPDX-FileCopyrightText: Copyright (c) 2025-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# This file was generated by stubgen-pyx v0.2.18 from python/pylibcudf/pylibcudf/io/experimental/hybrid_scan.pyx

import pylibcudf.libcudf.io.hybrid_scan
from pylibcudf.column import Column
from pylibcudf.io.parquet import ParquetReaderOptions
from pylibcudf.io.parquet_metadata import FileMetaData
from pylibcudf.io.parquet_metadata import FileMetaData as c_FileMetaData
from pylibcudf.io.text import ByteRangeInfo
from pylibcudf.io.types import TableWithMetadata
from pylibcudf.libcudf.io.hybrid_scan import \
    use_data_page_mask as cpp_use_data_page_mask
from pylibcudf.typing import CudaStreamLike
from rmm.pylibrmm.memory_resource import DeviceMemoryResource
from typing_extensions import Buffer

UseDataPageMask = pylibcudf.libcudf.io.hybrid_scan.use_data_page_mask
__all__ = ['FileMetaData', 'HybridScanReader', 'UseDataPageMask']

class HybridScanReader:
    """Experimental Parquet reader optimized for highly selective filters.

    This class implements a hybrid scan operation for reading Parquet files
    with highly selective filters. It reads in two passes: first reading
    filter columns to build a row mask, then reading payload columns using
    that mask for optimization.

    For details, see :cpp:class:`cudf::io::parquet::experimental::hybrid_scan_reader`

    Parameters
    ----------
    footer_bytes : Buffer
        Parquet file footer bytes
    options : ParquetReaderOptions
        Parquet reader options

    Examples
    --------
    >>> import pylibcudf as plc
    >>> # Create reader from footer bytes
    >>> reader = plc.io.hybrid_scan.HybridScanReader(footer_bytes, options)
    >>> # Get metadata
    >>> metadata = reader.parquet_metadata()
    >>> # Get all row groups
    >>> row_groups = reader.all_row_groups(options)
    """
    def __init__(self, footer_bytes: Buffer, options: ParquetReaderOptions): ...
    @staticmethod
    def from_parquet_metadata(metadata: c_FileMetaData, options: ParquetReaderOptions) -> HybridScanReader:
        """Create a HybridScanReader from pre-populated metadata.

        Parameters
        ----------
        metadata : FileMetaData
            Pre-populated Parquet file metadata
        options : ParquetReaderOptions
            Parquet reader options

        Returns
        -------
        HybridScanReader
        """
    def parquet_metadata(self) -> FileMetaData:
        """Get the Parquet file footer metadata.

        Returns
        -------
        FileMetaData
            Parquet file footer metadata
        """
    def page_index_byte_range(self) -> ByteRangeInfo:
        """Get the byte range of the page index.

        Returns
        -------
        ByteRangeInfo
            Byte range of the page index
        """
    def setup_page_index(self, page_index_bytes: Buffer) -> None:
        """Setup the page index within the Parquet file metadata.

        Parameters
        ----------
        page_index_bytes : Buffer
            Parquet page index buffer bytes
        """
    def all_row_groups(self, options: ParquetReaderOptions) -> list[int]:
        """Get all available row groups from the parquet file.

        Parameters
        ----------
        options : ParquetReaderOptions
            Parquet reader options

        Returns
        -------
        list[int]
            List of row group indices
        """
    def total_rows_in_row_groups(self, row_group_indices: list[int]) -> int:
        """Get the total number of top-level rows in the row groups.

        Parameters
        ----------
        row_group_indices : list[int]
            Input row group indices

        Returns
        -------
        int
            Total number of top-level rows
        """
    def reset_column_selection(self) -> None:
        """Reset the column selection state.

        Resets the internal column selection state forcing re-selection of columns in
        subsequent filter and read operations
        """
    def filter_row_groups_with_stats(self, row_group_indices: list[int], options: ParquetReaderOptions, stream: CudaStreamLike | None=None) -> list[int]:
        """Filter row groups using column chunk statistics.

        Parameters
        ----------
        row_group_indices : list[int]
            Input row group indices
        options : ParquetReaderOptions
            Parquet reader options
        stream : Stream, optional
            CUDA stream

        Returns
        -------
        list[int]
            Filtered row group indices
        """
    def secondary_filters_byte_ranges(self, row_group_indices: list[int], options: ParquetReaderOptions) -> tuple[list[ByteRangeInfo], list[ByteRangeInfo]]:
        """Get byte ranges of bloom filters and dictionary pages.

        Parameters
        ----------
        row_group_indices : list[int]
            Input row group indices
        options : ParquetReaderOptions
            Parquet reader options

        Returns
        -------
        tuple[list[ByteRangeInfo], list[ByteRangeInfo]]
            Tuple of (bloom_filter_ranges, dictionary_page_ranges)
        """
    def filter_row_groups_with_dictionary_pages(self, dictionary_page_data: list, row_group_indices: list[int], options: ParquetReaderOptions, stream: CudaStreamLike | None=None) -> list[int]:
        """Filter row groups using column chunk dictionary pages.

        Parameters
        ----------
        dictionary_page_data : list
            Span-like objects containing dictionary page data
        row_group_indices : list[int]
            Input row group indices
        options : ParquetReaderOptions
            Parquet reader options
        stream : Stream, optional
            CUDA stream

        Returns
        -------
        list[int]
            Filtered row group indices
        """
    def filter_row_groups_with_bloom_filters(self, bloom_filter_data: list, row_group_indices: list[int], options: ParquetReaderOptions, stream: CudaStreamLike | None=None) -> list[int]:
        """Filter row groups using column chunk bloom filters.

        Parameters
        ----------
        bloom_filter_data : list
            Span-like objects containing bloom filter data
        row_group_indices : list[int]
            Input row group indices
        options : ParquetReaderOptions
            Parquet reader options
        stream : Stream, optional
            CUDA stream

        Returns
        -------
        list[int]
            Filtered row group indices
        """
    def build_row_mask_with_page_index_stats(self, row_group_indices: list[int], options: ParquetReaderOptions, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> Column:
        """Build a boolean column indicating surviving rows from page stats.

        Parameters
        ----------
        row_group_indices : list[int]
            Input row group indices
        options : ParquetReaderOptions
            Parquet reader options
        stream : Stream, optional
            CUDA stream
        mr : DeviceMemoryResource, optional
            Device memory resource

        Returns
        -------
        Column
            Boolean column indicating surviving rows
        """
    def filter_column_chunks_byte_ranges(self, row_group_indices: list[int], options: ParquetReaderOptions) -> list[ByteRangeInfo]:
        """Get byte ranges of column chunks of filter columns.

        Parameters
        ----------
        row_group_indices : list[int]
            Input row group indices
        options : ParquetReaderOptions
            Parquet reader options

        Returns
        -------
        list[ByteRangeInfo]
            Byte ranges to column chunks of filter columns
        """
    def materialize_filter_columns(self, row_group_indices: list[int], column_chunk_data: list, row_mask: Column, mask_data_pages: cpp_use_data_page_mask, options: ParquetReaderOptions, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> TableWithMetadata:
        """Materialize filter columns and update the row mask.

        Parameters
        ----------
        row_group_indices : list[int]
            Input row group indices
        column_chunk_data : list
            Span-like objects containing column chunk data of filter columns
        row_mask : Column
            Mutable boolean column indicating surviving rows
        mask_data_pages : UseDataPageMask
            Whether to use a data page mask
        options : ParquetReaderOptions
            Parquet reader options
        stream : Stream, optional
            CUDA stream
        mr : DeviceMemoryResource, optional
            Device memory resource

        Returns
        -------
        TableWithMetadata
            Table of materialized filter columns and metadata
        """
    def payload_column_chunks_byte_ranges(self, row_group_indices: list[int], options: ParquetReaderOptions) -> list[ByteRangeInfo]:
        """Get byte ranges of column chunks of payload columns.

        Parameters
        ----------
        row_group_indices : list[int]
            Input row group indices
        options : ParquetReaderOptions
            Parquet reader options

        Returns
        -------
        list[ByteRangeInfo]
            Byte ranges to column chunks of payload columns
        """
    def materialize_payload_columns(self, row_group_indices: list[int], column_chunk_data: list, row_mask: Column, mask_data_pages: cpp_use_data_page_mask, options: ParquetReaderOptions, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> TableWithMetadata:
        """Materialize payload columns and apply the row mask.

        Parameters
        ----------
        row_group_indices : list[int]
            Input row group indices
        column_chunk_data : list
            Span-like objects containing column chunk data of payload columns
        row_mask : Column
            Boolean column indicating surviving rows
        mask_data_pages : UseDataPageMask
            Whether to use a data page mask
        options : ParquetReaderOptions
            Parquet reader options
        stream : Stream, optional
            CUDA stream
        mr : DeviceMemoryResource, optional
            Device memory resource

        Returns
        -------
        TableWithMetadata
            Table of materialized payload columns and metadata
        """
    def all_column_chunks_byte_ranges(self, row_group_indices: list[int], options: ParquetReaderOptions) -> list[ByteRangeInfo]:
        """Get byte ranges of column chunks of all columns.

        Parameters
        ----------
        row_group_indices : list[int]
            Input row group indices
        options : ParquetReaderOptions
            Parquet reader options

        Returns
        -------
        list[ByteRangeInfo]
            Byte ranges to column chunks of all columns
        """
    def materialize_all_columns(self, row_group_indices: list[int], column_chunk_data: list, options: ParquetReaderOptions, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> TableWithMetadata:
        """Materialize all columns.

        Parameters
        ----------
        row_group_indices : list[int]
            Input row group indices
        column_chunk_data : list
            Span-like objects containing column chunk data of all columns
        options : ParquetReaderOptions
            Parquet reader options
        stream : Stream, optional
            CUDA stream
        mr : DeviceMemoryResource, optional
            Device memory resource

        Returns
        -------
        TableWithMetadata
            Table of materialized all columns and metadata
        """
    def setup_chunking_for_filter_columns(self, chunk_read_limit: int, pass_read_limit: int, row_group_indices: list[int], row_mask: Column, mask_data_pages: cpp_use_data_page_mask, column_chunk_data: list, options: ParquetReaderOptions, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> None:
        """Setup chunking information for filter columns.

        Parameters
        ----------
        chunk_read_limit : int
            Limit on bytes returned per chunk (0 for no limit)
        pass_read_limit : int
            Limit on memory for reading/decompressing (0 for no limit)
        row_group_indices : list[int]
            Input row group indices
        row_mask : Column
            Boolean column indicating surviving rows
        mask_data_pages : UseDataPageMask
            Whether to use a data page mask
        column_chunk_data : list
            Span-like objects containing column chunk data of filter columns
        options : ParquetReaderOptions
            Parquet reader options
        stream : Stream, optional
            CUDA stream
        mr : DeviceMemoryResource, optional
            Device memory resource
        """
    def materialize_filter_columns_chunk(self, row_mask: Column) -> TableWithMetadata:
        """Materialize a chunk of filter columns.

        Parameters
        ----------
        row_mask : Column
            Mutable boolean column indicating surviving rows
        Returns
        -------
        TableWithMetadata
            Table chunk of materialized filter columns and metadata
        """
    def setup_chunking_for_payload_columns(self, chunk_read_limit: int, pass_read_limit: int, row_group_indices: list[int], row_mask: Column, mask_data_pages: cpp_use_data_page_mask, column_chunk_data: list, options: ParquetReaderOptions, stream: CudaStreamLike | None=None, mr: DeviceMemoryResource | None=None) -> None:
        """Setup chunking information for payload columns.

        Parameters
        ----------
        chunk_read_limit : int
            Limit on bytes returned per chunk (0 for no limit)
        pass_read_limit : int
            Limit on memory for reading/decompressing (0 for no limit)
        row_group_indices : list[int]
            Input row group indices
        row_mask : Column
            Boolean column indicating surviving rows
        mask_data_pages : UseDataPageMask
            Whether to use a data page mask
        column_chunk_data : list
            Span-like objects containing column chunk data of payload columns
        options : ParquetReaderOptions
            Parquet reader options
        stream : Stream, optional
            CUDA stream
        mr : DeviceMemoryResource, optional
            Device memory resource
        """
    def materialize_payload_columns_chunk(self, row_mask: Column) -> TableWithMetadata:
        """Materialize a chunk of payload columns.

        Parameters
        ----------
        row_mask : Column
            Boolean column indicating surviving rows
        Returns
        -------
        TableWithMetadata
            Table chunk of materialized payload columns and metadata
        """
    def construct_row_group_passes(self, row_group_indices: list[int], pass_read_limit: int) -> list[list[int]]:
        """Partition row groups into passes such that the GPU memory required to
        materialize a pass is bounded by the specified limit.

        Note that ``pass_read_limit`` is a hint, not an absolute limit. i.e. if
        a row group cannot fit within the limit, it will still constitute a valid
        pass.

        Parameters
        ----------
        row_group_indices : list[int]
            Input row group indices
        pass_read_limit : int
            Limit on the amount of memory used for reading and decompressing data
        or 0 if there is no limit.

        Returns
        -------
        list[list[int]]
            Lists of row group indices, one per pass.

        Raises
        ------
        ValueError
            If ``row_group_indices`` is empty.
        """
    def has_next_table_chunk(self) -> bool:
        """Check if there is any parquet data left to read.

        Returns
        -------
        bool
            True if there is data left to read
        """
